# 04e — Siamese CNN: Cosine Similarity / CosineEmbeddingLoss

## Obiettivo

Questo notebook studia la variante cosine della Siamese Network applicata
alle FCGR con `k=6`.

Il punto di partenza è la migliore configurazione ottenuta con
Euclidean Contrastive Loss:

- CNN encoder con GroupNorm;
- nessun Dropout;
- embedding dimension = 128;
- embedding L2-normalizzati;
- batch size = 128;
- learning rate iniziale = 5e-4;
- AdamW fused;
- AMP;
- forward dei due rami concatenata;
- pair dinamiche 50/50;
- split train/validation/test invariati e senza leakage;
- checkpoint selezionato tramite Validation ROC-AUC.

La modifica principale è:

Euclidean Contrastive Loss
→
Cosine similarity + CosineEmbeddingLoss

Il miglior margin euclideo precedente è:

margin = 1.25

Per embedding L2-normalizzati:

d² = 2 - 2 cos(θ)

quindi il valore geometricamente equivalente nel dominio cosine è:

cos_margin = 1 - 1.25² / 2 = 0.21875

Questo valore viene utilizzato come configurazione di riferimento,
ma NON viene assunto come margin cosine ottimale.

Verrà successivamente eseguita una cosine-margin ablation.

## Obiettivi secondari

Il notebook introduce inoltre ottimizzazioni della pipeline per ridurre
il tempo di training:

- meno trasferimenti GPU → CPU;
- trasferimenti CPU → GPU non bloccanti;
- DataLoader più leggero;
- forward concatenata;
- calcolo della cosine similarity senza operazioni duplicate;
- benchmark separato del DataLoader;
- eventuale torch.compile solo dopo benchmark.

## Metriche

Per ogni esperimento verranno analizzate:

- Validation ROC-AUC;
- Test ROC-AUC;
- Macro-F1;
- Balanced Accuracy;
- cosine similarity positiva;
- cosine similarity negativa;
- cosine gap;
- cosine d-prime;
- distanza euclidea positiva d+;
- distanza euclidea negativa d-;
- distance gap;
- euclidean d-prime.

In [1]:
from pathlib import Path

import json
import random
import time
import gc

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import (
    Dataset,
    DataLoader,
    get_worker_info,
)

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)


print("=" * 60)
print("ENVIRONMENT")
print("=" * 60)

print("PyTorch:", torch.__version__)
print("CUDA disponibile:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "Compute capability:",
        torch.cuda.get_device_capability(0),
    )

    total_memory = (
        torch.cuda.get_device_properties(0).total_memory
        / 1024**3
    )

    print(
        f"VRAM totale: {total_memory:.2f} GB"
    )

============================================================
ENVIRONMENT
============================================================
PyTorch: 2.12.0+cu126
CUDA disponibile: True
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
Compute capability: (8, 6)
VRAM totale: 6.00 GB

In [2]:
# ============================================================
# PROJECT PATHS
# ============================================================

CURRENT_DIR = Path.cwd().resolve()

if CURRENT_DIR.name == "notebooks":
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    PROJECT_ROOT = CURRENT_DIR


PROCESSED_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
)


ARTIFACTS_DIR = (
    PROJECT_ROOT
    / "artifacts"
    / "siamese_cosine"
)

ARTIFACTS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# INPUT FILES
# ============================================================

PAIR_CONFIG_PATH = (
    PROCESSED_DIR
    / "siamese_pair_config.json"
)

MANIFEST_PATH = (
    PROCESSED_DIR
    / "siamese_primary_manifest.tsv"
)

VAL_POOL_PATH = (
    PROCESSED_DIR
    / "siamese_val_pair_pool.tsv"
)

TEST_POOL_PATH = (
    PROCESSED_DIR
    / "siamese_test_pair_pool.tsv"
)


# ============================================================
# LOAD PAIR CONFIG
# ============================================================

with open(
    PAIR_CONFIG_PATH,
    "r",
    encoding="utf-8",
) as file:
    PAIR_CONFIG = json.load(file)


K = int(
    PAIR_CONFIG["k"]
)

TRAIN_PAIRS_PER_EPOCH = int(
    PAIR_CONFIG["train_pairs_per_epoch"]
)

VAL_PAIRS = int(
    PAIR_CONFIG["val_pairs"]
)

TEST_PAIRS = int(
    PAIR_CONFIG["test_pairs"]
)

POSITIVE_PAIR_PROBABILITY = float(
    PAIR_CONFIG["positive_probability"]
)

RANDOM_STATE = int(
    PAIR_CONFIG["random_state"]
)


# ============================================================
# FCGR CACHE
# ============================================================

FCGR_MEMMAP_PATH = (
    PROCESSED_DIR
    / "fcgr_cache"
    / f"fcgr_k{K}.npy"
)

FCGR_INDEX_PATH = (
    PROCESSED_DIR
    / "fcgr_cache"
    / f"fcgr_k{K}_index.tsv"
)


print("=" * 60)
print("PROJECT")
print("=" * 60)

print("Project root:")
print(PROJECT_ROOT)

print()

print("Processed data:")
print(PROCESSED_DIR)

print()

print("Artifacts:")
print(ARTIFACTS_DIR)

print()

print("k:", K)
print(
    "Train pairs / epoch:",
    f"{TRAIN_PAIRS_PER_EPOCH:,}",
)
print(
    "Validation pairs:",
    f"{VAL_PAIRS:,}",
)
print(
    "Test pairs:",
    f"{TEST_PAIRS:,}",
)
print(
    "Positive probability:",
    POSITIVE_PAIR_PROBABILITY,
)
print(
    "Random state:",
    RANDOM_STATE,
)

============================================================
PROJECT
============================================================
Project root:
D:\Daria\Desktop\eccdna_fcgr_siamese

Processed data:
D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed

Artifacts:
D:\Daria\Desktop\eccdna_fcgr_siamese\artifacts\siamese_cosine

k: 6
Train pairs / epoch: 50,000
Validation pairs: 10,000
Test pairs: 10,000
Positive probability: 0.5
Random state: 42

In [3]:
# ============================================================
# MODEL
# ============================================================

EMBEDDING_DIM = 128


# ============================================================
# TRAINING
# ============================================================

BATCH_SIZE = 128

LEARNING_RATE = 5e-4

WEIGHT_DECAY = 1e-4

MAX_EPOCHS = 50

EARLY_STOPPING_PATIENCE = 10

MIN_DELTA = 1e-4


# ============================================================
# COSINE LOSS
# ============================================================

EUCLIDEAN_REFERENCE_MARGIN = 1.25

REFERENCE_COSINE_MARGIN = (
    1.0
    - (EUCLIDEAN_REFERENCE_MARGIN ** 2) / 2.0
)


# Margin che testeremo DOPO la reference run.
COSINE_MARGIN_CANDIDATES = [
    0.00,
    0.10,
    REFERENCE_COSINE_MARGIN,
    0.35,
]


# ============================================================
# PERFORMANCE
# ============================================================

USE_AMP = True

PIN_MEMORY = torch.cuda.is_available()

NUM_WORKERS = 0

USE_TORCH_COMPILE = False


print("=" * 60)
print("EXPERIMENT CONFIGURATION")
print("=" * 60)

print("Embedding dim:", EMBEDDING_DIM)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Weight decay:", WEIGHT_DECAY)
print("Max epochs:", MAX_EPOCHS)
print(
    "Early stopping patience:",
    EARLY_STOPPING_PATIENCE,
)

print()

print(
    "Euclidean reference margin:",
    EUCLIDEAN_REFERENCE_MARGIN,
)

print(
    "Equivalent cosine margin:",
    REFERENCE_COSINE_MARGIN,
)

print(
    "Cosine margin candidates:",
    COSINE_MARGIN_CANDIDATES,
)

print()

print("AMP:", USE_AMP)
print("Pin memory:", PIN_MEMORY)
print("Num workers:", NUM_WORKERS)
print("torch.compile:", USE_TORCH_COMPILE)

============================================================
EXPERIMENT CONFIGURATION
============================================================
Embedding dim: 128
Batch size: 128
Learning rate: 0.0005
Weight decay: 0.0001
Max epochs: 50
Early stopping patience: 10

Euclidean reference margin: 1.25
Equivalent cosine margin: 0.21875
Cosine margin candidates: [0.0, 0.1, 0.21875, 0.35]

AMP: True
Pin memory: True
Num workers: 0
torch.compile: False

In [4]:
def set_seed(seed: int) -> None:

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


set_seed(
    RANDOM_STATE
)


DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


# ============================================================
# CUDA PERFORMANCE
# ============================================================

if DEVICE.type == "cuda":

    # Input FCGR sempre 64x64:
    # cuDNN può scegliere il kernel convoluzionale più efficiente.
    torch.backends.cudnn.benchmark = True

    torch.set_float32_matmul_precision(
        "high"
    )


print("=" * 60)
print("DEVICE CONFIGURATION")
print("=" * 60)

print("Device:", DEVICE)

print(
    "cuDNN benchmark:",
    torch.backends.cudnn.benchmark,
)

if DEVICE.type == "cuda":

    print(
        "Allocated VRAM:",
        f"{torch.cuda.memory_allocated() / 1024**2:.1f} MB",
    )

    print(
        "Reserved VRAM:",
        f"{torch.cuda.memory_reserved() / 1024**2:.1f} MB",
    )

============================================================
DEVICE CONFIGURATION
============================================================
Device: cuda
cuDNN benchmark: True
Allocated VRAM: 0.0 MB
Reserved VRAM: 0.0 MB

In [5]:
# ============================================================
# CELL 5 — DATA / PATH DIAGNOSTICS + LOAD
# ============================================================

print("=" * 70)
print("PATH DIAGNOSTICS")
print("=" * 70)

print("Current working directory:")
print(Path.cwd().resolve())

print()

print("PROJECT_ROOT:")
print(PROJECT_ROOT)

print()

print("PROCESSED_DIR:")
print(PROCESSED_DIR)

print()


# ============================================================
# HELPER: RESOLVE FILE IF EXPECTED PATH IS WRONG
# ============================================================

def resolve_file(
    expected_path,
    filename,
    search_root=None,
):
    """
    Usa expected_path se esiste.
    Altrimenti cerca filename ricorsivamente dentro search_root.
    """

    expected_path = Path(expected_path)

    if expected_path.exists():

        print(f"[OK] {filename}")
        print(f"     {expected_path}")

        return expected_path


    print(f"[MISSING] {expected_path}")


    if search_root is None:
        search_root = PROJECT_ROOT


    matches = list(
        Path(search_root).rglob(filename)
    )


    if len(matches) == 0:

        raise FileNotFoundError(
            f"\nFile non trovato: {filename}\n"
            f"Path previsto:\n{expected_path}\n\n"
            f"Nessuna copia trovata dentro:\n"
            f"{search_root}"
        )


    if len(matches) > 1:

        print()
        print(
            f"ATTENZIONE: trovate {len(matches)} copie "
            f"di {filename}:"
        )

        for match in matches:
            print("  ", match)

        print()
        print(
            "Uso la prima copia trovata:"
        )


    resolved = matches[0]

    print(f"[FOUND] {filename}")
    print(f"        {resolved}")

    return resolved


# ============================================================
# RESOLVE REQUIRED FILES
# ============================================================

PAIR_CONFIG_PATH = resolve_file(
    PAIR_CONFIG_PATH,
    "siamese_pair_config.json",
)


MANIFEST_PATH = resolve_file(
    MANIFEST_PATH,
    "siamese_primary_manifest.tsv",
)


VAL_POOL_PATH = resolve_file(
    VAL_POOL_PATH,
    "siamese_val_pair_pool.tsv",
)


TEST_POOL_PATH = resolve_file(
    TEST_POOL_PATH,
    "siamese_test_pair_pool.tsv",
)


FCGR_MEMMAP_PATH = resolve_file(
    FCGR_MEMMAP_PATH,
    f"fcgr_k{K}.npy",
)


FCGR_INDEX_PATH = resolve_file(
    FCGR_INDEX_PATH,
    f"fcgr_k{K}_index.tsv",
)


# ============================================================
# LOAD FILES
# ============================================================

manifest = pd.read_csv(
    MANIFEST_PATH,
    sep="\t",
)


fcgr_index = pd.read_csv(
    FCGR_INDEX_PATH,
    sep="\t",
)


val_pool = pd.read_csv(
    VAL_POOL_PATH,
    sep="\t",
)


test_pool = pd.read_csv(
    TEST_POOL_PATH,
    sep="\t",
)


# ============================================================
# PRINT RAW STRUCTURE
# ============================================================

print()
print("=" * 70)
print("MANIFEST STRUCTURE")
print("=" * 70)

print("Shape:")
print(manifest.shape)

print()

print("Columns:")
print(
    manifest.columns.tolist()
)


print()
print("=" * 70)
print("FCGR INDEX STRUCTURE")
print("=" * 70)

print("Shape:")
print(fcgr_index.shape)

print()

print("Columns:")
print(
    fcgr_index.columns.tolist()
)


print()
print("=" * 70)
print("VALIDATION PAIR POOL STRUCTURE")
print("=" * 70)

print("Shape:")
print(val_pool.shape)

print()

print("Columns:")
print(
    val_pool.columns.tolist()
)


print()
print("=" * 70)
print("TEST PAIR POOL STRUCTURE")
print("=" * 70)

print("Shape:")
print(test_pool.shape)

print()

print("Columns:")
print(
    test_pool.columns.tolist()
)


# ============================================================
# DATASET SEMANTIC COLUMNS
# ============================================================

ID_COL = "id"

CLASS_COL = "class_id"

SPLIT_COL = "split_cluster"


required_columns = {
    ID_COL,
    CLASS_COL,
    SPLIT_COL,
}


missing_columns = (
    required_columns
    -
    set(manifest.columns)
)


if missing_columns:

    raise KeyError(
        "Colonne richieste mancanti nel manifest: "
        f"{sorted(missing_columns)}"
    )


# ============================================================
# CHECK DISEASE_GROUP / CLASS_ID RELATION
# ============================================================

if "class_id" in manifest.columns:

    group_to_id = (
        manifest
        .groupby("disease_group")["class_id"]
        .nunique()
    )

    id_to_group = (
        manifest
        .groupby("class_id")["disease_group"]
        .nunique()
    )


    class_mapping_is_one_to_one = (
        group_to_id.max() == 1
        and
        id_to_group.max() == 1
    )


    print()
    print("=" * 70)
    print("CLASS MAPPING CHECK")
    print("=" * 70)

    print(
        "disease_group <-> class_id one-to-one:",
        class_mapping_is_one_to_one,
    )

    print()

    display(
        manifest[
            [
                "disease_group",
                "class_id",
            ]
        ]
        .drop_duplicates()
        .sort_values("class_id")
        .reset_index(drop=True)
    )


# ============================================================
# CHECK SPLIT VALUES
# ============================================================

print()
print("=" * 70)
print("RAW split_cluster VALUES")
print("=" * 70)

print(
    manifest[SPLIT_COL]
    .value_counts(
        dropna=False
    )
)


print()
print("Unique values:")

print(
    manifest[SPLIT_COL]
    .drop_duplicates()
    .tolist()
)


# ============================================================
# NORMALIZE SPLIT
# ============================================================

def normalize_split(value):

    value = (
        str(value)
        .strip()
        .lower()
    )

    aliases = {

        "training": "train",
        "tr": "train",

        "validation": "val",
        "valid": "val",
        "dev": "val",

        "testing": "test",
        "te": "test",
    }

    return aliases.get(
        value,
        value,
    )


manifest["_split_normalized"] = (
    manifest[SPLIT_COL]
    .map(normalize_split)
)


print()
print("=" * 70)
print("NORMALIZED SPLIT VALUES")
print("=" * 70)

print(
    manifest["_split_normalized"]
    .value_counts(
        dropna=False
    )
)


# ============================================================
# LOAD FCGR MEMMAP
# ============================================================

fcgr_memmap_check = np.load(
    FCGR_MEMMAP_PATH,
    mmap_mode="r",
)


print()
print("=" * 70)
print("FCGR CACHE")
print("=" * 70)

print(
    "Path:",
    FCGR_MEMMAP_PATH,
)

print(
    "Shape:",
    fcgr_memmap_check.shape,
)

print(
    "dtype:",
    fcgr_memmap_check.dtype,
)

print(
    "Index rows:",
    len(fcgr_index),
)


# ============================================================
# FINAL DIAGNOSTIC
# ============================================================

print()
print("=" * 70)
print("DIAGNOSTIC COMPLETE")
print("=" * 70)

print(
    "ID_COL:",
    ID_COL,
)

print(
    "CLASS_COL:",
    CLASS_COL,
)

print(
    "SPLIT_COL:",
    SPLIT_COL,
)

======================================================================
PATH DIAGNOSTICS
======================================================================
Current working directory:
D:\Daria\Desktop\eccdna_fcgr_siamese\notebooks

PROJECT_ROOT:
D:\Daria\Desktop\eccdna_fcgr_siamese

PROCESSED_DIR:
D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed

[OK] siamese_pair_config.json
     D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\siamese_pair_config.json
[OK] siamese_primary_manifest.tsv
     D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\siamese_primary_manifest.tsv
[OK] siamese_val_pair_pool.tsv
     D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\siamese_val_pair_pool.tsv
[OK] siamese_test_pair_pool.tsv
     D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\siamese_test_pair_pool.tsv
[OK] fcgr_k6.npy
     D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\fcgr_cache\fcgr_k6.npy
[OK] fcgr_k6_index.tsv
     D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\fcgr_cache\fcgr_k6_index.tsv

======================================================================
MANIFEST STRUCTURE
======================================================================
Shape:
(665681, 12)

Columns:
['id', 'disease', 'disease_clean', 'disease_group', 'class_id', 'split_cluster', 'cluster_id', 'length', 'gc', 'n_fraction', 'source_db', 'tissue']

======================================================================
FCGR INDEX STRUCTURE
======================================================================
Shape:
(150272, 5)

Columns:
['fcgr_row', 'id', 'class_id', 'disease_clean', 'split_cluster']

======================================================================
VALIDATION PAIR POOL STRUCTURE
======================================================================
Shape:
(12937, 12)

Columns:
['id', 'disease', 'disease_clean', 'disease_group', 'class_id', 'split_cluster', 'cluster_id', 'length', 'gc', 'n_fraction', 'source_db', 'tissue']

======================================================================
TEST PAIR POOL STRUCTURE
======================================================================
Shape:
(11070, 12)

Columns:
['id', 'disease', 'disease_clean', 'disease_group', 'class_id', 'split_cluster', 'cluster_id', 'length', 'gc', 'n_fraction', 'source_db', 'tissue']

======================================================================
CLASS MAPPING CHECK
======================================================================
disease_group <-> class_id one-to-one: False

         disease_group  class_id
0               cancer         0
1              healthy         1
2               cancer         2
3               cancer         3
4               cancer         4
5               cancer         5
6   non_cancer_disease         6
7               cancer         7
8               cancer         8
9   non_cancer_disease         9
10  non_cancer_disease        10
11              cancer        11
12              cancer        12
13              cancer        13
14  non_cancer_disease        14
15              cancer        15
16  non_cancer_disease        16
17  non_cancer_disease        17

======================================================================
RAW split_cluster VALUES
======================================================================
split_cluster
val      358124
test     181292
train    126265
Name: count, dtype: int64

Unique values:
['train', 'val', 'test']

======================================================================
NORMALIZED SPLIT VALUES
======================================================================
_split_normalized
val      358124
test     181292
train    126265
Name: count, dtype: int64

======================================================================
FCGR CACHE
======================================================================
Path: D:\Daria\Desktop\eccdna_fcgr_siamese\data\processed\fcgr_cache\fcgr_k6.npy
Shape: (150272, 64, 64)
dtype: float32
Index rows: 150272

======================================================================
DIAGNOSTIC COMPLETE
======================================================================
ID_COL: id
CLASS_COL: class_id
SPLIT_COL: split_cluster

In [6]:
# ============================================================
# CELL 6 — PREPARE DATA POOLS
# Baseline-compatible
# ============================================================

metadata = (
    manifest
    .copy()
    .reset_index(drop=True)
)


val_pair_pool = (
    val_pool
    .copy()
    .reset_index(drop=True)
)


test_pair_pool = (
    test_pool
    .copy()
    .reset_index(drop=True)
)


# ============================================================
# NORMALIZE IDS
# ============================================================

for dataframe in [
    metadata,
    val_pair_pool,
    test_pair_pool,
]:

    dataframe["id"] = (
        dataframe["id"]
        .astype(str)
    )


# ============================================================
# TRAIN SPLIT
# ============================================================

train_metadata = (
    metadata[
        metadata["split_cluster"] == "train"
    ]
    .copy()
    .reset_index(drop=True)
)


# ============================================================
# CLASS ID
# ============================================================

for dataframe in [
    train_metadata,
    val_pair_pool,
    test_pair_pool,
]:

    if "class_id" not in dataframe.columns:

        raise KeyError(
            "Manca la colonna 'class_id'.\n"
            f"Colonne disponibili: "
            f"{dataframe.columns.tolist()}"
        )

    dataframe["class_id"] = (
        dataframe["class_id"]
        .astype(int)
    )


# ============================================================
# VALIDATION
# ============================================================

if len(train_metadata) == 0:

    raise RuntimeError(
        "Training split vuoto."
    )


for name, dataframe in [

    ("train", train_metadata),

    ("validation", val_pair_pool),

    ("test", test_pair_pool),

]:

    if dataframe["id"].duplicated().any():

        duplicated = int(
            dataframe["id"]
            .duplicated()
            .sum()
        )

        print(
            f"ATTENZIONE: {name} contiene "
            f"{duplicated} ID duplicati."
        )


# ============================================================
# SUMMARY
# ============================================================

print("=" * 70)
print("DATA POOLS")
print("=" * 70)

print(
    "Train samples:",
    f"{len(train_metadata):,}"
)

print(
    "Validation pool:",
    f"{len(val_pair_pool):,}"
)

print(
    "Test pool:",
    f"{len(test_pair_pool):,}"
)

print()

print(
    "Train classes:",
    train_metadata[
        "class_id"
    ].nunique()
)

print(
    "Validation classes:",
    val_pair_pool[
        "class_id"
    ].nunique()
)

print(
    "Test classes:",
    test_pair_pool[
        "class_id"
    ].nunique()
)

print()

print("=" * 70)
print("TRAIN CLASS DISTRIBUTION")
print("=" * 70)

display(
    train_metadata[
        "class_id"
    ]
    .value_counts()
    .sort_index()
    .rename("n_samples")
    .to_frame()
)

======================================================================
DATA POOLS
======================================================================
Train samples: 126,265
Validation pool: 12,937
Test pool: 11,070

Train classes: 18
Validation classes: 18
Test classes: 18

======================================================================
TRAIN CLASS DISTRIBUTION
======================================================================

          n_samples
class_id
0             10000
1             10000
2             10000
3             10000
4             10000
5             10000
6             10000
7             10000
8             10000
9              6987
10             6896
11             5052
12             4880
13             4124
14             2601
15             2111
16             1859
17             1755

In [7]:
# ============================================================
# CELL 7 — LOAD FCGR MEMMAP + INDEX
# Same mapping used in previous Siamese notebooks
# ============================================================

fcgr_memmap = np.load(
    FCGR_MEMMAP_PATH,
    mmap_mode="r"
)


fcgr_index = pd.read_csv(
    FCGR_INDEX_PATH,
    sep="\t",
    dtype={
        "id": str
    }
)


# ============================================================
# EXPECTED FCGR INDEX FORMAT
# ============================================================

required_fcgr_columns = {
    "id",
    "fcgr_row",
}


missing_fcgr_columns = (
    required_fcgr_columns
    -
    set(fcgr_index.columns)
)


if missing_fcgr_columns:

    raise KeyError(
        "Il FCGR index non ha la struttura "
        "usata nei notebook precedenti.\n"
        f"Colonne mancanti: "
        f"{sorted(missing_fcgr_columns)}\n"
        f"Colonne presenti: "
        f"{fcgr_index.columns.tolist()}"
    )


# ============================================================
# NORMALIZE
# ============================================================

fcgr_index["id"] = (
    fcgr_index["id"]
    .astype(str)
)


fcgr_index["fcgr_row"] = (
    fcgr_index["fcgr_row"]
    .astype(np.int64)
)


# ============================================================
# ID -> MEMMAP ROW
# ============================================================

id_to_fcgr_row = dict(
    zip(
        fcgr_index["id"],
        fcgr_index["fcgr_row"],
    )
)


# ============================================================
# CHECKS
# ============================================================

if fcgr_index["id"].duplicated().any():

    raise RuntimeError(
        "Sono presenti ID duplicati "
        "nel FCGR index."
    )


if fcgr_index["fcgr_row"].duplicated().any():

    raise RuntimeError(
        "Sono presenti fcgr_row duplicate "
        "nel FCGR index."
    )


if (
    fcgr_index["fcgr_row"].min() < 0
    or
    fcgr_index["fcgr_row"].max()
    >= fcgr_memmap.shape[0]
):

    raise RuntimeError(
        "fcgr_row contiene indici "
        "fuori dai limiti del memmap."
    )


# ============================================================
# CHECK ALL DATASET IDS
# ============================================================

all_required_ids = set(
    pd.concat(
        [
            train_metadata["id"],
            val_pair_pool["id"],
            test_pair_pool["id"],
        ],
        ignore_index=True,
    ).astype(str)
)


missing_ids = (
    all_required_ids
    -
    set(id_to_fcgr_row.keys())
)


if missing_ids:

    raise RuntimeError(
        f"{len(missing_ids)} sample non sono "
        "presenti nella cache FCGR.\n"
        f"Primi ID mancanti: "
        f"{list(missing_ids)[:10]}"
    )


# ============================================================
# BASELINE-COMPATIBILITY CHECKS
# ============================================================

assert (
    fcgr_memmap.dtype
    ==
    np.float32
)


assert (
    len(id_to_fcgr_row)
    ==
    fcgr_memmap.shape[0]
)


# ============================================================
# SUMMARY
# ============================================================

print("=" * 70)
print("FCGR CACHE")
print("=" * 70)

print(
    "FCGR shape:",
    fcgr_memmap.shape
)

print(
    "FCGR dtype:",
    fcgr_memmap.dtype
)

print(
    "Index rows:",
    len(fcgr_index)
)

print(
    "Mapped IDs:",
    len(id_to_fcgr_row)
)

print()

print(
    "fcgr_row min:",
    fcgr_index["fcgr_row"].min()
)

print(
    "fcgr_row max:",
    fcgr_index["fcgr_row"].max()
)

print()

print(
    "All train/val/test IDs found:",
    "YES"
)

======================================================================
FCGR CACHE
======================================================================
FCGR shape: (150272, 64, 64)
FCGR dtype: float32
Index rows: 150272
Mapped IDs: 150272

fcgr_row min: 0
fcgr_row max: 150271

All train/val/test IDs found: YES

In [8]:
# ============================================================
# CELL 8 — SIAMESE PAIR DATASET
# ============================================================

class SiamesePairDataset(Dataset):

    def __init__(
        self,
        metadata,
        fcgr_memmap,
        id_to_fcgr_row,
        pairs_per_epoch,
        positive_probability=0.5,
        seed=42,
        deterministic=False,
    ):

        self.metadata = (
            metadata
            .copy()
            .reset_index(drop=True)
        )

        self.fcgr_memmap = fcgr_memmap

        self.id_to_fcgr_row = (
            id_to_fcgr_row
        )

        self.pairs_per_epoch = int(
            pairs_per_epoch
        )

        self.positive_probability = float(
            positive_probability
        )

        self.seed = int(seed)

        self.deterministic = bool(
            deterministic
        )


        # ----------------------------------------------------
        # Normalize
        # ----------------------------------------------------

        self.metadata["id"] = (
            self.metadata["id"]
            .astype(str)
        )

        self.metadata["class_id"] = (
            self.metadata["class_id"]
            .astype(int)
        )


        # ----------------------------------------------------
        # CLASS -> FCGR ROWS
        #
        # Precomputed once, rather than using pandas
        # inside __getitem__.
        # ----------------------------------------------------

        self.class_to_rows = {}

        for class_id, group in (
            self.metadata.groupby(
                "class_id",
                sort=False,
            )
        ):

            rows = np.array(
                [
                    self.id_to_fcgr_row[
                        sample_id
                    ]

                    for sample_id
                    in group["id"]
                ],
                dtype=np.int64,
            )

            self.class_to_rows[
                int(class_id)
            ] = rows


        self.classes = np.array(
            list(
                self.class_to_rows.keys()
            ),
            dtype=np.int64,
        )


        # Classi utilizzabili per positive pair:
        # servono almeno 2 sample.

        self.positive_classes = np.array(
            [
                class_id

                for class_id, rows
                in self.class_to_rows.items()

                if len(rows) >= 2
            ],
            dtype=np.int64,
        )


        if len(self.classes) < 2:

            raise RuntimeError(
                "Servono almeno 2 classi "
                "per generare negative pairs."
            )


        if len(self.positive_classes) == 0:

            raise RuntimeError(
                "Nessuna classe contiene almeno "
                "2 sample per positive pairs."
            )


        # Worker-local RNG.
        self._rng = None
        self._rng_seed = None


    def __len__(self):

        return self.pairs_per_epoch


    # ========================================================
    # RNG
    # ========================================================

    def _get_rng(
        self,
        index,
    ):

        # ----------------------------------------------------
        # Validation / test:
        # same index => same pair.
        # ----------------------------------------------------

        if self.deterministic:

            return np.random.default_rng(
                self.seed + int(index)
            )


        # ----------------------------------------------------
        # Training:
        # worker-specific random generator.
        # ----------------------------------------------------

        worker_info = get_worker_info()


        if worker_info is None:

            worker_seed = self.seed

        else:

            worker_seed = int(
                worker_info.seed
            )


        if (
            self._rng is None
            or
            self._rng_seed != worker_seed
        ):

            self._rng = (
                np.random.default_rng(
                    worker_seed
                )
            )

            self._rng_seed = (
                worker_seed
            )


        return self._rng


    # ========================================================
    # FCGR
    # ========================================================

    def _load_fcgr(
        self,
        row,
    ):

        # copy=True:
        # evita warning PyTorch su array memmap read-only.

        fcgr = np.array(
            self.fcgr_memmap[
                int(row)
            ],
            dtype=np.float32,
            copy=True,
        )


        # Cache possibilities:
        #
        # (64, 64)
        # oppure
        # (1, 64, 64)

        if fcgr.ndim == 2:

            fcgr = fcgr[
                None,
                :,
                :
            ]


        elif (
            fcgr.ndim == 3
            and
            fcgr.shape[0] == 1
        ):

            pass


        else:

            raise RuntimeError(
                "Shape FCGR non supportata: "
                f"{fcgr.shape}"
            )


        return torch.from_numpy(
            fcgr
        )


    # ========================================================
    # GETITEM
    # ========================================================

    def __getitem__(
        self,
        index,
    ):

        rng = self._get_rng(
            index
        )


        # ----------------------------------------------------
        # Decide positive / negative
        # ----------------------------------------------------

        positive_pair = (
            rng.random()
            <
            self.positive_probability
        )


        # ====================================================
        # POSITIVE PAIR
        # ====================================================

        if positive_pair:

            class_id = int(
                rng.choice(
                    self.positive_classes
                )
            )


            rows = (
                self.class_to_rows[
                    class_id
                ]
            )


            row1, row2 = rng.choice(
                rows,
                size=2,
                replace=False,
            )


            target = 1.0


        # ====================================================
        # NEGATIVE PAIR
        # ====================================================

        else:

            class1, class2 = rng.choice(
                self.classes,
                size=2,
                replace=False,
            )


            row1 = rng.choice(
                self.class_to_rows[
                    int(class1)
                ]
            )


            row2 = rng.choice(
                self.class_to_rows[
                    int(class2)
                ]
            )


            target = 0.0


        # ====================================================
        # FCGR
        # ====================================================

        x1 = self._load_fcgr(
            row1
        )

        x2 = self._load_fcgr(
            row2
        )


        # Stack once:
        #
        # [2, 1, 64, 64]

        pair = torch.stack(
            [
                x1,
                x2,
            ],
            dim=0,
        )


        return (
            pair,
            torch.tensor(
                target,
                dtype=torch.float32,
            ),
        )

In [9]:
# ============================================================
# CELL 9 — CREATE DATASETS
# ============================================================

train_dataset = SiamesePairDataset(

    metadata=train_metadata,

    fcgr_memmap=fcgr_memmap,

    id_to_fcgr_row=id_to_fcgr_row,

    pairs_per_epoch=(
        TRAIN_PAIRS_PER_EPOCH
    ),

    positive_probability=(
        POSITIVE_PAIR_PROBABILITY
    ),

    seed=RANDOM_STATE,

    deterministic=False,
)


val_dataset = SiamesePairDataset(

    metadata=val_pair_pool,

    fcgr_memmap=fcgr_memmap,

    id_to_fcgr_row=id_to_fcgr_row,

    pairs_per_epoch=(
        VAL_PAIRS
    ),

    positive_probability=(
        POSITIVE_PAIR_PROBABILITY
    ),

    seed=(
        RANDOM_STATE + 10_000
    ),

    deterministic=True,
)


test_dataset = SiamesePairDataset(

    metadata=test_pair_pool,

    fcgr_memmap=fcgr_memmap,

    id_to_fcgr_row=id_to_fcgr_row,

    pairs_per_epoch=(
        TEST_PAIRS
    ),

    positive_probability=(
        POSITIVE_PAIR_PROBABILITY
    ),

    seed=(
        RANDOM_STATE + 20_000
    ),

    deterministic=True,
)


print("=" * 70)
print("DATASETS")
print("=" * 70)

print(
    "Train pairs / epoch:",
    f"{len(train_dataset):,}",
)

print(
    "Validation pairs:",
    f"{len(val_dataset):,}",
)

print(
    "Test pairs:",
    f"{len(test_dataset):,}",
)

======================================================================
DATASETS
======================================================================
Train pairs / epoch: 50,000
Validation pairs: 10,000
Test pairs: 10,000

In [10]:
# ============================================================
# CELL 10 — DATASET SANITY CHECK
# ============================================================

pair, target = (
    train_dataset[0]
)


print("=" * 70)
print("SINGLE PAIR")
print("=" * 70)

print(
    "Pair shape:",
    pair.shape,
)

print(
    "Pair dtype:",
    pair.dtype,
)

print(
    "Target:",
    target.item(),
)

print()

print(
    "FCGR 1 min/max:",
    float(pair[0].min()),
    float(pair[0].max()),
)

print(
    "FCGR 2 min/max:",
    float(pair[1].min()),
    float(pair[1].max()),
)


assert (
    pair.ndim == 4
)

assert (
    pair.shape[0] == 2
)

assert (
    pair.shape[1] == 1
)

assert (
    pair.dtype
    ==
    torch.float32
)

assert (
    target.item()
    in
    {0.0, 1.0}
)


print()
print("Single pair: OK")


# ============================================================
# CHECK POSITIVE / NEGATIVE RATIO
# ============================================================

N_CHECK = 2000


targets = np.array(
    [
        float(
            train_dataset[i][1]
        )

        for i in range(
            N_CHECK
        )
    ]
)


print()
print("=" * 70)
print("TRAIN PAIR DISTRIBUTION")
print("=" * 70)

print(
    "Checked:",
    f"{N_CHECK:,}",
)

print(
    "Positive:",
    int(targets.sum()),
)

print(
    "Negative:",
    int(
        N_CHECK
        -
        targets.sum()
    ),
)

print(
    "Positive ratio:",
    f"{targets.mean():.4f}",
)

======================================================================
SINGLE PAIR
======================================================================
Pair shape: torch.Size([2, 1, 64, 64])
Pair dtype: torch.float32
Target: 0.0

FCGR 1 min/max: 0.0 0.007792207878082991
FCGR 2 min/max: 0.0 0.006956521887332201

Single pair: OK

======================================================================
TRAIN PAIR DISTRIBUTION
======================================================================
Checked: 2,000
Positive: 1010
Negative: 990
Positive ratio: 0.5050

In [11]:
# ============================================================
# CELL 11 — DETERMINISTIC VAL / TEST CHECK
# ============================================================

val_pair_a, val_target_a = (
    val_dataset[123]
)

val_pair_b, val_target_b = (
    val_dataset[123]
)


same_pair = torch.equal(
    val_pair_a,
    val_pair_b,
)

same_target = torch.equal(
    val_target_a,
    val_target_b,
)


print("=" * 70)
print("DETERMINISTIC VALIDATION CHECK")
print("=" * 70)

print(
    "Same FCGR pair:",
    same_pair,
)

print(
    "Same target:",
    same_target,
)


assert same_pair

assert same_target


print()
print(
    "Validation deterministic sampling: OK"
)

======================================================================
DETERMINISTIC VALIDATION CHECK
======================================================================
Same FCGR pair: True
Same target: True

Validation deterministic sampling: OK

In [12]:
# ============================================================
# CELL 12 — DATALOADER FACTORY
# ============================================================

def create_loader(
    dataset,
    num_workers,
    batch_size=BATCH_SIZE,
):

    kwargs = {

        "dataset":
            dataset,

        "batch_size":
            batch_size,

        # Pair generation is already random for train.
        "shuffle":
            False,

        "num_workers":
            int(num_workers),

        "pin_memory":
            PIN_MEMORY,

        "drop_last":
            False,
    }


    if num_workers > 0:

        kwargs.update(
            {
                "persistent_workers":
                    True,

                "prefetch_factor":
                    2,
            }
        )


    return DataLoader(
        **kwargs
    )

In [13]:
# ============================================================
# CELL 13 — FINAL DATALOADER CONFIGURATION
# ============================================================

# Windows + Jupyter:
# multiprocessing workers can hang when Dataset classes
# are defined directly inside the notebook.
#
# num_workers=0 already provides ~7.7k pairs/s,
# therefore data loading is not currently a bottleneck.

NUM_WORKERS = 0


print("=" * 70)
print("FINAL DATALOADER CONFIGURATION")
print("=" * 70)

print(
    "NUM_WORKERS:",
    NUM_WORKERS
)

print(
    "PIN_MEMORY:",
    PIN_MEMORY
)

print(
    "Reason:",
    "num_workers=0 already reaches ~7.7k pairs/s"
)

print(
    "Multiprocessing:",
    "disabled for notebook stability"
)

======================================================================
FINAL DATALOADER CONFIGURATION
======================================================================
NUM_WORKERS: 0
PIN_MEMORY: True
Reason: num_workers=0 already reaches ~7.7k pairs/s
Multiprocessing: disabled for notebook stability

In [14]:
# ============================================================
# CELL 14 — FINAL DATALOADERS
# ============================================================

train_loader = DataLoader(
    train_dataset,

    batch_size=BATCH_SIZE,

    shuffle=False,

    num_workers=NUM_WORKERS,

    pin_memory=PIN_MEMORY,

    drop_last=False,
)


val_loader = DataLoader(
    val_dataset,

    batch_size=BATCH_SIZE,

    shuffle=False,

    num_workers=NUM_WORKERS,

    pin_memory=PIN_MEMORY,

    drop_last=False,
)


test_loader = DataLoader(
    test_dataset,

    batch_size=BATCH_SIZE,

    shuffle=False,

    num_workers=NUM_WORKERS,

    pin_memory=PIN_MEMORY,

    drop_last=False,
)


print("=" * 70)
print("FINAL DATALOADERS")
print("=" * 70)

print(
    "Train batches:",
    len(train_loader)
)

print(
    "Validation batches:",
    len(val_loader)
)

print(
    "Test batches:",
    len(test_loader)
)

print()

print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Num workers:",
    NUM_WORKERS
)

print(
    "Pin memory:",
    PIN_MEMORY
)

======================================================================
FINAL DATALOADERS
======================================================================
Train batches: 391
Validation batches: 79
Test batches: 79

Batch size: 128
Num workers: 0
Pin memory: True

In [15]:
# ============================================================
# CELL 15 — BATCH SANITY CHECK
# ============================================================

pair_batch, target_batch = next(
    iter(train_loader)
)


print("=" * 70)
print("BATCH SANITY CHECK")
print("=" * 70)

print(
    "Pair batch shape:",
    pair_batch.shape
)

print(
    "Target batch shape:",
    target_batch.shape
)

print()

print(
    "Pair dtype:",
    pair_batch.dtype
)

print(
    "Target dtype:",
    target_batch.dtype
)

print()

print(
    "Positive pairs:",
    int(target_batch.sum())
)

print(
    "Negative pairs:",
    int(
        len(target_batch)
        -
        target_batch.sum()
    )
)


assert pair_batch.ndim == 5

assert pair_batch.shape[1] == 2

assert pair_batch.shape[2] == 1

assert pair_batch.shape[-2:] == (
    64,
    64,
)

assert target_batch.ndim == 1


print()
print("Batch format: OK")

======================================================================
BATCH SANITY CHECK
======================================================================
Pair batch shape: torch.Size([128, 2, 1, 64, 64])
Target batch shape: torch.Size([128])

Pair dtype: torch.float32
Target dtype: torch.float32

Positive pairs: 63
Negative pairs: 65

Batch format: OK

In [16]:
# ============================================================
# CELL 16 — FCGR CNN ENCODER
# Same architecture as Baseline C
# ============================================================

class FCGRCNNEncoder(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()


        self.features = nn.Sequential(

            # ==================================================
            # 64 x 64
            # ==================================================

            nn.Conv2d(
                in_channels=1,
                out_channels=32,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                num_groups=8,
                num_channels=32,
            ),

            nn.ReLU(
                inplace=True
            ),


            nn.Conv2d(
                in_channels=32,
                out_channels=32,
                kernel_size=3,
                padding=1,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.MaxPool2d(
                kernel_size=2
            ),


            # ==================================================
            # 32 x 32
            # ==================================================

            nn.Conv2d(
                in_channels=32,
                out_channels=64,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                num_groups=8,
                num_channels=64,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.MaxPool2d(
                kernel_size=2
            ),


            # ==================================================
            # 16 x 16
            # ==================================================

            nn.Conv2d(
                in_channels=64,
                out_channels=128,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                num_groups=8,
                num_channels=128,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.MaxPool2d(
                kernel_size=2
            ),


            # ==================================================
            # 8 x 8
            # ==================================================

            nn.Conv2d(
                in_channels=128,
                out_channels=128,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                num_groups=8,
                num_channels=128,
            ),

            nn.ReLU(
                inplace=True
            ),


            # ==================================================
            # 4 x 4
            # ==================================================

            nn.AdaptiveAvgPool2d(
                (4, 4)
            ),
        )


        self.projection = nn.Sequential(

            nn.Flatten(),

            nn.Linear(
                128 * 4 * 4,
                256,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.Linear(
                256,
                embedding_dim,
            ),
        )


    def forward(
        self,
        x,
    ):

        x = self.features(
            x
        )

        z = self.projection(
            x
        )


        # ------------------------------------------------------
        # Fundamental for cosine metric learning
        # ------------------------------------------------------

        z = F.normalize(
            z,
            p=2,
            dim=1,
            eps=1e-8,
        )


        return z

In [17]:
# ============================================================
# CELL 17 — SIAMESE NETWORK
# Optimized concatenated forward
# ============================================================

class SiameseNetwork(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()

        self.encoder = FCGRCNNEncoder(
            embedding_dim=embedding_dim
        )


    def forward(
        self,
        pair_batch,
    ):

        # pair_batch:
        #
        # [B, 2, 1, 64, 64]

        batch_size = (
            pair_batch.shape[0]
        )


        # ------------------------------------------------------
        # Merge Siamese branches
        #
        # [B, 2, 1, 64, 64]
        #
        # ->
        #
        # [2B, 1, 64, 64]
        # ------------------------------------------------------

        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        # Single encoder forward

        z = self.encoder(
            x
        )


        # ------------------------------------------------------
        # Restore pair dimension
        #
        # [2B, D]
        #
        # ->
        #
        # [B, 2, D]
        # ------------------------------------------------------

        z = z.reshape(
            batch_size,
            2,
            -1,
        )


        z1 = z[:, 0, :]

        z2 = z[:, 1, :]


        return z1, z2

In [18]:
# ============================================================
# CELL 18 — COSINE SIMILARITY
# Official PyTorch implementation
# ============================================================

def cosine_similarity(
    z1,
    z2,
):

    return F.cosine_similarity(
        z1,
        z2,
        dim=1,
        eps=1e-8,
    )

In [19]:
# ============================================================
# CELL 19 — COSINE EMBEDDING LOSS
# Official PyTorch implementation
# ============================================================

class CosineMetricLoss(nn.Module):

    def __init__(
        self,
        margin,
    ):

        super().__init__()

        self.margin = float(
            margin
        )


        self.loss_fn = (
            nn.CosineEmbeddingLoss(

                margin=self.margin,

                reduction="mean",
            )
        )


    def forward(
        self,
        z1,
        z2,
        target,
    ):

        # Dataset convention:
        #
        # 1 = positive pair
        # 0 = negative pair
        #
        # CosineEmbeddingLoss convention:
        #
        # +1 = positive
        # -1 = negative

        cosine_target = torch.where(

            target > 0.5,

            torch.ones_like(
                target
            ),

            -torch.ones_like(
                target
            ),
        )


        loss = self.loss_fn(

            z1,

            z2,

            cosine_target,
        )


        similarity = (
            F.cosine_similarity(

                z1,

                z2,

                dim=1,

                eps=1e-8,
            )
        )


        return (
            loss,
            similarity,
        )

In [20]:
# ============================================================
# CELL 20 — INITIAL EMBEDDING DIAGNOSTIC
#
# Goal:
# Check whether the cosine embedding space is already
# collapsed BEFORE any training step.
# ============================================================

set_seed(
    RANDOM_STATE
)


# ============================================================
# FRESH UNTRAINED MODEL
# ============================================================

diagnostic_model = SiameseNetwork(
    embedding_dim=EMBEDDING_DIM
).to(
    DEVICE
)


diagnostic_model.eval()


# ============================================================
# AMP
# Defined locally so this cell does not depend on later cells.
# ============================================================

diagnostic_amp_enabled = (
    USE_AMP
    and
    DEVICE.type == "cuda"
)


# ============================================================
# STORAGE
# ============================================================

all_similarities = []

all_targets = []


MAX_DIAGNOSTIC_BATCHES = 30


# ============================================================
# FORWARD
# ============================================================

with torch.inference_mode():

    for batch_index, (
        pair_batch,
        target_batch,
    ) in enumerate(
        val_loader
    ):

        if (
            batch_index
            >=
            MAX_DIAGNOSTIC_BATCHES
        ):
            break


        # ----------------------------------------------------
        # CPU -> GPU
        # ----------------------------------------------------

        pair_batch = pair_batch.to(
            DEVICE,
            non_blocking=True,
        )


        # ----------------------------------------------------
        # Encoder forward
        # ----------------------------------------------------

        with torch.autocast(
            device_type=DEVICE.type,
            dtype=torch.float16,
            enabled=diagnostic_amp_enabled,
        ):

            z1, z2 = diagnostic_model(
                pair_batch
            )


        # ----------------------------------------------------
        # Compute cosine explicitly in FP32
        # ----------------------------------------------------

        similarity = F.cosine_similarity(
            z1.float(),
            z2.float(),
            dim=1,
            eps=1e-8,
        )


        all_similarities.append(
            similarity.cpu()
        )


        all_targets.append(
            target_batch.cpu()
        )


# ============================================================
# CONCATENATE
# ============================================================

initial_similarities = (
    torch.cat(
        all_similarities
    )
    .numpy()
)


initial_targets = (
    torch.cat(
        all_targets
    )
    .numpy()
    .astype(np.int64)
)


# ============================================================
# POSITIVE / NEGATIVE DISTRIBUTIONS
# ============================================================

positive_initial = (
    initial_similarities[
        initial_targets == 1
    ]
)


negative_initial = (
    initial_similarities[
        initial_targets == 0
    ]
)


if (
    len(positive_initial) == 0
    or
    len(negative_initial) == 0
):

    raise RuntimeError(
        "La diagnostica non contiene entrambe "
        "le classi positive/negative."
    )


# ============================================================
# ROC-AUC BEFORE TRAINING
# ============================================================

initial_auc = roc_auc_score(
    initial_targets,
    initial_similarities,
)


# ============================================================
# OUTPUT
# ============================================================

print("=" * 70)
print("UNTRAINED EMBEDDING DIAGNOSTIC")
print("=" * 70)

print(
    "Samples checked:",
    f"{len(initial_targets):,}"
)

print(
    "Positive pairs:",
    f"{len(positive_initial):,}"
)

print(
    "Negative pairs:",
    f"{len(negative_initial):,}"
)

print()


print(
    "All cosine mean:",
    f"{initial_similarities.mean():.6f}"
)

print(
    "All cosine std:",
    f"{initial_similarities.std():.6f}"
)

print()


print(
    "Positive cosine mean:",
    f"{positive_initial.mean():.6f}"
)

print(
    "Negative cosine mean:",
    f"{negative_initial.mean():.6f}"
)


initial_gap = (
    positive_initial.mean()
    -
    negative_initial.mean()
)


print(
    "Initial cosine gap:",
    f"{initial_gap:.6f}"
)

print()


print(
    "Initial ROC-AUC:",
    f"{initial_auc:.6f}"
)

print()


print(
    "Min:",
    f"{initial_similarities.min():.6f}"
)

print(
    "25%:",
    f"{np.quantile(initial_similarities, 0.25):.6f}"
)

print(
    "Median:",
    f"{np.median(initial_similarities):.6f}"
)

print(
    "75%:",
    f"{np.quantile(initial_similarities, 0.75):.6f}"
)

print(
    "Max:",
    f"{initial_similarities.max():.6f}"
)


# ============================================================
# CLEANUP
# ============================================================

del diagnostic_model

gc.collect()


if DEVICE.type == "cuda":
    torch.cuda.empty_cache()

======================================================================
UNTRAINED EMBEDDING DIAGNOSTIC
======================================================================
Samples checked: 3,840
Positive pairs: 1,985
Negative pairs: 1,855

All cosine mean: 0.999979
All cosine std: 0.000077

Positive cosine mean: 0.999979
Negative cosine mean: 0.999979
Initial cosine gap: -0.000000

Initial ROC-AUC: 0.544810

Min: 0.998193
25%: 0.999986
Median: 0.999993
75%: 0.999997
Max: 1.000000

In [21]:
# ============================================================
# CELL 21 — MODEL SANITY CHECK
# ============================================================

set_seed(
    RANDOM_STATE
)


model = SiameseNetwork(
    embedding_dim=EMBEDDING_DIM
).to(
    DEVICE
)


# ============================================================
# PARAMETER COUNT
# ============================================================

total_parameters = sum(
    parameter.numel()
    for parameter in model.parameters()
)


trainable_parameters = sum(
    parameter.numel()
    for parameter in model.parameters()
    if parameter.requires_grad
)


print("=" * 70)
print("MODEL")
print("=" * 70)

print(model)

print()

print(
    "Total parameters:",
    f"{total_parameters:,}"
)

print(
    "Trainable parameters:",
    f"{trainable_parameters:,}"
)


# ============================================================
# REAL BATCH
# ============================================================

pair_batch, target_batch = next(
    iter(train_loader)
)


pair_batch = pair_batch.to(
    DEVICE,
    non_blocking=True,
)


target_batch = target_batch.to(
    DEVICE,
    non_blocking=True,
)


amp_enabled = (
    USE_AMP
    and
    DEVICE.type == "cuda"
)


with torch.autocast(
    device_type=DEVICE.type,
    dtype=torch.float16,
    enabled=amp_enabled,
):

    z1, z2 = model(
        pair_batch
    )


# Similarity in FP32

similarity = F.cosine_similarity(
    z1.float(),
    z2.float(),
    dim=1,
    eps=1e-8,
)


# ============================================================
# CHECK EMBEDDING NORMS
# ============================================================

z1_norm = (
    z1.float()
    .norm(
        p=2,
        dim=1,
    )
)


z2_norm = (
    z2.float()
    .norm(
        p=2,
        dim=1,
    )
)


print()
print("=" * 70)
print("FORWARD CHECK")
print("=" * 70)

print(
    "z1 shape:",
    z1.shape
)

print(
    "z2 shape:",
    z2.shape
)

print()

print(
    "z1 norm mean:",
    z1_norm.mean().item()
)

print(
    "z2 norm mean:",
    z2_norm.mean().item()
)

print()

print(
    "Similarity min:",
    similarity.min().item()
)

print(
    "Similarity max:",
    similarity.max().item()
)

print(
    "Similarity mean:",
    similarity.mean().item()
)


assert z1.shape == (
    BATCH_SIZE,
    EMBEDDING_DIM,
)

assert z2.shape == (
    BATCH_SIZE,
    EMBEDDING_DIM,
)


assert torch.allclose(
    z1_norm,
    torch.ones_like(z1_norm),
    atol=2e-3,
)


assert torch.allclose(
    z2_norm,
    torch.ones_like(z2_norm),
    atol=2e-3,
)


assert (
    similarity.min()
    >= -1.0001
)

assert (
    similarity.max()
    <= 1.0001
)


print()
print(
    "Model + embeddings + cosine: OK"
)

======================================================================
MODEL
======================================================================
SiameseNetwork(
  (encoder): FCGRCNNEncoder(
    (features): Sequential(
      (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): GroupNorm(8, 32, eps=1e-05, affine=True, bias=True)
      (2): ReLU(inplace=True)
      (3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): GroupNorm(8, 64, eps=1e-05, affine=True, bias=True)
      (8): ReLU(inplace=True)
      (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (10): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): GroupNorm(8, 128, eps=1e-05, affine=True, bias=True)
      (12): ReLU(inplace=True)
      (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (14): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (15): GroupNorm(8, 128, eps=1e-05, affine=True, bias=True)
      (16): ReLU(inplace=True)
      (17): AdaptiveAvgPool2d(output_size=(4, 4))
    )
    (projection): Sequential(
      (0): Flatten(start_dim=1, end_dim=-1)
      (1): Linear(in_features=2048, out_features=256, bias=True)
      (2): ReLU(inplace=True)
      (3): Linear(in_features=256, out_features=128, bias=True)
    )
  )
)

Total parameters: 807,648
Trainable parameters: 807,648

======================================================================
FORWARD CHECK
======================================================================
z1 shape: torch.Size([128, 128])
z2 shape: torch.Size([128, 128])

z1 norm mean: 1.0
z2 norm mean: 1.0

Similarity min: 0.9998984932899475
Similarity max: 0.9999994039535522
Similarity mean: 0.9999876022338867

Model + embeddings + cosine: OK

In [22]:
# ============================================================
# CELL 22 — EXPERIMENT DATALOADER FACTORY
# ============================================================

def build_experiment_loaders():

    # IMPORTANT:
    # recreate datasets from scratch so that every experiment
    # starts from the same RNG state and therefore sees the
    # same dynamic training-pair sequence.

    train_ds = SiamesePairDataset(

        metadata=train_metadata,

        fcgr_memmap=fcgr_memmap,

        id_to_fcgr_row=id_to_fcgr_row,

        pairs_per_epoch=TRAIN_PAIRS_PER_EPOCH,

        positive_probability=POSITIVE_PAIR_PROBABILITY,

        seed=RANDOM_STATE,

        deterministic=False,
    )


    val_ds = SiamesePairDataset(

        metadata=val_pair_pool,

        fcgr_memmap=fcgr_memmap,

        id_to_fcgr_row=id_to_fcgr_row,

        pairs_per_epoch=VAL_PAIRS,

        positive_probability=POSITIVE_PAIR_PROBABILITY,

        seed=RANDOM_STATE + 10_000,

        deterministic=True,
    )


    test_ds = SiamesePairDataset(

        metadata=test_pair_pool,

        fcgr_memmap=fcgr_memmap,

        id_to_fcgr_row=id_to_fcgr_row,

        pairs_per_epoch=TEST_PAIRS,

        positive_probability=POSITIVE_PAIR_PROBABILITY,

        seed=RANDOM_STATE + 20_000,

        deterministic=True,
    )


    train_dl = DataLoader(

        train_ds,

        batch_size=BATCH_SIZE,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=PIN_MEMORY,

        drop_last=False,
    )


    val_dl = DataLoader(

        val_ds,

        batch_size=BATCH_SIZE,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=PIN_MEMORY,

        drop_last=False,
    )


    test_dl = DataLoader(

        test_ds,

        batch_size=BATCH_SIZE,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=PIN_MEMORY,

        drop_last=False,
    )


    return (
        train_dl,
        val_dl,
        test_dl,
    )


print(
    "Experiment DataLoader factory: OK"
)

Experiment DataLoader factory: OK

In [23]:
# ============================================================
# CELL 23 — TRAINING COMPONENT FACTORY
# ============================================================

AMP_ENABLED = (
    USE_AMP
    and
    DEVICE.type == "cuda"
)


def build_training_components(
    margin,
):

    # --------------------------------------------------------
    # Same initialization for every experiment
    # --------------------------------------------------------

    set_seed(
        RANDOM_STATE
    )


    # --------------------------------------------------------
    # Model
    # --------------------------------------------------------

    model = SiameseNetwork(
        embedding_dim=EMBEDDING_DIM
    ).to(
        DEVICE
    )


    # --------------------------------------------------------
    # AdamW
    # --------------------------------------------------------

    fused_adamw = False


    try:

        optimizer = torch.optim.AdamW(

            model.parameters(),

            lr=LEARNING_RATE,

            weight_decay=WEIGHT_DECAY,

            fused=(
                DEVICE.type == "cuda"
            ),
        )

        fused_adamw = (
            DEVICE.type == "cuda"
        )


    except (
        TypeError,
        RuntimeError,
    ):

        optimizer = torch.optim.AdamW(

            model.parameters(),

            lr=LEARNING_RATE,

            weight_decay=WEIGHT_DECAY,
        )


    # --------------------------------------------------------
    # AMP scaler
    # --------------------------------------------------------

    if hasattr(
        torch,
        "amp"
    ):

        scaler = torch.amp.GradScaler(
            "cuda",
            enabled=AMP_ENABLED,
        )

    else:

        scaler = torch.cuda.amp.GradScaler(
            enabled=AMP_ENABLED
        )


    # --------------------------------------------------------
    # Official CosineEmbeddingLoss wrapper
    # --------------------------------------------------------

    criterion = CosineMetricLoss(
        margin=margin
    )


    return (
        model,
        optimizer,
        scaler,
        criterion,
        fused_adamw,
    )


print("=" * 70)
print("TRAINING CONFIGURATION")
print("=" * 70)

print(
    "AMP:",
    AMP_ENABLED
)

print(
    "LR:",
    LEARNING_RATE
)

print(
    "Weight decay:",
    WEIGHT_DECAY
)

print(
    "Loss:",
    "CosineMetricLoss / nn.CosineEmbeddingLoss"
)

======================================================================
TRAINING CONFIGURATION
======================================================================
AMP: True
LR: 0.0005
Weight decay: 0.0001
Loss: CosineMetricLoss / nn.CosineEmbeddingLoss

In [24]:
# ============================================================
# CELL 24 — METRICS
# ============================================================

def safe_dprime(
    mean_a,
    std_a,
    mean_b,
    std_b,
):

    pooled_std = np.sqrt(
        (
            std_a ** 2
            +
            std_b ** 2
        )
        / 2.0
    )


    if pooled_std < 1e-12:
        return 0.0


    return (
        mean_a
        -
        mean_b
    ) / pooled_std


def compute_distribution_metrics(
    targets,
    similarities,
):

    targets = np.asarray(
        targets,
        dtype=np.int64,
    )

    similarities = np.asarray(
        similarities,
        dtype=np.float64,
    )


    positive_mask = (
        targets == 1
    )

    negative_mask = (
        targets == 0
    )


    cos_pos = similarities[
        positive_mask
    ]

    cos_neg = similarities[
        negative_mask
    ]


    # --------------------------------------------------------
    # Cosine statistics
    # --------------------------------------------------------

    cos_pos_mean = float(
        cos_pos.mean()
    )

    cos_neg_mean = float(
        cos_neg.mean()
    )


    cos_pos_std = float(
        cos_pos.std()
    )

    cos_neg_std = float(
        cos_neg.std()
    )


    cosine_gap = (
        cos_pos_mean
        -
        cos_neg_mean
    )


    cosine_dprime = safe_dprime(

        cos_pos_mean,
        cos_pos_std,

        cos_neg_mean,
        cos_neg_std,
    )


    # --------------------------------------------------------
    # Convert cosine -> Euclidean distance
    #
    # for unit embeddings:
    #
    # d² = 2 - 2 cos
    # --------------------------------------------------------

    distances = np.sqrt(
        np.clip(
            2.0
            -
            2.0 * similarities,
            a_min=0.0,
            a_max=None,
        )
    )


    dist_pos = distances[
        positive_mask
    ]

    dist_neg = distances[
        negative_mask
    ]


    d_pos = float(
        dist_pos.mean()
    )

    d_neg = float(
        dist_neg.mean()
    )


    d_pos_std = float(
        dist_pos.std()
    )

    d_neg_std = float(
        dist_neg.std()
    )


    distance_gap = (
        d_neg
        -
        d_pos
    )


    distance_dprime = safe_dprime(

        d_neg,
        d_neg_std,

        d_pos,
        d_pos_std,
    )


    return {

        "cos_pos":
            cos_pos_mean,

        "cos_neg":
            cos_neg_mean,

        "cos_gap":
            cosine_gap,

        "cos_dprime":
            cosine_dprime,

        "d_pos":
            d_pos,

        "d_neg":
            d_neg,

        "distance_gap":
            distance_gap,

        "distance_dprime":
            distance_dprime,
    }

In [25]:
# ============================================================
# CELL 25 — VALIDATION THRESHOLD SEARCH
# ============================================================

def find_best_threshold(
    targets,
    similarities,
):

    targets = np.asarray(
        targets,
        dtype=np.int64,
    )

    similarities = np.asarray(
        similarities,
        dtype=np.float64,
    )


    # Higher cosine => positive pair.

    order = np.argsort(
        -similarities
    )


    y = targets[
        order
    ]

    scores = similarities[
        order
    ]


    positive = (
        y == 1
    ).astype(np.int64)

    negative = (
        y == 0
    ).astype(np.int64)


    tp = np.cumsum(
        positive
    )

    fp = np.cumsum(
        negative
    )


    total_positive = int(
        positive.sum()
    )

    total_negative = int(
        negative.sum()
    )


    fn = (
        total_positive
        -
        tp
    )

    tn = (
        total_negative
        -
        fp
    )


    # F1 for class 1

    f1_positive = (
        2.0 * tp
        /
        np.maximum(
            2.0 * tp
            +
            fp
            +
            fn,
            1,
        )
    )


    # F1 for class 0

    f1_negative = (
        2.0 * tn
        /
        np.maximum(
            2.0 * tn
            +
            fp
            +
            fn,
            1,
        )
    )


    macro_f1 = (
        f1_positive
        +
        f1_negative
    ) / 2.0


    # Only evaluate valid score boundaries.

    boundary_mask = np.r_[

        scores[:-1]
        !=
        scores[1:],

        True,
    ]


    valid_indices = np.where(
        boundary_mask
    )[0]


    best_relative_index = np.argmax(
        macro_f1[
            valid_indices
        ]
    )


    best_index = int(
        valid_indices[
            best_relative_index
        ]
    )


    best_threshold = float(
        scores[
            best_index
        ]
    )


    return best_threshold

In [26]:
# ============================================================
# CELL 26 — CLASSIFICATION METRICS
# ============================================================

def compute_classification_metrics(
    targets,
    similarities,
    threshold,
):

    targets = np.asarray(
        targets,
        dtype=np.int64,
    )

    similarities = np.asarray(
        similarities,
        dtype=np.float64,
    )


    predictions = (
        similarities
        >=
        threshold
    ).astype(
        np.int64
    )


    return {

        "roc_auc":
            float(
                roc_auc_score(
                    targets,
                    similarities,
                )
            ),

        "accuracy":
            float(
                accuracy_score(
                    targets,
                    predictions,
                )
            ),

        "macro_f1":
            float(
                f1_score(
                    targets,
                    predictions,
                    average="macro",
                )
            ),

        "balanced_accuracy":
            float(
                balanced_accuracy_score(
                    targets,
                    predictions,
                )
            ),

        "precision":
            float(
                precision_score(
                    targets,
                    predictions,
                    zero_division=0,
                )
            ),

        "recall":
            float(
                recall_score(
                    targets,
                    predictions,
                    zero_division=0,
                )
            ),

        "confusion_matrix":
            confusion_matrix(
                targets,
                predictions,
            ),
    }

In [27]:
# ============================================================
# CELL 27 — OPTIMIZED EPOCH LOOP
# ============================================================

def run_epoch(
    model,
    loader,
    criterion,
    optimizer=None,
    scaler=None,
    collect_outputs=False,
):

    training = (
        optimizer is not None
    )


    if training:
        model.train()
    else:
        model.eval()


    # --------------------------------------------------------
    # GPU-side accumulators
    # --------------------------------------------------------

    loss_sum = torch.zeros(
        (),
        device=DEVICE,
        dtype=torch.float32,
    )


    positive_similarity_sum = torch.zeros(
        (),
        device=DEVICE,
        dtype=torch.float32,
    )


    negative_similarity_sum = torch.zeros(
        (),
        device=DEVICE,
        dtype=torch.float32,
    )


    positive_count = torch.zeros(
        (),
        device=DEVICE,
        dtype=torch.float32,
    )


    negative_count = torch.zeros(
        (),
        device=DEVICE,
        dtype=torch.float32,
    )


    n_samples = 0


    all_targets = []

    all_similarities = []


    # Accurate epoch timing.

    if DEVICE.type == "cuda":
        torch.cuda.synchronize()


    start_time = time.perf_counter()


    context = (
        torch.enable_grad()
        if training
        else torch.inference_mode()
    )


    with context:

        for (
            pair_batch,
            target_batch,
        ) in loader:


            # ------------------------------------------------
            # CPU -> GPU
            # ------------------------------------------------

            pair_batch = pair_batch.to(

                DEVICE,

                non_blocking=True,
            )


            target_batch = target_batch.to(

                DEVICE,

                non_blocking=True,
            )


            batch_size = (
                target_batch.shape[0]
            )


            # ------------------------------------------------
            # TRAIN
            # ------------------------------------------------

            if training:

                optimizer.zero_grad(
                    set_to_none=True
                )


            # ------------------------------------------------
            # FORWARD
            # ------------------------------------------------

            with torch.autocast(

                device_type="cuda",

                dtype=torch.float16,

                enabled=AMP_ENABLED,
            ):

                z1, z2 = model(
                    pair_batch
                )


                loss, similarity = criterion(

                    z1,
                    z2,
                    target_batch,
                )


            # ------------------------------------------------
            # BACKWARD
            # ------------------------------------------------

            if training:

                scaler.scale(
                    loss
                ).backward()


                scaler.step(
                    optimizer
                )


                scaler.update()


            # ------------------------------------------------
            # GPU STATISTICS
            # ------------------------------------------------

            similarity_detached = (
                similarity.detach()
            )


            target_detached = (
                target_batch.detach()
            )


            positive_mask = (
                target_detached
                >
                0.5
            )


            negative_mask = (
                ~positive_mask
            )


            loss_sum += (
                loss.detach()
                *
                batch_size
            )


            positive_similarity_sum += (
                similarity_detached[
                    positive_mask
                ]
                .sum()
            )


            negative_similarity_sum += (
                similarity_detached[
                    negative_mask
                ]
                .sum()
            )


            positive_count += (
                positive_mask
                .sum()
            )


            negative_count += (
                negative_mask
                .sum()
            )


            n_samples += (
                batch_size
            )


            # ------------------------------------------------
            # Only validation/test need full outputs.
            # ------------------------------------------------

            if collect_outputs:

                all_targets.append(

                    target_detached
                    .cpu()
                )


                all_similarities.append(

                    similarity_detached
                    .cpu()
                )


    # --------------------------------------------------------
    # Timing
    # --------------------------------------------------------

    if DEVICE.type == "cuda":
        torch.cuda.synchronize()


    elapsed = (
        time.perf_counter()
        -
        start_time
    )


    # --------------------------------------------------------
    # Single GPU -> CPU synchronization
    # --------------------------------------------------------

    epoch_loss = float(
        (
            loss_sum
            /
            max(
                n_samples,
                1,
            )
        ).item()
    )


    mean_positive_similarity = float(

        (
            positive_similarity_sum
            /
            positive_count.clamp_min(
                1
            )
        ).item()
    )


    mean_negative_similarity = float(

        (
            negative_similarity_sum
            /
            negative_count.clamp_min(
                1
            )
        ).item()
    )


    stats = {

        "loss":
            epoch_loss,

        "cos_pos":
            mean_positive_similarity,

        "cos_neg":
            mean_negative_similarity,

        "cos_gap":
            (
                mean_positive_similarity
                -
                mean_negative_similarity
            ),

        "seconds":
            elapsed,

        "pairs_per_second":
            (
                n_samples
                /
                max(
                    elapsed,
                    1e-9,
                )
            ),
    }


    # --------------------------------------------------------
    # Validation / test arrays
    # --------------------------------------------------------

    if collect_outputs:

        targets_np = (
            torch.cat(
                all_targets
            )
            .numpy()
        )


        similarities_np = (
            torch.cat(
                all_similarities
            )
            .numpy()
        )


        return (
            stats,
            targets_np,
            similarities_np,
        )


    return stats

In [28]:
# ============================================================
# CELL 28 — TRAIN ONE COSINE EXPERIMENT
# ============================================================

def train_cosine_experiment(
    margin,
    experiment_name,
    max_epochs=MAX_EPOCHS,
):

    print("=" * 80)
    print(
        f"EXPERIMENT: {experiment_name}"
    )
    print("=" * 80)

    print(
        "Cosine margin:",
        margin
    )

    print()


    # ========================================================
    # Clean previous GPU memory
    # ========================================================

    gc.collect()


    if DEVICE.type == "cuda":

        torch.cuda.empty_cache()


    # ========================================================
    # Fresh DataLoaders
    # ========================================================

    (
        train_dl,
        val_dl,
        test_dl,
    ) = build_experiment_loaders()


    # ========================================================
    # Fresh model / optimizer
    # ========================================================

    (
        model,
        optimizer,
        scaler,
        criterion,
        fused_adamw,
    ) = build_training_components(
        margin
    )


    print(
        "Fused AdamW:",
        fused_adamw
    )

    print(
        "AMP:",
        AMP_ENABLED
    )

    print()


    # ========================================================
    # Experiment directory
    # ========================================================

    experiment_dir = (
        ARTIFACTS_DIR
        /
        experiment_name
    )


    experiment_dir.mkdir(
        parents=True,
        exist_ok=True,
    )


    checkpoint_path = (
        experiment_dir
        /
        "best_model.pt"
    )


    # ========================================================
    # Training state
    # ========================================================

    best_val_auc = -np.inf

    best_epoch = 0

    epochs_without_improvement = 0

    history = []


    # ========================================================
    # Epoch loop
    # ========================================================

    for epoch in range(
        1,
        max_epochs + 1,
    ):


        # ----------------------------------------------------
        # TRAIN
        # ----------------------------------------------------

        train_stats = run_epoch(

            model=model,

            loader=train_dl,

            criterion=criterion,

            optimizer=optimizer,

            scaler=scaler,

            collect_outputs=False,
        )


        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        (
            val_stats,
            val_targets,
            val_similarities,
        ) = run_epoch(

            model=model,

            loader=val_dl,

            criterion=criterion,

            optimizer=None,

            scaler=None,

            collect_outputs=True,
        )


        val_auc = float(

            roc_auc_score(

                val_targets,

                val_similarities,
            )
        )


        val_distribution = (
            compute_distribution_metrics(

                val_targets,

                val_similarities,
            )
        )


        # ----------------------------------------------------
        # Save history
        # ----------------------------------------------------

        epoch_result = {

            "epoch":
                epoch,

            "train_loss":
                train_stats["loss"],

            "val_loss":
                val_stats["loss"],

            "val_auc":
                val_auc,

            "train_cos_pos":
                train_stats["cos_pos"],

            "train_cos_neg":
                train_stats["cos_neg"],

            "train_cos_gap":
                train_stats["cos_gap"],

            "val_cos_pos":
                val_distribution["cos_pos"],

            "val_cos_neg":
                val_distribution["cos_neg"],

            "val_cos_gap":
                val_distribution["cos_gap"],

            "val_cos_dprime":
                val_distribution["cos_dprime"],

            "val_d_pos":
                val_distribution["d_pos"],

            "val_d_neg":
                val_distribution["d_neg"],

            "val_distance_gap":
                val_distribution[
                    "distance_gap"
                ],

            "val_distance_dprime":
                val_distribution[
                    "distance_dprime"
                ],

            "train_seconds":
                train_stats["seconds"],

            "val_seconds":
                val_stats["seconds"],

            "train_pairs_per_second":
                train_stats[
                    "pairs_per_second"
                ],
        }


        history.append(
            epoch_result
        )


        # ----------------------------------------------------
        # Checkpoint: validation ROC-AUC
        # ----------------------------------------------------

        improved = (

            val_auc
            >
            best_val_auc
            +
            MIN_DELTA
        )


        if improved:

            best_val_auc = (
                val_auc
            )

            best_epoch = (
                epoch
            )

            epochs_without_improvement = 0


            torch.save(

                {
                    "epoch":
                        epoch,

                    "margin":
                        margin,

                    "val_auc":
                        val_auc,

                    "model_state_dict":
                        model.state_dict(),

                    "optimizer_state_dict":
                        optimizer.state_dict(),
                },

                checkpoint_path,
            )


        else:

            epochs_without_improvement += 1


        # ----------------------------------------------------
        # Progress
        # ----------------------------------------------------

        marker = (
            "  *BEST*"
            if improved
            else ""
        )


        print(

            f"Epoch {epoch:02d}/{max_epochs} | "

            f"train loss "
            f"{train_stats['loss']:.5f} | "

            f"val loss "
            f"{val_stats['loss']:.5f} | "

            f"val AUC "
            f"{val_auc:.5f} | "

            f"cos+ "
            f"{val_distribution['cos_pos']:.4f} | "

            f"cos- "
            f"{val_distribution['cos_neg']:.4f} | "

            f"gap "
            f"{val_distribution['cos_gap']:.4f} | "

            f"d' "
            f"{val_distribution['cos_dprime']:.3f} | "

            f"{train_stats['seconds']:.1f}s"

            f"{marker}"
        )


        # ----------------------------------------------------
        # Early stopping
        # ----------------------------------------------------

        if (
            epochs_without_improvement
            >=
            EARLY_STOPPING_PATIENCE
        ):

            print()
            print(
                "Early stopping."
            )

            break


    # ========================================================
    # Save history
    # ========================================================

    history_df = pd.DataFrame(
        history
    )


    history_df.to_csv(

        experiment_dir
        /
        "history.tsv",

        sep="\t",

        index=False,
    )


    print()
    print("=" * 80)

    print(
        "Best epoch:",
        best_epoch
    )

    print(
        "Best Val ROC-AUC:",
        f"{best_val_auc:.5f}"
    )

    print(
        "Checkpoint:",
        checkpoint_path
    )

    print("=" * 80)


    return {

        "model":
            model,

        "criterion":
            criterion,

        "train_loader":
            train_dl,

        "val_loader":
            val_dl,

        "test_loader":
            test_dl,

        "history":
            history_df,

        "checkpoint_path":
            checkpoint_path,

        "best_epoch":
            best_epoch,

        "best_val_auc":
            best_val_auc,

        "experiment_dir":
            experiment_dir,
    }

In [29]:
'''# ============================================================
# CELL 29 — REFERENCE COSINE RUN
# ============================================================

REFERENCE_EXPERIMENT_NAME = (
    "cosine_margin_0p21875"
)


reference_run = train_cosine_experiment(

    margin=REFERENCE_COSINE_MARGIN,

    experiment_name=(
        REFERENCE_EXPERIMENT_NAME
    ),

    max_epochs=MAX_EPOCHS,
)'''

'# ============================================================\n# CELL 29 — REFERENCE COSINE RUN\n# ============================================================\n\nREFERENCE_EXPERIMENT_NAME = (\n    "cosine_margin_0p21875"\n)\n\n\nreference_run = train_cosine_experiment(\n\n    margin=REFERENCE_COSINE_MARGIN,\n\n    experiment_name=(\n        REFERENCE_EXPERIMENT_NAME\n    ),\n\n    max_epochs=MAX_EPOCHS,\n)'

In [30]:
# ============================================================
# CELL 30 — COSINE ENCODER V1
#
# Minimal anti-collapse modification:
# final projection has NO bias.
#
# Everything else remains identical to Baseline C.
# ============================================================

class FCGRCNNEncoderCosineV1(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()


        self.features = nn.Sequential(

            nn.Conv2d(
                1,
                32,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                32,
            ),

            nn.ReLU(
                inplace=True
            ),


            nn.Conv2d(
                32,
                32,
                kernel_size=3,
                padding=1,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.MaxPool2d(2),


            nn.Conv2d(
                32,
                64,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                64,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.MaxPool2d(2),


            nn.Conv2d(
                64,
                128,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                128,
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.MaxPool2d(2),


            nn.Conv2d(
                128,
                128,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                128,
            ),

            nn.ReLU(
                inplace=True
            ),


            nn.AdaptiveAvgPool2d(
                (4, 4)
            ),
        )


        self.projection = nn.Sequential(

            nn.Flatten(),

            nn.Linear(
                128 * 4 * 4,
                256,
            ),

            nn.ReLU(
                inplace=True
            ),

            # -----------------------------------------------
            # ONLY architectural change
            # -----------------------------------------------

            nn.Linear(
                256,
                embedding_dim,
                bias=False,
            ),
        )


    def forward(
        self,
        x,
    ):

        x = self.features(
            x
        )

        z = self.projection(
            x
        )


        z = F.normalize(
            z,
            p=2,
            dim=1,
            eps=1e-8,
        )


        return z

In [31]:
# ============================================================
# CELL 31 — SIAMESE COSINE V1
# ============================================================

class SiameseNetworkCosineV1(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()


        self.encoder = FCGRCNNEncoderCosineV1(
            embedding_dim=embedding_dim
        )


    def forward(
        self,
        pair_batch,
    ):

        batch_size = (
            pair_batch.shape[0]
        )


        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        z = self.encoder(
            x
        )


        z = z.reshape(
            batch_size,
            2,
            -1,
        )


        return (
            z[:, 0, :],
            z[:, 1, :],
        )

In [32]:
# ============================================================
# CELL 32 — INITIAL GEOMETRY COMPARISON
# ============================================================

def evaluate_initial_geometry(
    model_class,
    name,
    max_batches=30,
):

    set_seed(
        RANDOM_STATE
    )


    model = model_class(
        embedding_dim=EMBEDDING_DIM
    ).to(
        DEVICE
    )


    model.eval()


    similarities_list = []
    targets_list = []


    with torch.inference_mode():

        for batch_index, (
            pair_batch,
            target_batch,
        ) in enumerate(
            val_loader
        ):

            if batch_index >= max_batches:
                break


            pair_batch = pair_batch.to(
                DEVICE,
                non_blocking=True,
            )


            with torch.autocast(

                device_type=DEVICE.type,

                dtype=torch.float16,

                enabled=(
                    USE_AMP
                    and
                    DEVICE.type == "cuda"
                ),
            ):

                z1, z2 = model(
                    pair_batch
                )


            similarities = (
                F.cosine_similarity(

                    z1.float(),

                    z2.float(),

                    dim=1,

                    eps=1e-8,
                )
            )


            similarities_list.append(
                similarities.cpu()
            )


            targets_list.append(
                target_batch.cpu()
            )


    similarities = (
        torch.cat(
            similarities_list
        )
        .numpy()
    )


    targets = (
        torch.cat(
            targets_list
        )
        .numpy()
        .astype(int)
    )


    positive = (
        similarities[
            targets == 1
        ]
    )


    negative = (
        similarities[
            targets == 0
        ]
    )


    result = {

        "model":
            name,

        "mean":
            float(
                similarities.mean()
            ),

        "std":
            float(
                similarities.std()
            ),

        "min":
            float(
                similarities.min()
            ),

        "median":
            float(
                np.median(
                    similarities
                )
            ),

        "max":
            float(
                similarities.max()
            ),

        "cos_pos":
            float(
                positive.mean()
            ),

        "cos_neg":
            float(
                negative.mean()
            ),

        "gap":
            float(
                positive.mean()
                -
                negative.mean()
            ),

        "auc":
            float(
                roc_auc_score(
                    targets,
                    similarities,
                )
            ),
    }


    del model

    gc.collect()


    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()


    return result


baseline_geometry = (
    evaluate_initial_geometry(

        SiameseNetwork,

        "Baseline head",
    )
)


v1_geometry = (
    evaluate_initial_geometry(

        SiameseNetworkCosineV1,

        "Cosine V1 bias=False",
    )
)


initial_geometry_df = pd.DataFrame(
    [
        baseline_geometry,
        v1_geometry,
    ]
)


display(
    initial_geometry_df
)

,model,mean,std,min,median,max,cos_pos,cos_neg,gap,auc
0,Baseline head,0.999979,0.000077,0.998193,0.999993,1.0,0.999979,0.999979,-5.960464e-08,0.54481
1,Cosine V1 bias=False,0.999978,0.000080,0.998110,0.999993,1.0,0.999978,0.999978,-1.192093e-07,0.54445

In [33]:
# ============================================================
# CELL 33 — COSINE ENCODER V2
#
# Anti-collapse projection:
#
# Linear -> ReLU -> Linear(bias=False)
#        -> LayerNorm(affine=False)
#        -> L2 normalize
#
# CNN backbone remains identical to Baseline C.
# ============================================================

class FCGRCNNEncoderCosineV2(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()


        # ====================================================
        # SAME CNN AS BASELINE C
        # ====================================================

        self.features = nn.Sequential(

            nn.Conv2d(
                1,
                32,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                32,
            ),

            nn.ReLU(
                inplace=True,
            ),


            nn.Conv2d(
                32,
                32,
                kernel_size=3,
                padding=1,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.MaxPool2d(2),


            nn.Conv2d(
                32,
                64,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                64,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.MaxPool2d(2),


            nn.Conv2d(
                64,
                128,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                128,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.MaxPool2d(2),


            nn.Conv2d(
                128,
                128,
                kernel_size=3,
                padding=1,
            ),

            nn.GroupNorm(
                8,
                128,
            ),

            nn.ReLU(
                inplace=True,
            ),


            nn.AdaptiveAvgPool2d(
                (4, 4)
            ),
        )


        # ====================================================
        # COSINE PROJECTION HEAD V2
        # ====================================================

        self.projection = nn.Sequential(

            nn.Flatten(),

            nn.Linear(
                128 * 4 * 4,
                256,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.Linear(
                256,
                embedding_dim,
                bias=False,
            ),

            # ------------------------------------------------
            # Key V2 modification.
            #
            # Per-sample centering / scaling.
            # No learnable affine bias.
            # ------------------------------------------------

            nn.LayerNorm(
                embedding_dim,
                elementwise_affine=False,
            ),
        )


    def forward(
        self,
        x,
    ):

        x = self.features(
            x
        )


        z = self.projection(
            x
        )


        z = F.normalize(
            z,
            p=2,
            dim=1,
            eps=1e-8,
        )


        return z

In [34]:
# ============================================================
# CELL 34 — SIAMESE COSINE V2
# ============================================================

class SiameseNetworkCosineV2(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()


        self.encoder = (
            FCGRCNNEncoderCosineV2(
                embedding_dim=embedding_dim,
            )
        )


    def forward(
        self,
        pair_batch,
    ):

        batch_size = (
            pair_batch.shape[0]
        )


        # ----------------------------------------------------
        # [B, 2, 1, 64, 64]
        # ->
        # [2B, 1, 64, 64]
        # ----------------------------------------------------

        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        z = self.encoder(
            x
        )


        # ----------------------------------------------------
        # [2B, D]
        # ->
        # [B, 2, D]
        # ----------------------------------------------------

        z = z.reshape(
            batch_size,
            2,
            -1,
        )


        z1 = z[:, 0, :]

        z2 = z[:, 1, :]


        return z1, z2

In [35]:
# ============================================================
# CELL 35 — INITIAL GEOMETRY:
# BASELINE vs V1 vs V2
# ============================================================

baseline_geometry = (
    evaluate_initial_geometry(
        SiameseNetwork,
        "Baseline head",
    )
)


v1_geometry = (
    evaluate_initial_geometry(
        SiameseNetworkCosineV1,
        "V1 bias=False",
    )
)


v2_geometry = (
    evaluate_initial_geometry(
        SiameseNetworkCosineV2,
        "V2 LayerNorm",
    )
)


geometry_comparison_df = pd.DataFrame(
    [
        baseline_geometry,
        v1_geometry,
        v2_geometry,
    ]
)


display(
    geometry_comparison_df
)

,model,mean,std,min,median,max,cos_pos,cos_neg,gap,auc
0,Baseline head,0.999979,0.000077,0.998193,0.999993,1.0,0.999979,0.999979,-5.960464e-08,0.544810
1,V1 bias=False,0.999978,0.000080,0.998110,0.999993,1.0,0.999978,0.999978,-1.192093e-07,0.544450
2,V2 LayerNorm,0.999978,0.000082,0.998096,0.999993,1.0,0.999978,0.999978,-5.960464e-08,0.544683

In [36]:
# ============================================================
# CELL 36 — INITIAL GEOMETRY: FP32 vs AMP
# ============================================================

def evaluate_precision_geometry(
    use_amp,
    max_batches=30,
):

    set_seed(RANDOM_STATE)

    model = SiameseNetwork(
        embedding_dim=EMBEDDING_DIM
    ).to(DEVICE)

    model.eval()

    similarities_list = []
    targets_list = []

    with torch.inference_mode():

        for batch_index, (
            pair_batch,
            target_batch,
        ) in enumerate(val_loader):

            if batch_index >= max_batches:
                break

            pair_batch = pair_batch.to(
                DEVICE,
                non_blocking=True,
            )

            with torch.autocast(
                device_type=DEVICE.type,
                dtype=torch.float16,
                enabled=(
                    use_amp
                    and
                    DEVICE.type == "cuda"
                ),
            ):

                z1, z2 = model(
                    pair_batch
                )

            similarity = F.cosine_similarity(
                z1.float(),
                z2.float(),
                dim=1,
                eps=1e-8,
            )

            similarities_list.append(
                similarity.cpu()
            )

            targets_list.append(
                target_batch.cpu()
            )

    similarities = (
        torch.cat(similarities_list)
        .numpy()
    )

    targets = (
        torch.cat(targets_list)
        .numpy()
        .astype(int)
    )

    positive = similarities[
        targets == 1
    ]

    negative = similarities[
        targets == 0
    ]

    result = {
        "precision":
            "AMP FP16" if use_amp else "FP32",

        "mean":
            float(similarities.mean()),

        "std":
            float(similarities.std()),

        "min":
            float(similarities.min()),

        "median":
            float(np.median(similarities)),

        "max":
            float(similarities.max()),

        "cos_pos":
            float(positive.mean()),

        "cos_neg":
            float(negative.mean()),

        "gap":
            float(
                positive.mean()
                -
                negative.mean()
            ),

        "auc":
            float(
                roc_auc_score(
                    targets,
                    similarities,
                )
            ),
    }

    del model
    gc.collect()

    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()

    return result


precision_comparison_df = pd.DataFrame(
    [
        evaluate_precision_geometry(
            use_amp=False
        ),

        evaluate_precision_geometry(
            use_amp=True
        ),
    ]
)


display(
    precision_comparison_df
)

,precision,mean,std,min,median,max,cos_pos,cos_neg,gap,auc
0,FP32,0.999979,0.000078,0.998168,0.999993,1.0,0.999979,0.999979,-1.192093e-07,0.544611
1,AMP FP16,0.999979,0.000077,0.998193,0.999993,1.0,0.999979,0.999979,-5.960464e-08,0.544810

In [37]:
# ============================================================
# CELL 37 — STAGE-WISE GEOMETRY DIAGNOSTIC
# ============================================================

set_seed(RANDOM_STATE)

stage_model = FCGRCNNEncoder(
    embedding_dim=EMBEDDING_DIM
).to(DEVICE)

stage_model.eval()


stage_values = {
    "cnn_flat": [],
    "hidden_linear": [],
    "hidden_relu": [],
    "raw_embedding": [],
    "normalized_embedding": [],
}


MAX_STAGE_BATCHES = 20


def paired_cosine(
    x,
    batch_size,
):

    x = x.reshape(
        batch_size,
        2,
        -1,
    )

    x1 = x[:, 0, :]
    x2 = x[:, 1, :]

    return F.cosine_similarity(
        x1.float(),
        x2.float(),
        dim=1,
        eps=1e-8,
    )


with torch.inference_mode():

    for batch_index, (
        pair_batch,
        _,
    ) in enumerate(val_loader):

        if batch_index >= MAX_STAGE_BATCHES:
            break

        batch_size = (
            pair_batch.shape[0]
        )

        pair_batch = pair_batch.to(
            DEVICE,
            non_blocking=True,
        )

        # Deliberately FP32 for diagnosis.
        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        # ----------------------------------------------------
        # CNN
        # ----------------------------------------------------

        features = stage_model.features(
            x
        )

        flat = torch.flatten(
            features,
            start_dim=1,
        )


        # ----------------------------------------------------
        # Projection head, explicitly stage by stage
        # ----------------------------------------------------

        hidden_linear = (
            stage_model.projection[1](
                flat
            )
        )

        hidden_relu = (
            stage_model.projection[2](
                hidden_linear
            )
        )

        raw_embedding = (
            stage_model.projection[3](
                hidden_relu
            )
        )

        normalized_embedding = F.normalize(
            raw_embedding,
            p=2,
            dim=1,
            eps=1e-8,
        )


        tensors = {
            "cnn_flat":
                flat,

            "hidden_linear":
                hidden_linear,

            "hidden_relu":
                hidden_relu,

            "raw_embedding":
                raw_embedding,

            "normalized_embedding":
                normalized_embedding,
        }


        for name, tensor in tensors.items():

            similarities = paired_cosine(
                tensor,
                batch_size,
            )

            stage_values[name].append(
                similarities.cpu()
            )


# ============================================================
# SUMMARY
# ============================================================

stage_results = []


for name, chunks in stage_values.items():

    similarities = (
        torch.cat(chunks)
        .numpy()
    )

    stage_results.append(
        {
            "stage":
                name,

            "mean_cosine":
                float(
                    similarities.mean()
                ),

            "std_cosine":
                float(
                    similarities.std()
                ),

            "min_cosine":
                float(
                    similarities.min()
                ),

            "median_cosine":
                float(
                    np.median(
                        similarities
                    )
                ),

            "max_cosine":
                float(
                    similarities.max()
                ),
        }
    )


stage_geometry_df = pd.DataFrame(
    stage_results
)


display(
    stage_geometry_df
)


del stage_model

gc.collect()

if DEVICE.type == "cuda":
    torch.cuda.empty_cache()

,stage,mean_cosine,std_cosine,min_cosine,median_cosine,max_cosine
0,cnn_flat,0.999978,0.000087,0.998215,0.999993,1.0
1,hidden_linear,0.999975,0.000096,0.997966,0.999993,1.0
2,hidden_relu,0.999975,0.000096,0.997966,0.999993,1.0
3,raw_embedding,0.999978,0.000084,0.998202,0.999993,1.0
4,normalized_embedding,0.999978,0.000084,0.998202,0.999993,1.0

In [38]:
# ============================================================
# CELL 38 — RAW FCGR GEOMETRY DIAGNOSTIC
#
# Goal:
# determine whether the strong common direction already exists
# in the k=6 FCGR inputs, before the CNN.
# ============================================================

raw_cosine_chunks = []
centered_cosine_chunks = []
target_chunks = []

MAX_RAW_BATCHES = 30


with torch.inference_mode():

    for batch_index, (
        pair_batch,
        target_batch,
    ) in enumerate(val_loader):

        if batch_index >= MAX_RAW_BATCHES:
            break


        # pair_batch:
        # [B, 2, 1, 64, 64]

        pair_batch = pair_batch.float()


        batch_size = pair_batch.shape[0]


        # ====================================================
        # RAW FCGR
        # ====================================================

        x1 = pair_batch[:, 0].flatten(
            start_dim=1
        )

        x2 = pair_batch[:, 1].flatten(
            start_dim=1
        )


        raw_cosine = F.cosine_similarity(
            x1,
            x2,
            dim=1,
            eps=1e-8,
        )


        # ====================================================
        # DIAGNOSTIC COMMON-COMPONENT REMOVAL
        #
        # Compute mean FCGR across all 2B samples in the batch.
        #
        # IMPORTANT:
        # this is only a diagnostic, NOT yet preprocessing.
        # ====================================================

        all_fcgr = pair_batch.reshape(
            batch_size * 2,
            -1,
        )


        common_component = all_fcgr.mean(
            dim=0,
            keepdim=True,
        )


        x1_centered = (
            x1
            -
            common_component
        )


        x2_centered = (
            x2
            -
            common_component
        )


        centered_cosine = F.cosine_similarity(
            x1_centered,
            x2_centered,
            dim=1,
            eps=1e-8,
        )


        raw_cosine_chunks.append(
            raw_cosine
        )

        centered_cosine_chunks.append(
            centered_cosine
        )

        target_chunks.append(
            target_batch
        )


# ============================================================
# CONCATENATE
# ============================================================

raw_cosine = torch.cat(
    raw_cosine_chunks
).numpy()


centered_cosine = torch.cat(
    centered_cosine_chunks
).numpy()


targets = (
    torch.cat(
        target_chunks
    )
    .numpy()
    .astype(int)
)


# ============================================================
# SUMMARY FUNCTION
# ============================================================

def summarize_input_geometry(
    name,
    similarities,
    targets,
):

    positive = similarities[
        targets == 1
    ]

    negative = similarities[
        targets == 0
    ]


    return {

        "representation":
            name,

        "mean":
            float(
                similarities.mean()
            ),

        "std":
            float(
                similarities.std()
            ),

        "min":
            float(
                similarities.min()
            ),

        "median":
            float(
                np.median(
                    similarities
                )
            ),

        "max":
            float(
                similarities.max()
            ),

        "cos_pos":
            float(
                positive.mean()
            ),

        "cos_neg":
            float(
                negative.mean()
            ),

        "gap":
            float(
                positive.mean()
                -
                negative.mean()
            ),

        "auc":
            float(
                roc_auc_score(
                    targets,
                    similarities,
                )
            ),
    }


raw_geometry = summarize_input_geometry(
    "Raw FCGR",
    raw_cosine,
    targets,
)


centered_geometry = summarize_input_geometry(
    "FCGR - common component",
    centered_cosine,
    targets,
)


input_geometry_df = pd.DataFrame(
    [
        raw_geometry,
        centered_geometry,
    ]
)


display(
    input_geometry_df
)

,representation,mean,std,min,median,max,cos_pos,cos_neg,gap,auc
0,Raw FCGR,0.146689,0.125572,0.000000,0.114744,0.950246,0.153469,0.139433,0.014035,0.516279
1,FCGR - common component,0.008114,0.082143,-0.431066,-0.004093,0.782943,0.014796,0.000963,0.013833,0.549318

In [39]:
# ============================================================
# CELL 39 — FIRST CNN BLOCK GEOMETRY
# ============================================================

set_seed(RANDOM_STATE)

diagnostic_encoder = FCGRCNNEncoder(
    embedding_dim=EMBEDDING_DIM
).to(DEVICE)

diagnostic_encoder.eval()


stage_chunks = {
    "raw_fcgr": [],
    "conv1": [],
    "groupnorm1": [],
    "relu1": [],
    "conv2": [],
    "relu2": [],
    "pool1": [],
}


MAX_BATCHES = 20


def pairwise_stage_cosine(
    tensor,
    batch_size,
):

    tensor = tensor.reshape(
        batch_size,
        2,
        -1,
    )

    return F.cosine_similarity(
        tensor[:, 0].float(),
        tensor[:, 1].float(),
        dim=1,
        eps=1e-8,
    )


with torch.inference_mode():

    for batch_index, (
        pair_batch,
        _,
    ) in enumerate(val_loader):

        if batch_index >= MAX_BATCHES:
            break


        batch_size = pair_batch.shape[0]


        pair_batch = pair_batch.to(
            DEVICE,
            non_blocking=True,
        )


        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        # Raw input

        stage_chunks[
            "raw_fcgr"
        ].append(
            pairwise_stage_cosine(
                x,
                batch_size,
            ).cpu()
        )


        # ----------------------------------------------------
        # First CNN block
        # ----------------------------------------------------

        conv1 = (
            diagnostic_encoder
            .features[0](x)
        )


        gn1 = (
            diagnostic_encoder
            .features[1](conv1)
        )


        relu1 = (
            diagnostic_encoder
            .features[2](gn1)
        )


        conv2 = (
            diagnostic_encoder
            .features[3](relu1)
        )


        relu2 = (
            diagnostic_encoder
            .features[4](conv2)
        )


        pool1 = (
            diagnostic_encoder
            .features[5](relu2)
        )


        tensors = {
            "conv1":
                conv1,

            "groupnorm1":
                gn1,

            "relu1":
                relu1,

            "conv2":
                conv2,

            "relu2":
                relu2,

            "pool1":
                pool1,
        }


        for name, tensor in tensors.items():

            stage_chunks[
                name
            ].append(

                pairwise_stage_cosine(
                    tensor,
                    batch_size,
                ).cpu()
            )


# ============================================================
# SUMMARY
# ============================================================

first_block_results = []


for name, chunks in stage_chunks.items():

    sims = (
        torch.cat(chunks)
        .numpy()
    )


    first_block_results.append(
        {
            "stage":
                name,

            "mean_cosine":
                float(sims.mean()),

            "std_cosine":
                float(sims.std()),

            "min_cosine":
                float(sims.min()),

            "median_cosine":
                float(np.median(sims)),

            "max_cosine":
                float(sims.max()),
        }
    )


first_block_df = pd.DataFrame(
    first_block_results
)


display(
    first_block_df
)


del diagnostic_encoder

gc.collect()

if DEVICE.type == "cuda":
    torch.cuda.empty_cache()

        stage  mean_cosine  std_cosine  min_cosine  median_cosine  max_cosine
0    raw_fcgr     0.147286    0.125416    0.000000       0.115842    0.897374
1       conv1     0.999989    0.000019    0.999633       0.999993    1.000000
2  groupnorm1     0.999967    0.000040    0.999413       0.999977    1.000000
3       relu1     0.999967    0.000040    0.999413       0.999977    1.000000
4       conv2     0.999984    0.000019    0.999738       0.999988    1.000000
5       relu2     0.999984    0.000019    0.999738       0.999988    1.000000
6       pool1     0.999980    0.000032    0.999494       0.999989    1.000000

In [43]:
# ============================================================
# CELL 39b — CONV1 BIAS ABLATION
#
# Same Conv1 weights:
#   1) normal output with bias
#   2) output with bias manually removed
#
# This isolates the effect of Conv1 bias.
# ============================================================

set_seed(RANDOM_STATE)

diagnostic_encoder = FCGRCNNEncoder(
    embedding_dim=EMBEDDING_DIM
).to(DEVICE)

diagnostic_encoder.eval()


with_bias_chunks = []
without_bias_chunks = []
raw_chunks = []

MAX_BATCHES = 20


with torch.inference_mode():

    for batch_index, (
        pair_batch,
        _
    ) in enumerate(val_loader):

        if batch_index >= MAX_BATCHES:
            break


        batch_size = pair_batch.shape[0]

        pair_batch = pair_batch.to(
            DEVICE,
            non_blocking=True,
        )


        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        conv1_layer = (
            diagnostic_encoder.features[0]
        )


        # ====================================================
        # NORMAL CONV1
        # ====================================================

        conv_with_bias = conv1_layer(
            x
        )


        # ====================================================
        # SAME WEIGHTS — NO BIAS
        # ====================================================

        conv_without_bias = F.conv2d(

            x,

            weight=conv1_layer.weight,

            bias=None,

            stride=conv1_layer.stride,

            padding=conv1_layer.padding,

            dilation=conv1_layer.dilation,

            groups=conv1_layer.groups,
        )


        # ====================================================
        # PAIRWISE COSINE
        # ====================================================

        raw_chunks.append(

            pairwise_stage_cosine(
                x,
                batch_size,
            ).cpu()
        )


        with_bias_chunks.append(

            pairwise_stage_cosine(
                conv_with_bias,
                batch_size,
            ).cpu()
        )


        without_bias_chunks.append(

            pairwise_stage_cosine(
                conv_without_bias,
                batch_size,
            ).cpu()
        )


def summarize_cosine(
    name,
    chunks,
):

    values = (
        torch.cat(chunks)
        .numpy()
    )


    return {

        "representation":
            name,

        "mean_cosine":
            float(values.mean()),

        "std_cosine":
            float(values.std()),

        "min_cosine":
            float(values.min()),

        "median_cosine":
            float(np.median(values)),

        "max_cosine":
            float(values.max()),
    }


conv1_bias_test_df = pd.DataFrame(
    [
        summarize_cosine(
            "Raw FCGR",
            raw_chunks,
        ),

        summarize_cosine(
            "Conv1 with bias",
            with_bias_chunks,
        ),

        summarize_cosine(
            "Conv1 same weights, bias removed",
            without_bias_chunks,
        ),
    ]
)


display(
    conv1_bias_test_df
)


# ============================================================
# EXTRA: BIAS vs SIGNAL MAGNITUDE
# ============================================================

print()
print("=" * 70)
print("CONV1 MAGNITUDE CHECK")
print("=" * 70)

print(
    "Input abs mean:",
    float(x.abs().mean())
)

print(
    "Input abs max:",
    float(x.abs().max())
)

print()

print(
    "Conv signal abs mean (no bias):",
    float(
        conv_without_bias
        .abs()
        .mean()
    )
)

print(
    "Conv1 bias abs mean:",
    float(
        conv1_layer.bias
        .abs()
        .mean()
    )
)

print(
    "Conv1 bias abs max:",
    float(
        conv1_layer.bias
        .abs()
        .max()
    )
)


del diagnostic_encoder

gc.collect()

if DEVICE.type == "cuda":
    torch.cuda.empty_cache()

,representation,mean_cosine,std_cosine,min_cosine,median_cosine,max_cosine
0,Raw FCGR,0.147286,0.125416,0.000000,0.115842,0.897374
1,Conv1 with bias,0.999989,0.000019,0.999633,0.999993,1.000000
2,"Conv1 same weights, bias removed",0.157613,0.126908,-0.003911,0.128089,0.907671

======================================================================
CONV1 MAGNITUDE CHECK
======================================================================
Input abs mean: 0.000244140625
Input abs max: 0.2222222238779068

Conv signal abs mean (no bias): 0.0002732232096605003
Conv1 bias abs mean: 0.16031858325004578
Conv1 bias abs max: 0.32862916588783264

C:\Users\simon\AppData\Local\Temp\ipykernel_17996\3957375863.py:211: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\autograd\generated\python_variable_methods.cpp:839.)
  float(

In [44]:
# ============================================================
# CELL 40 — COSINE V3
# BIAS-FREE CNN
# ============================================================

class FCGRCNNEncoderCosineV3(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()


        self.features = nn.Sequential(

            # ==================================================
            # 64 x 64
            # ==================================================

            nn.Conv2d(
                1,
                32,
                kernel_size=3,
                padding=1,
                bias=False,
            ),

            nn.GroupNorm(
                8,
                32,
            ),

            nn.ReLU(
                inplace=True,
            ),


            nn.Conv2d(
                32,
                32,
                kernel_size=3,
                padding=1,
                bias=False,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.MaxPool2d(2),


            # ==================================================
            # 32 x 32
            # ==================================================

            nn.Conv2d(
                32,
                64,
                kernel_size=3,
                padding=1,
                bias=False,
            ),

            nn.GroupNorm(
                8,
                64,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.MaxPool2d(2),


            # ==================================================
            # 16 x 16
            # ==================================================

            nn.Conv2d(
                64,
                128,
                kernel_size=3,
                padding=1,
                bias=False,
            ),

            nn.GroupNorm(
                8,
                128,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.MaxPool2d(2),


            # ==================================================
            # 8 x 8
            # ==================================================

            nn.Conv2d(
                128,
                128,
                kernel_size=3,
                padding=1,
                bias=False,
            ),

            nn.GroupNorm(
                8,
                128,
            ),

            nn.ReLU(
                inplace=True,
            ),


            nn.AdaptiveAvgPool2d(
                (4, 4)
            ),
        )


        # ====================================================
        # SAME PROJECTION AS BASELINE C
        # ====================================================

        self.projection = nn.Sequential(

            nn.Flatten(),

            nn.Linear(
                128 * 4 * 4,
                256,
            ),

            nn.ReLU(
                inplace=True,
            ),

            nn.Linear(
                256,
                embedding_dim,
            ),
        )


    def forward(
        self,
        x,
    ):

        x = self.features(
            x
        )

        z = self.projection(
            x
        )

        z = F.normalize(
            z,
            p=2,
            dim=1,
            eps=1e-8,
        )

        return z

In [45]:
# ============================================================
# CELL 41 — SIAMESE COSINE V3
# ============================================================

class SiameseNetworkCosineV3(nn.Module):

    def __init__(
        self,
        embedding_dim=128,
    ):

        super().__init__()

        self.encoder = (
            FCGRCNNEncoderCosineV3(
                embedding_dim=embedding_dim,
            )
        )


    def forward(
        self,
        pair_batch,
    ):

        batch_size = (
            pair_batch.shape[0]
        )


        x = pair_batch.reshape(
            batch_size * 2,
            1,
            64,
            64,
        )


        z = self.encoder(
            x
        )


        z = z.reshape(
            batch_size,
            2,
            -1,
        )


        return (
            z[:, 0],
            z[:, 1],
        )

In [46]:
# ============================================================
# CELL 42 — INITIAL GEOMETRY:
# BASELINE vs BIAS-FREE CNN
# ============================================================

baseline_geometry = (
    evaluate_initial_geometry(
        SiameseNetwork,
        "Baseline CNN",
    )
)


v3_geometry = (
    evaluate_initial_geometry(
        SiameseNetworkCosineV3,
        "V3 conv bias=False",
    )
)


bias_geometry_df = pd.DataFrame(
    [
        baseline_geometry,
        v3_geometry,
    ]
)


display(
    bias_geometry_df
)

,model,mean,std,min,median,max,cos_pos,cos_neg,gap,auc
0,Baseline CNN,0.999979,0.000077,0.998193,0.999993,1.000000,0.999979,0.999979,-5.960464e-08,0.54481
1,V3 conv bias=False,0.944419,0.045570,0.462310,0.958633,0.994376,0.945797,0.942944,2.852559e-03,0.55091

In [47]:
# ============================================================
# CELL 43 — TRAINING COMPONENT FACTORY — COSINE V3
#
# V3:
# - convolution bias=False
# - GroupNorm
# - same projection head
# - official CosineEmbeddingLoss
# ============================================================

def build_training_components_v3(
    margin,
):

    # --------------------------------------------------------
    # Reproducible initialization
    # --------------------------------------------------------

    set_seed(
        RANDOM_STATE
    )


    # --------------------------------------------------------
    # COSINE V3 MODEL
    # --------------------------------------------------------

    model = SiameseNetworkCosineV3(
        embedding_dim=EMBEDDING_DIM
    ).to(
        DEVICE
    )


    # --------------------------------------------------------
    # OPTIMIZER
    # --------------------------------------------------------

    fused_adamw = False


    try:

        optimizer = torch.optim.AdamW(

            model.parameters(),

            lr=LEARNING_RATE,

            weight_decay=WEIGHT_DECAY,

            fused=(
                DEVICE.type == "cuda"
            ),
        )


        fused_adamw = (
            DEVICE.type == "cuda"
        )


    except (
        TypeError,
        RuntimeError,
    ):

        optimizer = torch.optim.AdamW(

            model.parameters(),

            lr=LEARNING_RATE,

            weight_decay=WEIGHT_DECAY,
        )


    # --------------------------------------------------------
    # AMP
    # --------------------------------------------------------

    amp_enabled = (
        USE_AMP
        and
        DEVICE.type == "cuda"
    )


    if hasattr(
        torch,
        "amp"
    ):

        scaler = torch.amp.GradScaler(
            "cuda",
            enabled=amp_enabled,
        )

    else:

        scaler = torch.cuda.amp.GradScaler(
            enabled=amp_enabled
        )


    # --------------------------------------------------------
    # OFFICIAL COSINE LOSS WRAPPER
    # --------------------------------------------------------

    criterion = CosineMetricLoss(
        margin=margin
    )


    return (
        model,
        optimizer,
        scaler,
        criterion,
        fused_adamw,
    )


print("=" * 70)
print("COSINE V3 TRAINING CONFIGURATION")
print("=" * 70)

print(
    "Model:",
    "SiameseNetworkCosineV3"
)

print(
    "Conv bias:",
    False
)

print(
    "LR:",
    LEARNING_RATE
)

print(
    "Weight decay:",
    WEIGHT_DECAY
)

print(
    "AMP:",
    AMP_ENABLED
)

print(
    "Cosine margin:",
    REFERENCE_COSINE_MARGIN
)

======================================================================
COSINE V3 TRAINING CONFIGURATION
======================================================================
Model: SiameseNetworkCosineV3
Conv bias: False
LR: 0.0005
Weight decay: 0.0001
AMP: True
Cosine margin: 0.21875

In [49]:
import inspect

print(
    inspect.signature(
        run_epoch
    )
)

(model, loader, criterion, optimizer=None, scaler=None, collect_outputs=False)

In [51]:
# ============================================================
# DEBUG — CHECK run_epoch RETURN STRUCTURE
# ============================================================

debug_result = run_epoch(
    model=smoke_model,
    loader=smoke_val_loader,
    criterion=smoke_criterion,
    optimizer=None,
    scaler=None,
    collect_outputs=True,
)

print("Type:", type(debug_result))
print("Length:", len(debug_result))

for i, value in enumerate(debug_result):

    print()
    print(f"Element {i}")
    print("Type:", type(value))

    if hasattr(value, "shape"):
        print("Shape:", value.shape)

    elif isinstance(value, (list, tuple)):
        print("Length:", len(value))

    else:
        print("Value:", value)

Type: <class 'tuple'>
Length: 3

Element 0
Type: <class 'dict'>
Value: {'loss': 0.3545454740524292, 'cos_pos': 0.7070900797843933, 'cos_neg': 0.6321941018104553, 'cos_gap': 0.07489597797393799, 'seconds': 3.3548801000015374, 'pairs_per_second': 2980.732455981189}

Element 1
Type: <class 'numpy.ndarray'>
Shape: (10000,)

Element 2
Type: <class 'numpy.ndarray'>
Shape: (10000,)

In [52]:
# ============================================================
# CELL 44 — COSINE V3 SMOKE TEST
#
# 5 epochs from scratch.
#
# Goal:
# verify that the bias-free CNN avoids cosine collapse
# during optimization.
# ============================================================

SMOKE_EPOCHS = 5


# ============================================================
# FRESH LOADERS
# ============================================================

(
    smoke_train_loader,
    smoke_val_loader,
    _
) = build_experiment_loaders()


# ============================================================
# FRESH V3 MODEL
# ============================================================

(
    smoke_model,
    smoke_optimizer,
    smoke_scaler,
    smoke_criterion,
    smoke_fused_adamw,
) = build_training_components_v3(
    margin=REFERENCE_COSINE_MARGIN
)


print("=" * 70)
print("COSINE V3 — 5 EPOCH SMOKE TEST")
print("=" * 70)

print(
    "Margin:",
    REFERENCE_COSINE_MARGIN
)

print(
    "Learning rate:",
    LEARNING_RATE
)

print(
    "Fused AdamW:",
    smoke_fused_adamw
)

print(
    "AMP:",
    AMP_ENABLED
)

print()


# ============================================================
# STORAGE
# ============================================================

smoke_history = []


# ============================================================
# TRAINING LOOP
# ============================================================

for epoch in range(
    1,
    SMOKE_EPOCHS + 1,
):

    # ========================================================
    # TRAIN
    # ========================================================

    train_output = run_epoch(

        model=smoke_model,

        loader=smoke_train_loader,

        criterion=smoke_criterion,

        optimizer=smoke_optimizer,

        scaler=smoke_scaler,

        collect_outputs=False,
    )


    # run_epoch may return either:
    # metrics_dict
    # OR
    # (metrics_dict, ...)
    if isinstance(
        train_output,
        tuple,
    ):

        train_metrics = (
            train_output[0]
        )

    else:

        train_metrics = (
            train_output
        )


    # ========================================================
    # VALIDATION
    # ========================================================

    val_output = run_epoch(

        model=smoke_model,

        loader=smoke_val_loader,

        criterion=smoke_criterion,

        optimizer=None,

        scaler=None,

        collect_outputs=True,
    )


    # Exact structure verified experimentally:
    #
    # (
    #     metrics_dict,
    #     targets,
    #     similarities,
    # )

    (
        val_metrics,
        val_targets,
        val_scores,
    ) = val_output


    val_targets = np.asarray(
        val_targets
    ).astype(
        np.int64
    )


    val_scores = np.asarray(
        val_scores
    )


    # ========================================================
    # ROC-AUC
    # ========================================================

    val_auc = roc_auc_score(
        val_targets,
        val_scores,
    )


    # ========================================================
    # POSITIVE / NEGATIVE DISTRIBUTIONS
    # ========================================================

    positive_scores = (
        val_scores[
            val_targets == 1
        ]
    )


    negative_scores = (
        val_scores[
            val_targets == 0
        ]
    )


    cos_pos = float(
        positive_scores.mean()
    )


    cos_neg = float(
        negative_scores.mean()
    )


    gap = (
        cos_pos
        -
        cos_neg
    )


    # ========================================================
    # D-PRIME
    # ========================================================

    pooled_std = np.sqrt(

        0.5
        *
        (
            positive_scores.var()
            +
            negative_scores.var()
        )

        +

        1e-12
    )


    d_prime = float(
        gap
        /
        pooled_std
    )


    # ========================================================
    # SAVE HISTORY
    # ========================================================

    epoch_result = {

        "epoch":
            epoch,

        "train_loss":
            float(
                train_metrics["loss"]
            ),

        "val_loss":
            float(
                val_metrics["loss"]
            ),

        "val_auc":
            float(
                val_auc
            ),

        "cos_pos":
            cos_pos,

        "cos_neg":
            cos_neg,

        "gap":
            gap,

        "d_prime":
            d_prime,

        "train_seconds":
            float(
                train_metrics.get(
                    "seconds",
                    np.nan,
                )
            ),

        "val_seconds":
            float(
                val_metrics.get(
                    "seconds",
                    np.nan,
                )
            ),
    }


    smoke_history.append(
        epoch_result
    )


    # ========================================================
    # PRINT
    # ========================================================

    print(

        f"Epoch {epoch:02d}/{SMOKE_EPOCHS}"

        f" | train loss "
        f"{epoch_result['train_loss']:.5f}"

        f" | val loss "
        f"{epoch_result['val_loss']:.5f}"

        f" | val AUC "
        f"{epoch_result['val_auc']:.5f}"

        f" | cos+ "
        f"{epoch_result['cos_pos']:.4f}"

        f" | cos- "
        f"{epoch_result['cos_neg']:.4f}"

        f" | gap "
        f"{epoch_result['gap']:.4f}"

        f" | d' "
        f"{epoch_result['d_prime']:.3f}"

        f" | "
        f"{epoch_result['train_seconds']:.1f}s"
    )


# ============================================================
# FINAL TABLE
# ============================================================

smoke_history_df = pd.DataFrame(
    smoke_history
)


display(
    smoke_history_df
)

======================================================================
COSINE V3 — 5 EPOCH SMOKE TEST
======================================================================
Margin: 0.21875
Learning rate: 0.0005
Fused AdamW: True
AMP: True

Epoch 01/5 | train loss 0.37235 | val loss 0.35455 | val AUC 0.56529 | cos+ 0.7071 | cos- 0.6322 | gap 0.0749 | d' 0.213 | 32.0s
Epoch 02/5 | train loss 0.35482 | val loss 0.35181 | val AUC 0.56807 | cos+ 0.7088 | cos- 0.6336 | gap 0.0752 | d' 0.220 | 61.2s
Epoch 03/5 | train loss 0.33966 | val loss 0.34480 | val AUC 0.59479 | cos+ 0.7213 | cos- 0.6312 | gap 0.0902 | d' 0.287 | 163.3s
Epoch 04/5 | train loss 0.33771 | val loss 0.33705 | val AUC 0.60672 | cos+ 0.7211 | cos- 0.6095 | gap 0.1115 | d' 0.350 | 109.4s
Epoch 05/5 | train loss 0.33381 | val loss 0.33568 | val AUC 0.60843 | cos+ 0.6941 | cos- 0.5835 | gap 0.1106 | d' 0.352 | 43.8s

,epoch,train_loss,val_loss,val_auc,cos_pos,cos_neg,gap,d_prime,train_seconds,val_seconds
0,1,0.372350,0.354545,0.565292,0.707090,0.632194,0.074896,0.212694,31.987483,2.805566
1,2,0.354823,0.351815,0.568068,0.708776,0.633582,0.075195,0.219611,61.184255,13.099535
2,3,0.339662,0.344799,0.594787,0.721335,0.631156,0.090179,0.287174,163.301904,19.712824
3,4,0.337710,0.337051,0.606724,0.721056,0.609540,0.111515,0.350217,109.377744,4.850561
4,5,0.333808,0.335680,0.608434,0.694087,0.583474,0.110613,0.352438,43.759265,4.934352

In [53]:
# ============================================================
# CELL 45 — FULL COSINE V3 TRAINING
#
# Reference configuration:
# - bias-free CNN
# - GroupNorm
# - official CosineEmbeddingLoss
# - cosine margin = 0.21875
# - checkpoint on validation ROC-AUC
# - early stopping
# ============================================================


def train_cosine_v3_experiment(
    margin,
    experiment_name,
):

    # ========================================================
    # FRESH DATA LOADERS
    # ========================================================

    (
        train_loader_exp,
        val_loader_exp,
        test_loader_exp,
    ) = build_experiment_loaders()


    # ========================================================
    # FRESH MODEL / OPTIMIZER / LOSS
    # ========================================================

    (
        model,
        optimizer,
        scaler,
        criterion,
        fused_adamw,
    ) = build_training_components_v3(
        margin=margin
    )


    print("=" * 70)
    print(
        "EXPERIMENT:",
        experiment_name
    )
    print("=" * 70)

    print(
        "Cosine margin:",
        margin
    )

    print(
        "Learning rate:",
        LEARNING_RATE
    )

    print(
        "Fused AdamW:",
        fused_adamw
    )

    print(
        "AMP:",
        AMP_ENABLED
    )

    print(
        "Max epochs:",
        MAX_EPOCHS
    )

    print(
        "Early stopping patience:",
        EARLY_STOPPING_PATIENCE
    )

    print()


    # ========================================================
    # TRACKING
    # ========================================================

    history = []

    best_val_auc = -np.inf

    best_epoch = 0

    best_state = None

    epochs_without_improvement = 0


    # ========================================================
    # TRAINING LOOP
    # ========================================================

    for epoch in range(
        1,
        MAX_EPOCHS + 1,
    ):

        # ----------------------------------------------------
        # TRAIN
        # ----------------------------------------------------

        train_output = run_epoch(

            model=model,

            loader=train_loader_exp,

            criterion=criterion,

            optimizer=optimizer,

            scaler=scaler,

            collect_outputs=False,
        )


        if isinstance(
            train_output,
            tuple,
        ):

            train_metrics = (
                train_output[0]
            )

        else:

            train_metrics = (
                train_output
            )


        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        (
            val_metrics,
            val_targets,
            val_scores,
        ) = run_epoch(

            model=model,

            loader=val_loader_exp,

            criterion=criterion,

            optimizer=None,

            scaler=None,

            collect_outputs=True,
        )


        val_targets = np.asarray(
            val_targets
        ).astype(
            np.int64
        )


        val_scores = np.asarray(
            val_scores
        )


        # ====================================================
        # VALIDATION METRICS
        # ====================================================

        val_auc = float(
            roc_auc_score(
                val_targets,
                val_scores,
            )
        )


        positive_scores = (
            val_scores[
                val_targets == 1
            ]
        )


        negative_scores = (
            val_scores[
                val_targets == 0
            ]
        )


        cos_pos = float(
            positive_scores.mean()
        )


        cos_neg = float(
            negative_scores.mean()
        )


        gap = float(
            cos_pos
            -
            cos_neg
        )


        pooled_std = np.sqrt(

            0.5
            *
            (
                positive_scores.var()
                +
                negative_scores.var()
            )

            +

            1e-12
        )


        d_prime = float(
            gap
            /
            pooled_std
        )


        # ====================================================
        # CHECKPOINT
        # ====================================================

        improved = (
            val_auc
            >
            best_val_auc
            +
            MIN_DELTA
        )


        if improved:

            best_val_auc = (
                val_auc
            )

            best_epoch = (
                epoch
            )

            epochs_without_improvement = 0


            # CPU checkpoint in memory
            best_state = {

                key:
                    value
                    .detach()
                    .cpu()
                    .clone()

                for key, value
                in model.state_dict().items()
            }


        else:

            epochs_without_improvement += 1


        # ====================================================
        # HISTORY
        # ====================================================

        epoch_result = {

            "epoch":
                epoch,

            "train_loss":
                float(
                    train_metrics["loss"]
                ),

            "val_loss":
                float(
                    val_metrics["loss"]
                ),

            "val_auc":
                val_auc,

            "cos_pos":
                cos_pos,

            "cos_neg":
                cos_neg,

            "gap":
                gap,

            "d_prime":
                d_prime,

            "train_seconds":
                float(
                    train_metrics.get(
                        "seconds",
                        np.nan,
                    )
                ),

            "val_seconds":
                float(
                    val_metrics.get(
                        "seconds",
                        np.nan,
                    )
                ),
        }


        history.append(
            epoch_result
        )


        # ====================================================
        # PRINT
        # ====================================================

        marker = (
            " *BEST*"
            if improved
            else ""
        )


        print(

            f"Epoch "
            f"{epoch:02d}/{MAX_EPOCHS}"

            f" | train loss "
            f"{epoch_result['train_loss']:.5f}"

            f" | val loss "
            f"{epoch_result['val_loss']:.5f}"

            f" | val AUC "
            f"{val_auc:.5f}"

            f" | cos+ "
            f"{cos_pos:.4f}"

            f" | cos- "
            f"{cos_neg:.4f}"

            f" | gap "
            f"{gap:.4f}"

            f" | d' "
            f"{d_prime:.3f}"

            f" | "
            f"{epoch_result['train_seconds']:.1f}s"

            f"{marker}"
        )


        # ====================================================
        # EARLY STOPPING
        # ====================================================

        if (
            epochs_without_improvement
            >=
            EARLY_STOPPING_PATIENCE
        ):

            print()
            print(
                "Early stopping at epoch",
                epoch
            )

            break


    # ========================================================
    # RESTORE BEST MODEL
    # ========================================================

    if best_state is None:

        raise RuntimeError(
            "No valid checkpoint was created."
        )


    model.load_state_dict(
        best_state
    )


    model.to(
        DEVICE
    )


    history_df = pd.DataFrame(
        history
    )


    print()
    print("=" * 70)
    print("TRAINING COMPLETE")
    print("=" * 70)

    print(
        "Best epoch:",
        best_epoch
    )

    print(
        "Best validation ROC-AUC:",
        f"{best_val_auc:.6f}"
    )


    return {
        "model":
            model,

        "history":
            history_df,

        "best_epoch":
            best_epoch,

        "best_val_auc":
            best_val_auc,

        "margin":
            margin,

        "experiment_name":
            experiment_name,

        "test_loader":
            test_loader_exp,
    }

In [54]:
# ============================================================
# CELL 46 — RUN COSINE V3 REFERENCE
# ============================================================

cosine_v3_reference = (
    train_cosine_v3_experiment(

        margin=
            REFERENCE_COSINE_MARGIN,

        experiment_name=
            "cosine_v3_biasfree_margin_0p21875",
    )
)

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p21875
======================================================================
Cosine margin: 0.21875
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.37235 | val loss 0.35455 | val AUC 0.56529 | cos+ 0.7071 | cos- 0.6322 | gap 0.0749 | d' 0.213 | 20.0s *BEST*
Epoch 02/50 | train loss 0.35482 | val loss 0.35181 | val AUC 0.56807 | cos+ 0.7088 | cos- 0.6336 | gap 0.0752 | d' 0.220 | 19.7s *BEST*
Epoch 03/50 | train loss 0.33966 | val loss 0.34480 | val AUC 0.59479 | cos+ 0.7213 | cos- 0.6312 | gap 0.0902 | d' 0.287 | 41.1s *BEST*
Epoch 04/50 | train loss 0.33771 | val loss 0.33705 | val AUC 0.60672 | cos+ 0.7211 | cos- 0.6095 | gap 0.1115 | d' 0.350 | 106.3s *BEST*
Epoch 05/50 | train loss 0.33381 | val loss 0.33568 | val AUC 0.60843 | cos+ 0.6941 | cos- 0.5835 | gap 0.1106 | d' 0.352 | 74.2s *BEST*
Epoch 06/50 | train loss 0.33311 | val loss 0.33501 | val AUC 0.60820 | cos+ 0.6787 | cos- 0.5632 | gap 0.1155 | d' 0.350 | 21.0s
Epoch 07/50 | train loss 0.33291 | val loss 0.33435 | val AUC 0.60700 | cos+ 0.7089 | cos- 0.5967 | gap 0.1123 | d' 0.352 | 21.1s
Epoch 08/50 | train loss 0.33204 | val loss 0.33109 | val AUC 0.60827 | cos+ 0.6743 | cos- 0.5543 | gap 0.1200 | d' 0.353 | 28.9s
Epoch 09/50 | train loss 0.33068 | val loss 0.32883 | val AUC 0.61159 | cos+ 0.6975 | cos- 0.5744 | gap 0.1231 | d' 0.352 | 109.5s *BEST*
Epoch 10/50 | train loss 0.33169 | val loss 0.33102 | val AUC 0.60892 | cos+ 0.6961 | cos- 0.5754 | gap 0.1207 | d' 0.344 | 108.0s
Epoch 11/50 | train loss 0.32939 | val loss 0.33496 | val AUC 0.60702 | cos+ 0.7101 | cos- 0.6002 | gap 0.1099 | d' 0.335 | 64.4s
Epoch 12/50 | train loss 0.32634 | val loss 0.32904 | val AUC 0.61086 | cos+ 0.7064 | cos- 0.5845 | gap 0.1219 | d' 0.347 | 23.0s
Epoch 13/50 | train loss 0.32554 | val loss 0.32974 | val AUC 0.61369 | cos+ 0.6718 | cos- 0.5487 | gap 0.1231 | d' 0.351 | 22.8s *BEST*
Epoch 14/50 | train loss 0.32832 | val loss 0.32969 | val AUC 0.61104 | cos+ 0.6725 | cos- 0.5462 | gap 0.1263 | d' 0.366 | 62.9s
Epoch 15/50 | train loss 0.32805 | val loss 0.33916 | val AUC 0.60246 | cos+ 0.6772 | cos- 0.5686 | gap 0.1086 | d' 0.332 | 60.1s
Epoch 16/50 | train loss 0.32646 | val loss 0.32712 | val AUC 0.61273 | cos+ 0.6752 | cos- 0.5450 | gap 0.1302 | d' 0.367 | 22.4s
Epoch 17/50 | train loss 0.32265 | val loss 0.34411 | val AUC 0.59142 | cos+ 0.6868 | cos- 0.5944 | gap 0.0925 | d' 0.259 | 22.6s
Epoch 18/50 | train loss 0.32306 | val loss 0.32595 | val AUC 0.61326 | cos+ 0.6929 | cos- 0.5633 | gap 0.1296 | d' 0.360 | 94.3s
Epoch 19/50 | train loss 0.32565 | val loss 0.32851 | val AUC 0.60565 | cos+ 0.7075 | cos- 0.5843 | gap 0.1232 | d' 0.347 | 22.4s
Epoch 20/50 | train loss 0.32226 | val loss 0.32558 | val AUC 0.61412 | cos+ 0.6841 | cos- 0.5532 | gap 0.1308 | d' 0.386 | 22.4s *BEST*
Epoch 21/50 | train loss 0.32357 | val loss 0.32423 | val AUC 0.61534 | cos+ 0.6951 | cos- 0.5621 | gap 0.1330 | d' 0.373 | 39.6s *BEST*
Epoch 22/50 | train loss 0.32735 | val loss 0.32352 | val AUC 0.62018 | cos+ 0.7031 | cos- 0.5690 | gap 0.1341 | d' 0.380 | 70.2s *BEST*
Epoch 23/50 | train loss 0.31950 | val loss 0.32358 | val AUC 0.61727 | cos+ 0.6888 | cos- 0.5548 | gap 0.1339 | d' 0.383 | 22.3s
Epoch 24/50 | train loss 0.31866 | val loss 0.32828 | val AUC 0.61125 | cos+ 0.7057 | cos- 0.5821 | gap 0.1236 | d' 0.347 | 22.5s
Epoch 25/50 | train loss 0.32069 | val loss 0.32323 | val AUC 0.62018 | cos+ 0.6836 | cos- 0.5461 | gap 0.1375 | d' 0.388 | 87.3s
Epoch 26/50 | train loss 0.32713 | val loss 0.32367 | val AUC 0.61935 | cos+ 0.6999 | cos- 0.5648 | gap 0.1350 | d' 0.389 | 22.5s
Epoch 27/50 | train loss 0.32594 | val loss 0.34876 | val AUC 0.58487 | cos+ 0.7212 | cos- 0.6402 | gap 0.0810 | d' 0.229 | 22.6s
Epoch 28/50 | train loss 0.32187 | val loss 0.32367 | val AUC 0.62015 | cos+ 0.7037 | cos- 0.5684 | gap 0.1353 | d' 0.380 | 72.6s
Epoch 29/50 | train loss 0.32219 | val loss 0.32806 | val AUC 0.61575 | cos+ 0.6897 | cos- 0.5591 | gap 0.1307 | d' 0.363 | 43.3s
Epoch 30/50 | train loss 0.32335 | val loss 0.32445 | val AUC 0.61954 | cos+ 0.6764 | cos- 0.5417 | gap 0.1348 | d' 0.392 | 22.5s
Epoch 31/50 | train loss 0.32093 | val loss 0.32214 | val AUC 0.62660 | cos+ 0.6767 | cos- 0.5385 | gap 0.1382 | d' 0.401 | 37.1s *BEST*
Epoch 32/50 | train loss 0.31874 | val loss 0.32667 | val AUC 0.62351 | cos+ 0.6708 | cos- 0.5421 | gap 0.1288 | d' 0.373 | 81.9s
Epoch 33/50 | train loss 0.32188 | val loss 0.32252 | val AUC 0.62805 | cos+ 0.6577 | cos- 0.5195 | gap 0.1382 | d' 0.413 | 22.4s *BEST*
Epoch 34/50 | train loss 0.31950 | val loss 0.31924 | val AUC 0.63174 | cos+ 0.6662 | cos- 0.5214 | gap 0.1448 | d' 0.435 | 22.5s *BEST*
Epoch 35/50 | train loss 0.31742 | val loss 0.32395 | val AUC 0.62797 | cos+ 0.6804 | cos- 0.5456 | gap 0.1349 | d' 0.424 | 93.7s
Epoch 36/50 | train loss 0.31721 | val loss 0.32092 | val AUC 0.62865 | cos+ 0.6516 | cos- 0.5088 | gap 0.1428 | d' 0.429 | 34.2s
Epoch 37/50 | train loss 0.31950 | val loss 0.32201 | val AUC 0.62890 | cos+ 0.6754 | cos- 0.5350 | gap 0.1404 | d' 0.428 | 22.5s
Epoch 38/50 | train loss 0.31886 | val loss 0.32033 | val AUC 0.63342 | cos+ 0.6636 | cos- 0.5212 | gap 0.1424 | d' 0.435 | 29.8s *BEST*
Epoch 39/50 | train loss 0.31674 | val loss 0.32044 | val AUC 0.63207 | cos+ 0.6616 | cos- 0.5191 | gap 0.1425 | d' 0.433 | 78.0s
Epoch 40/50 | train loss 0.31581 | val loss 0.31886 | val AUC 0.63418 | cos+ 0.6740 | cos- 0.5292 | gap 0.1448 | d' 0.446 | 22.4s *BEST*
Epoch 41/50 | train loss 0.31873 | val loss 0.31738 | val AUC 0.64013 | cos+ 0.6533 | cos- 0.5021 | gap 0.1512 | d' 0.475 | 22.5s *BEST*
Epoch 42/50 | train loss 0.31484 | val loss 0.31889 | val AUC 0.64115 | cos+ 0.6548 | cos- 0.5082 | gap 0.1467 | d' 0.456 | 90.3s *BEST*
Epoch 43/50 | train loss 0.31064 | val loss 0.31908 | val AUC 0.63784 | cos+ 0.6539 | cos- 0.5076 | gap 0.1463 | d' 0.461 | 22.4s
Epoch 44/50 | train loss 0.31256 | val loss 0.31763 | val AUC 0.64113 | cos+ 0.6541 | cos- 0.5052 | gap 0.1489 | d' 0.460 | 22.5s
Epoch 45/50 | train loss 0.30865 | val loss 0.32086 | val AUC 0.63335 | cos+ 0.6437 | cos- 0.4985 | gap 0.1452 | d' 0.444 | 76.6s
Epoch 46/50 | train loss 0.31019 | val loss 0.31949 | val AUC 0.63829 | cos+ 0.6367 | cos- 0.4905 | gap 0.1462 | d' 0.461 | 38.2s
Epoch 47/50 | train loss 0.31040 | val loss 0.31765 | val AUC 0.63967 | cos+ 0.6394 | cos- 0.4899 | gap 0.1495 | d' 0.460 | 22.4s
Epoch 48/50 | train loss 0.31098 | val loss 0.31618 | val AUC 0.63768 | cos+ 0.6475 | cos- 0.4954 | gap 0.1521 | d' 0.463 | 22.5s
Epoch 49/50 | train loss 0.31020 | val loss 0.31920 | val AUC 0.63838 | cos+ 0.6306 | cos- 0.4809 | gap 0.1497 | d' 0.462 | 86.6s
Epoch 50/50 | train loss 0.31101 | val loss 0.31863 | val AUC 0.63903 | cos+ 0.6355 | cos- 0.4867 | gap 0.1488 | d' 0.448 | 22.4s

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 42
Best validation ROC-AUC: 0.641155

In [57]:
# ============================================================
# CELL 47 — COSINE V3 MARGIN ABLATION
#
# Reference margin 0.21875 has already been trained.
# Train only the remaining margins.
# ============================================================

COSINE_MARGINS_TO_RUN = [
    0.00,
    0.10,
    0.35,
]


cosine_v3_margin_results = {

    REFERENCE_COSINE_MARGIN:
        cosine_v3_reference
}


for margin in COSINE_MARGINS_TO_RUN:

    margin_tag = (
        str(margin)
        .replace(".", "p")
    )


    experiment_name = (
        f"cosine_v3_biasfree_margin_{margin_tag}"
    )


    print()
    print("#" * 80)
    print(
        "STARTING:",
        experiment_name
    )
    print("#" * 80)
    print()


    result = train_cosine_v3_experiment(

        margin=margin,

        experiment_name=experiment_name,
    )


    cosine_v3_margin_results[
        margin
    ] = result

################################################################################
STARTING: cosine_v3_biasfree_margin_0p0
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p0
======================================================================
Cosine margin: 0.0
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.47701 | val loss 0.45969 | val AUC 0.55786 | cos+ 0.6343 | cos- 0.5576 | gap 0.0766 | d' 0.176 | 30.8s *BEST*
Epoch 02/50 | train loss 0.45237 | val loss 0.45453 | val AUC 0.56675 | cos+ 0.6277 | cos- 0.5403 | gap 0.0874 | d' 0.200 | 50.0s *BEST*
Epoch 03/50 | train loss 0.45012 | val loss 0.43718 | val AUC 0.58997 | cos+ 0.6647 | cos- 0.5408 | gap 0.1238 | d' 0.282 | 115.2s *BEST*
Epoch 04/50 | train loss 0.43881 | val loss 0.43615 | val AUC 0.60054 | cos+ 0.5670 | cos- 0.4254 | gap 0.1416 | d' 0.326 | 114.3s *BEST*
Epoch 05/50 | train loss 0.43088 | val loss 0.43953 | val AUC 0.59787 | cos+ 0.6007 | cos- 0.4809 | gap 0.1198 | d' 0.287 | 114.1s
Epoch 06/50 | train loss 0.42639 | val loss 0.43467 | val AUC 0.59920 | cos+ 0.6018 | cos- 0.4705 | gap 0.1314 | d' 0.332 | 114.3s
Epoch 07/50 | train loss 0.42727 | val loss 0.42610 | val AUC 0.59777 | cos+ 0.6631 | cos- 0.5123 | gap 0.1508 | d' 0.351 | 112.1s
Epoch 08/50 | train loss 0.42791 | val loss 0.42274 | val AUC 0.60926 | cos+ 0.6024 | cos- 0.4396 | gap 0.1628 | d' 0.366 | 111.1s *BEST*
Epoch 09/50 | train loss 0.42708 | val loss 0.42581 | val AUC 0.60289 | cos+ 0.6230 | cos- 0.4738 | gap 0.1492 | d' 0.341 | 110.3s
Epoch 10/50 | train loss 0.42387 | val loss 0.41922 | val AUC 0.61020 | cos+ 0.6316 | cos- 0.4716 | gap 0.1600 | d' 0.359 | 108.6s *BEST*
Epoch 11/50 | train loss 0.42388 | val loss 0.43417 | val AUC 0.60062 | cos+ 0.5955 | cos- 0.4646 | gap 0.1310 | d' 0.319 | 112.1s
Epoch 12/50 | train loss 0.42136 | val loss 0.41975 | val AUC 0.61058 | cos+ 0.6169 | cos- 0.4564 | gap 0.1604 | d' 0.350 | 109.2s *BEST*
Epoch 13/50 | train loss 0.42226 | val loss 0.42733 | val AUC 0.60309 | cos+ 0.6294 | cos- 0.4863 | gap 0.1431 | d' 0.329 | 108.1s
Epoch 14/50 | train loss 0.41930 | val loss 0.42189 | val AUC 0.61215 | cos+ 0.6134 | cos- 0.4578 | gap 0.1556 | d' 0.355 | 107.1s *BEST*
Epoch 15/50 | train loss 0.42000 | val loss 0.42377 | val AUC 0.60214 | cos+ 0.5851 | cos- 0.4317 | gap 0.1535 | d' 0.345 | 106.4s
Epoch 16/50 | train loss 0.41903 | val loss 0.42185 | val AUC 0.60520 | cos+ 0.6165 | cos- 0.4587 | gap 0.1579 | d' 0.336 | 106.2s
Epoch 17/50 | train loss 0.41274 | val loss 0.41670 | val AUC 0.61265 | cos+ 0.6020 | cos- 0.4349 | gap 0.1671 | d' 0.360 | 105.9s *BEST*
Epoch 18/50 | train loss 0.41529 | val loss 0.46571 | val AUC 0.54730 | cos+ 0.7306 | cos- 0.6693 | gap 0.0613 | d' 0.140 | 105.7s
Epoch 19/50 | train loss 0.41840 | val loss 0.42899 | val AUC 0.59772 | cos+ 0.5808 | cos- 0.4392 | gap 0.1417 | d' 0.324 | 105.7s
Epoch 20/50 | train loss 0.41166 | val loss 0.41386 | val AUC 0.61278 | cos+ 0.6052 | cos- 0.4335 | gap 0.1717 | d' 0.367 | 105.6s *BEST*
Epoch 21/50 | train loss 0.41454 | val loss 0.41237 | val AUC 0.61735 | cos+ 0.6093 | cos- 0.4328 | gap 0.1765 | d' 0.376 | 106.0s *BEST*
Epoch 22/50 | train loss 0.41238 | val loss 0.41221 | val AUC 0.61721 | cos+ 0.6144 | cos- 0.4366 | gap 0.1778 | d' 0.378 | 105.9s
Epoch 23/50 | train loss 0.40944 | val loss 0.41281 | val AUC 0.61719 | cos+ 0.6274 | cos- 0.4545 | gap 0.1729 | d' 0.378 | 105.6s
Epoch 24/50 | train loss 0.41287 | val loss 0.41153 | val AUC 0.61892 | cos+ 0.6347 | cos- 0.4593 | gap 0.1754 | d' 0.386 | 105.9s *BEST*
Epoch 25/50 | train loss 0.40826 | val loss 0.41385 | val AUC 0.61794 | cos+ 0.6003 | cos- 0.4259 | gap 0.1744 | d' 0.378 | 106.0s
Epoch 26/50 | train loss 0.41420 | val loss 0.41613 | val AUC 0.61352 | cos+ 0.6194 | cos- 0.4502 | gap 0.1692 | d' 0.362 | 106.2s
Epoch 27/50 | train loss 0.41020 | val loss 0.41406 | val AUC 0.61673 | cos+ 0.5816 | cos- 0.4093 | gap 0.1723 | d' 0.378 | 106.6s
Epoch 28/50 | train loss 0.42495 | val loss 0.40905 | val AUC 0.61924 | cos+ 0.6265 | cos- 0.4442 | gap 0.1823 | d' 0.394 | 106.3s *BEST*
Epoch 29/50 | train loss 0.41091 | val loss 0.42068 | val AUC 0.61276 | cos+ 0.6027 | cos- 0.4416 | gap 0.1611 | d' 0.347 | 106.2s
Epoch 30/50 | train loss 0.40982 | val loss 0.44659 | val AUC 0.57935 | cos+ 0.6518 | cos- 0.5483 | gap 0.1035 | d' 0.221 | 105.9s
Epoch 31/50 | train loss 0.40862 | val loss 0.41147 | val AUC 0.62239 | cos+ 0.5903 | cos- 0.4121 | gap 0.1783 | d' 0.379 | 105.9s *BEST*
Epoch 32/50 | train loss 0.40512 | val loss 0.41507 | val AUC 0.61754 | cos+ 0.5744 | cos- 0.4035 | gap 0.1710 | d' 0.376 | 105.5s
Epoch 33/50 | train loss 0.40839 | val loss 0.40708 | val AUC 0.62591 | cos+ 0.6139 | cos- 0.4283 | gap 0.1856 | d' 0.407 | 105.5s *BEST*
Epoch 34/50 | train loss 0.40285 | val loss 0.40943 | val AUC 0.62095 | cos+ 0.6032 | cos- 0.4218 | gap 0.1815 | d' 0.396 | 105.4s
Epoch 35/50 | train loss 0.40550 | val loss 0.41376 | val AUC 0.62103 | cos+ 0.6160 | cos- 0.4429 | gap 0.1731 | d' 0.378 | 105.2s
Epoch 36/50 | train loss 0.41071 | val loss 0.40985 | val AUC 0.62548 | cos+ 0.6080 | cos- 0.4277 | gap 0.1803 | d' 0.400 | 105.4s
Epoch 37/50 | train loss 0.40525 | val loss 0.43615 | val AUC 0.59283 | cos+ 0.6123 | cos- 0.4863 | gap 0.1260 | d' 0.268 | 105.8s
Epoch 38/50 | train loss 0.40405 | val loss 0.40993 | val AUC 0.62179 | cos+ 0.6023 | cos- 0.4215 | gap 0.1809 | d' 0.393 | 105.3s
Epoch 39/50 | train loss 0.40978 | val loss 0.46936 | val AUC 0.54979 | cos+ 0.7987 | cos- 0.7488 | gap 0.0499 | d' 0.124 | 105.4s
Epoch 40/50 | train loss 0.42182 | val loss 0.40539 | val AUC 0.62570 | cos+ 0.6250 | cos- 0.4367 | gap 0.1882 | d' 0.415 | 105.3s
Epoch 41/50 | train loss 0.40753 | val loss 0.40781 | val AUC 0.62668 | cos+ 0.5858 | cos- 0.3994 | gap 0.1864 | d' 0.407 | 105.2s *BEST*
Epoch 42/50 | train loss 0.40721 | val loss 0.40730 | val AUC 0.62257 | cos+ 0.6208 | cos- 0.4359 | gap 0.1849 | d' 0.395 | 105.5s
Epoch 43/50 | train loss 0.39737 | val loss 0.40781 | val AUC 0.62183 | cos+ 0.6071 | cos- 0.4226 | gap 0.1844 | d' 0.412 | 105.3s
Epoch 44/50 | train loss 0.40845 | val loss 0.40584 | val AUC 0.62992 | cos+ 0.6136 | cos- 0.4246 | gap 0.1890 | d' 0.404 | 105.3s *BEST*
Epoch 45/50 | train loss 0.40219 | val loss 0.40700 | val AUC 0.62579 | cos+ 0.5999 | cos- 0.4129 | gap 0.1870 | d' 0.420 | 105.3s
Epoch 46/50 | train loss 0.39848 | val loss 0.41356 | val AUC 0.62548 | cos+ 0.5945 | cos- 0.4210 | gap 0.1736 | d' 0.379 | 105.3s
Epoch 47/50 | train loss 0.40460 | val loss 0.40622 | val AUC 0.62812 | cos+ 0.5969 | cos- 0.4089 | gap 0.1879 | d' 0.418 | 105.8s
Epoch 48/50 | train loss 0.40254 | val loss 0.40476 | val AUC 0.62870 | cos+ 0.6065 | cos- 0.4156 | gap 0.1909 | d' 0.421 | 105.7s
Epoch 49/50 | train loss 0.40144 | val loss 0.40498 | val AUC 0.62950 | cos+ 0.6094 | cos- 0.4193 | gap 0.1901 | d' 0.421 | 105.3s
Epoch 50/50 | train loss 0.40353 | val loss 0.40821 | val AUC 0.62861 | cos+ 0.5761 | cos- 0.3911 | gap 0.1850 | d' 0.418 | 105.2s

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 44
Best validation ROC-AUC: 0.629923

################################################################################
STARTING: cosine_v3_biasfree_margin_0p1
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p1
======================================================================
Cosine margin: 0.1
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.41835 | val loss 0.39992 | val AUC 0.57169 | cos+ 0.7132 | cos- 0.6179 | gap 0.0953 | d' 0.239 | 105.3s *BEST*
Epoch 02/50 | train loss 0.39878 | val loss 0.38985 | val AUC 0.60598 | cos+ 0.5941 | cos- 0.4695 | gap 0.1245 | d' 0.322 | 105.6s *BEST*
Epoch 03/50 | train loss 0.39098 | val loss 0.39235 | val AUC 0.59741 | cos+ 0.6189 | cos- 0.5040 | gap 0.1149 | d' 0.314 | 105.5s
Epoch 04/50 | train loss 0.39640 | val loss 0.38950 | val AUC 0.60213 | cos+ 0.5931 | cos- 0.4673 | gap 0.1258 | d' 0.325 | 105.4s
Epoch 05/50 | train loss 0.38193 | val loss 0.38019 | val AUC 0.61149 | cos+ 0.5821 | cos- 0.4404 | gap 0.1417 | d' 0.355 | 105.4s *BEST*
Epoch 06/50 | train loss 0.38593 | val loss 0.40280 | val AUC 0.57494 | cos+ 0.6963 | cos- 0.6062 | gap 0.0902 | d' 0.244 | 105.4s
Epoch 07/50 | train loss 0.39729 | val loss 0.40220 | val AUC 0.58952 | cos+ 0.7316 | cos- 0.6412 | gap 0.0904 | d' 0.221 | 105.4s
Epoch 08/50 | train loss 0.39282 | val loss 0.38168 | val AUC 0.61006 | cos+ 0.5934 | cos- 0.4534 | gap 0.1400 | d' 0.359 | 105.7s
Epoch 09/50 | train loss 0.37890 | val loss 0.38041 | val AUC 0.61414 | cos+ 0.5930 | cos- 0.4507 | gap 0.1423 | d' 0.364 | 105.4s *BEST*
Epoch 10/50 | train loss 0.37402 | val loss 0.37675 | val AUC 0.61706 | cos+ 0.5948 | cos- 0.4446 | gap 0.1503 | d' 0.386 | 105.4s *BEST*
Epoch 11/50 | train loss 0.37747 | val loss 0.38061 | val AUC 0.60965 | cos+ 0.6220 | cos- 0.4825 | gap 0.1395 | d' 0.357 | 105.2s
Epoch 12/50 | train loss 0.37883 | val loss 0.40198 | val AUC 0.56884 | cos+ 0.6822 | cos- 0.5898 | gap 0.0925 | d' 0.224 | 105.3s
Epoch 13/50 | train loss 0.37259 | val loss 0.38016 | val AUC 0.61574 | cos+ 0.5933 | cos- 0.4512 | gap 0.1421 | d' 0.365 | 105.5s
Epoch 14/50 | train loss 0.37642 | val loss 0.38184 | val AUC 0.60702 | cos+ 0.6213 | cos- 0.4838 | gap 0.1375 | d' 0.337 | 105.2s
Epoch 15/50 | train loss 0.37587 | val loss 0.37202 | val AUC 0.62420 | cos+ 0.6054 | cos- 0.4440 | gap 0.1614 | d' 0.416 | 105.3s *BEST*
Epoch 16/50 | train loss 0.37012 | val loss 0.37144 | val AUC 0.62390 | cos+ 0.6194 | cos- 0.4601 | gap 0.1593 | d' 0.416 | 105.2s
Epoch 17/50 | train loss 0.36939 | val loss 0.36862 | val AUC 0.63049 | cos+ 0.6180 | cos- 0.4536 | gap 0.1643 | d' 0.436 | 105.3s *BEST*
Epoch 18/50 | train loss 0.36872 | val loss 0.36842 | val AUC 0.62873 | cos+ 0.6220 | cos- 0.4570 | gap 0.1650 | d' 0.428 | 105.8s
Epoch 19/50 | train loss 0.36738 | val loss 0.36740 | val AUC 0.62883 | cos+ 0.6406 | cos- 0.4750 | gap 0.1657 | d' 0.436 | 105.4s
Epoch 20/50 | train loss 0.36619 | val loss 0.36561 | val AUC 0.63234 | cos+ 0.6178 | cos- 0.4467 | gap 0.1711 | d' 0.438 | 105.4s *BEST*
Epoch 21/50 | train loss 0.36571 | val loss 0.36939 | val AUC 0.62458 | cos+ 0.6153 | cos- 0.4528 | gap 0.1625 | d' 0.414 | 105.4s
Epoch 22/50 | train loss 0.37138 | val loss 0.36731 | val AUC 0.62907 | cos+ 0.6188 | cos- 0.4510 | gap 0.1678 | d' 0.433 | 105.4s
Epoch 23/50 | train loss 0.36499 | val loss 0.36593 | val AUC 0.63056 | cos+ 0.6331 | cos- 0.4629 | gap 0.1702 | d' 0.442 | 105.7s
Epoch 24/50 | train loss 0.36717 | val loss 0.37119 | val AUC 0.62245 | cos+ 0.6196 | cos- 0.4584 | gap 0.1612 | d' 0.402 | 105.4s
Epoch 25/50 | train loss 0.36307 | val loss 0.36864 | val AUC 0.62814 | cos+ 0.6228 | cos- 0.4570 | gap 0.1658 | d' 0.418 | 105.3s
Epoch 26/50 | train loss 0.36670 | val loss 0.36534 | val AUC 0.63033 | cos+ 0.6489 | cos- 0.4782 | gap 0.1707 | d' 0.432 | 105.4s
Epoch 27/50 | train loss 0.37249 | val loss 0.36649 | val AUC 0.63790 | cos+ 0.6346 | cos- 0.4645 | gap 0.1700 | d' 0.467 | 105.3s *BEST*
Epoch 28/50 | train loss 0.36449 | val loss 0.36536 | val AUC 0.63141 | cos+ 0.6533 | cos- 0.4826 | gap 0.1707 | d' 0.424 | 105.5s
Epoch 29/50 | train loss 0.36400 | val loss 0.36823 | val AUC 0.63130 | cos+ 0.6135 | cos- 0.4420 | gap 0.1716 | d' 0.430 | 105.6s
Epoch 30/50 | train loss 0.36317 | val loss 0.36794 | val AUC 0.63277 | cos+ 0.6353 | cos- 0.4705 | gap 0.1648 | d' 0.428 | 105.3s
Epoch 31/50 | train loss 0.36574 | val loss 0.36378 | val AUC 0.63514 | cos+ 0.6425 | cos- 0.4688 | gap 0.1737 | d' 0.436 | 105.3s
Epoch 32/50 | train loss 0.36398 | val loss 0.36955 | val AUC 0.62926 | cos+ 0.6237 | cos- 0.4611 | gap 0.1626 | d' 0.414 | 105.3s
Epoch 33/50 | train loss 0.36478 | val loss 0.37117 | val AUC 0.62750 | cos+ 0.6369 | cos- 0.4773 | gap 0.1596 | d' 0.433 | 54.6s
Epoch 34/50 | train loss 0.36813 | val loss 0.36505 | val AUC 0.63873 | cos+ 0.6267 | cos- 0.4544 | gap 0.1722 | d' 0.447 | 22.2s *BEST*
Epoch 35/50 | train loss 0.36188 | val loss 0.36711 | val AUC 0.63558 | cos+ 0.6285 | cos- 0.4599 | gap 0.1686 | d' 0.444 | 22.1s
Epoch 36/50 | train loss 0.36226 | val loss 0.36502 | val AUC 0.63483 | cos+ 0.6179 | cos- 0.4433 | gap 0.1746 | d' 0.440 | 92.2s
Epoch 37/50 | train loss 0.36354 | val loss 0.36731 | val AUC 0.63570 | cos+ 0.6272 | cos- 0.4571 | gap 0.1701 | d' 0.443 | 105.3s
Epoch 38/50 | train loss 0.36282 | val loss 0.36279 | val AUC 0.64086 | cos+ 0.6383 | cos- 0.4622 | gap 0.1762 | d' 0.458 | 105.3s *BEST*
Epoch 39/50 | train loss 0.36457 | val loss 0.36523 | val AUC 0.63028 | cos+ 0.6346 | cos- 0.4633 | gap 0.1714 | d' 0.435 | 105.3s
Epoch 40/50 | train loss 0.36233 | val loss 0.36172 | val AUC 0.63711 | cos+ 0.6469 | cos- 0.4698 | gap 0.1770 | d' 0.459 | 105.4s
Epoch 41/50 | train loss 0.36587 | val loss 0.36383 | val AUC 0.63908 | cos+ 0.6314 | cos- 0.4570 | gap 0.1744 | d' 0.452 | 105.5s
Epoch 42/50 | train loss 0.36272 | val loss 0.36751 | val AUC 0.63287 | cos+ 0.6419 | cos- 0.4751 | gap 0.1669 | d' 0.425 | 105.6s
Epoch 43/50 | train loss 0.35969 | val loss 0.36807 | val AUC 0.63453 | cos+ 0.6270 | cos- 0.4620 | gap 0.1650 | d' 0.430 | 105.3s
Epoch 44/50 | train loss 0.36039 | val loss 0.36570 | val AUC 0.63444 | cos+ 0.6385 | cos- 0.4679 | gap 0.1706 | d' 0.428 | 105.3s
Epoch 45/50 | train loss 0.35944 | val loss 0.36564 | val AUC 0.63898 | cos+ 0.6297 | cos- 0.4590 | gap 0.1707 | d' 0.455 | 105.2s
Epoch 46/50 | train loss 0.35774 | val loss 0.36645 | val AUC 0.63828 | cos+ 0.6087 | cos- 0.4363 | gap 0.1724 | d' 0.458 | 73.8s
Epoch 47/50 | train loss 0.36156 | val loss 0.36730 | val AUC 0.63855 | cos+ 0.6260 | cos- 0.4584 | gap 0.1676 | d' 0.441 | 20.2s
Epoch 48/50 | train loss 0.35975 | val loss 0.36460 | val AUC 0.63958 | cos+ 0.6274 | cos- 0.4529 | gap 0.1745 | d' 0.452 | 21.8s

Early stopping at epoch 48

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 38
Best validation ROC-AUC: 0.640862

################################################################################
STARTING: cosine_v3_biasfree_margin_0p35
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p35
======================================================================
Cosine margin: 0.35
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.29080 | val loss 0.27969 | val AUC 0.61123 | cos+ 0.7629 | cos- 0.6676 | gap 0.0953 | d' 0.371 | 59.9s *BEST*
Epoch 02/50 | train loss 0.27834 | val loss 0.27962 | val AUC 0.61253 | cos+ 0.7432 | cos- 0.6528 | gap 0.0904 | d' 0.374 | 105.2s *BEST*
Epoch 03/50 | train loss 0.27505 | val loss 0.27755 | val AUC 0.62010 | cos+ 0.7334 | cos- 0.6346 | gap 0.0988 | d' 0.412 | 105.3s *BEST*
Epoch 04/50 | train loss 0.27839 | val loss 0.27963 | val AUC 0.61675 | cos+ 0.6835 | cos- 0.5794 | gap 0.1041 | d' 0.395 | 105.4s
Epoch 05/50 | train loss 0.27227 | val loss 0.27597 | val AUC 0.62221 | cos+ 0.7003 | cos- 0.5891 | gap 0.1112 | d' 0.414 | 105.3s *BEST*
Epoch 06/50 | train loss 0.27256 | val loss 0.28702 | val AUC 0.59385 | cos+ 0.7395 | cos- 0.6635 | gap 0.0761 | d' 0.279 | 105.4s
Epoch 07/50 | train loss 0.27058 | val loss 0.27169 | val AUC 0.63155 | cos+ 0.7210 | cos- 0.6104 | gap 0.1106 | d' 0.448 | 85.5s *BEST*
Epoch 08/50 | train loss 0.27163 | val loss 0.27315 | val AUC 0.62686 | cos+ 0.7071 | cos- 0.5989 | gap 0.1082 | d' 0.427 | 22.0s
Epoch 09/50 | train loss 0.26674 | val loss 0.27150 | val AUC 0.63014 | cos+ 0.7178 | cos- 0.6062 | gap 0.1117 | d' 0.427 | 22.2s
Epoch 10/50 | train loss 0.26529 | val loss 0.26701 | val AUC 0.64313 | cos+ 0.7076 | cos- 0.5859 | gap 0.1217 | d' 0.478 | 57.0s *BEST*
Epoch 11/50 | train loss 0.26722 | val loss 0.26990 | val AUC 0.62832 | cos+ 0.7241 | cos- 0.6121 | gap 0.1120 | d' 0.436 | 105.5s
Epoch 12/50 | train loss 0.26434 | val loss 0.26599 | val AUC 0.63611 | cos+ 0.7162 | cos- 0.5958 | gap 0.1204 | d' 0.461 | 105.4s
Epoch 13/50 | train loss 0.26515 | val loss 0.26678 | val AUC 0.64083 | cos+ 0.7038 | cos- 0.5840 | gap 0.1198 | d' 0.468 | 105.3s
Epoch 14/50 | train loss 0.26285 | val loss 0.26447 | val AUC 0.64547 | cos+ 0.7097 | cos- 0.5836 | gap 0.1261 | d' 0.494 | 105.8s *BEST*
Epoch 15/50 | train loss 0.26263 | val loss 0.26602 | val AUC 0.64343 | cos+ 0.6936 | cos- 0.5688 | gap 0.1249 | d' 0.476 | 105.3s
Epoch 16/50 | train loss 0.26224 | val loss 0.26380 | val AUC 0.64363 | cos+ 0.7170 | cos- 0.5915 | gap 0.1255 | d' 0.479 | 22.2s
Epoch 17/50 | train loss 0.26044 | val loss 0.26304 | val AUC 0.64675 | cos+ 0.7116 | cos- 0.5819 | gap 0.1297 | d' 0.490 | 22.4s *BEST*
Epoch 18/50 | train loss 0.26100 | val loss 0.26443 | val AUC 0.64409 | cos+ 0.7129 | cos- 0.5889 | gap 0.1240 | d' 0.480 | 26.6s
Epoch 19/50 | train loss 0.26300 | val loss 0.26871 | val AUC 0.63573 | cos+ 0.7454 | cos- 0.6319 | gap 0.1135 | d' 0.469 | 105.4s
Epoch 20/50 | train loss 0.26078 | val loss 0.26254 | val AUC 0.65041 | cos+ 0.6939 | cos- 0.5615 | gap 0.1324 | d' 0.499 | 105.3s *BEST*
Epoch 21/50 | train loss 0.26076 | val loss 0.26504 | val AUC 0.64087 | cos+ 0.7148 | cos- 0.5903 | gap 0.1244 | d' 0.465 | 105.5s
Epoch 22/50 | train loss 0.26096 | val loss 0.26131 | val AUC 0.64898 | cos+ 0.7040 | cos- 0.5717 | gap 0.1323 | d' 0.498 | 105.4s
Epoch 23/50 | train loss 0.25998 | val loss 0.26283 | val AUC 0.64457 | cos+ 0.7284 | cos- 0.6010 | gap 0.1275 | d' 0.491 | 105.1s
Epoch 24/50 | train loss 0.25714 | val loss 0.26385 | val AUC 0.64233 | cos+ 0.7151 | cos- 0.5860 | gap 0.1290 | d' 0.467 | 20.3s
Epoch 25/50 | train loss 0.25657 | val loss 0.26118 | val AUC 0.65059 | cos+ 0.7032 | cos- 0.5693 | gap 0.1338 | d' 0.500 | 20.4s *BEST*
Epoch 26/50 | train loss 0.25869 | val loss 0.26058 | val AUC 0.64814 | cos+ 0.7068 | cos- 0.5692 | gap 0.1377 | d' 0.504 | 20.3s
Epoch 27/50 | train loss 0.26091 | val loss 0.26359 | val AUC 0.64594 | cos+ 0.6988 | cos- 0.5706 | gap 0.1282 | d' 0.480 | 102.6s
Epoch 28/50 | train loss 0.25872 | val loss 0.26474 | val AUC 0.64004 | cos+ 0.7326 | cos- 0.6077 | gap 0.1248 | d' 0.458 | 105.2s
Epoch 29/50 | train loss 0.25803 | val loss 0.26333 | val AUC 0.64254 | cos+ 0.7032 | cos- 0.5731 | gap 0.1301 | d' 0.479 | 105.5s
Epoch 30/50 | train loss 0.25440 | val loss 0.26265 | val AUC 0.64677 | cos+ 0.7120 | cos- 0.5801 | gap 0.1319 | d' 0.496 | 105.5s
Epoch 31/50 | train loss 0.25733 | val loss 0.26128 | val AUC 0.64748 | cos+ 0.7183 | cos- 0.5866 | gap 0.1317 | d' 0.487 | 31.0s
Epoch 32/50 | train loss 0.25483 | val loss 0.25932 | val AUC 0.65169 | cos+ 0.7076 | cos- 0.5714 | gap 0.1362 | d' 0.508 | 23.1s *BEST*
Epoch 33/50 | train loss 0.25615 | val loss 0.26315 | val AUC 0.64324 | cos+ 0.7226 | cos- 0.5945 | gap 0.1281 | d' 0.473 | 24.4s
Epoch 34/50 | train loss 0.25464 | val loss 0.26177 | val AUC 0.64906 | cos+ 0.7121 | cos- 0.5788 | gap 0.1333 | d' 0.498 | 105.8s
Epoch 35/50 | train loss 0.25448 | val loss 0.26006 | val AUC 0.64961 | cos+ 0.7192 | cos- 0.5858 | gap 0.1334 | d' 0.502 | 105.5s
Epoch 36/50 | train loss 0.25590 | val loss 0.25903 | val AUC 0.65405 | cos+ 0.7086 | cos- 0.5710 | gap 0.1376 | d' 0.511 | 105.6s *BEST*
Epoch 37/50 | train loss 0.25568 | val loss 0.25823 | val AUC 0.65449 | cos+ 0.7213 | cos- 0.5818 | gap 0.1395 | d' 0.519 | 60.3s *BEST*

In [58]:
# ============================================================
# CELL 48 — COSINE V3 MARGIN COMPARISON
# ============================================================

margin_summary = []


for margin, result in (
    cosine_v3_margin_results.items()
):

    history = result["history"]

    best_epoch = result["best_epoch"]

    best_row = (
        history[
            history["epoch"]
            ==
            best_epoch
        ]
        .iloc[0]
    )


    margin_summary.append(
        {
            "margin":
                margin,

            "best_epoch":
                best_epoch,

            "val_auc":
                result["best_val_auc"],

            "val_loss":
                float(
                    best_row["val_loss"]
                ),

            "cos_pos":
                float(
                    best_row["cos_pos"]
                ),

            "cos_neg":
                float(
                    best_row["cos_neg"]
                ),

            "gap":
                float(
                    best_row["gap"]
                ),

            "d_prime":
                float(
                    best_row["d_prime"]
                ),
        }
    )


cosine_margin_summary_df = (
    pd.DataFrame(
        margin_summary
    )
    .sort_values(
        "val_auc",
        ascending=False,
    )
    .reset_index(
        drop=True
    )
)


display(
    cosine_margin_summary_df
)


best_cosine_margin = float(
    cosine_margin_summary_df
    .iloc[0]["margin"]
)


print()
print("=" * 70)
print("BEST COSINE V3 CONFIGURATION")
print("=" * 70)

print(
    "Margin:",
    best_cosine_margin
)

print(
    "Validation ROC-AUC:",
    f"{cosine_margin_summary_df.iloc[0]['val_auc']:.6f}"
)

,margin,best_epoch,val_auc,val_loss,cos_pos,cos_neg,gap,d_prime
0,0.35000,37,0.654489,0.258232,0.721291,0.581834,0.139456,0.518848
1,0.21875,42,0.641155,0.318893,0.654827,0.508155,0.146672,0.455734
2,0.10000,38,0.640862,0.362787,0.638347,0.462181,0.176166,0.458475
3,0.00000,44,0.629923,0.405838,0.613592,0.424624,0.188968,0.404092

======================================================================
BEST COSINE V3 CONFIGURATION
======================================================================
Margin: 0.35
Validation ROC-AUC: 0.654489

In [59]:
# ============================================================
# CELL 49 — EXTEND COSINE V3 MARGIN ABLATION
#
# Current best = 0.35, which is at the upper boundary.
# Test two slightly larger margins before touching test data.
# ============================================================

ADDITIONAL_COSINE_MARGINS = [
    0.45,
    0.50,
]


for margin in ADDITIONAL_COSINE_MARGINS:

    margin_tag = (
        str(margin)
        .replace(".", "p")
    )


    experiment_name = (
        f"cosine_v3_biasfree_margin_{margin_tag}"
    )


    print()
    print("#" * 80)
    print(
        "STARTING:",
        experiment_name
    )
    print("#" * 80)
    print()


    result = train_cosine_v3_experiment(

        margin=margin,

        experiment_name=experiment_name,
    )


    cosine_v3_margin_results[
        margin
    ] = result

################################################################################
STARTING: cosine_v3_biasfree_margin_0p45
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p45
======================================================================
Cosine margin: 0.45
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.24419 | val loss 0.24078 | val AUC 0.60072 | cos+ 0.8360 | cos- 0.7707 | gap 0.0653 | d' 0.353 | 27.6s *BEST*
Epoch 02/50 | train loss 0.23596 | val loss 0.23758 | val AUC 0.60988 | cos+ 0.7806 | cos- 0.7060 | gap 0.0747 | d' 0.357 | 20.4s *BEST*
Epoch 03/50 | train loss 0.23349 | val loss 0.23715 | val AUC 0.61426 | cos+ 0.7918 | cos- 0.7121 | gap 0.0796 | d' 0.388 | 20.7s *BEST*
Epoch 04/50 | train loss 0.23372 | val loss 0.23657 | val AUC 0.61766 | cos+ 0.7701 | cos- 0.6885 | gap 0.0816 | d' 0.410 | 46.4s *BEST*
Epoch 05/50 | train loss 0.23317 | val loss 0.23788 | val AUC 0.61315 | cos+ 0.7712 | cos- 0.6870 | gap 0.0842 | d' 0.385 | 107.4s
Epoch 06/50 | train loss 0.23116 | val loss 0.22873 | val AUC 0.63311 | cos+ 0.7675 | cos- 0.6722 | gap 0.0953 | d' 0.459 | 21.0s *BEST*
Epoch 07/50 | train loss 0.22623 | val loss 0.22831 | val AUC 0.63652 | cos+ 0.7685 | cos- 0.6705 | gap 0.0979 | d' 0.477 | 20.9s *BEST*
Epoch 08/50 | train loss 0.22905 | val loss 0.22832 | val AUC 0.63545 | cos+ 0.7491 | cos- 0.6487 | gap 0.1004 | d' 0.463 | 21.2s
Epoch 09/50 | train loss 0.22544 | val loss 0.22558 | val AUC 0.63961 | cos+ 0.7603 | cos- 0.6545 | gap 0.1058 | d' 0.466 | 46.6s *BEST*
Epoch 10/50 | train loss 0.22474 | val loss 0.22808 | val AUC 0.63952 | cos+ 0.7505 | cos- 0.6468 | gap 0.1037 | d' 0.485 | 105.3s
Epoch 11/50 | train loss 0.22512 | val loss 0.22884 | val AUC 0.62804 | cos+ 0.7615 | cos- 0.6668 | gap 0.0947 | d' 0.428 | 43.1s
Epoch 12/50 | train loss 0.22458 | val loss 0.22355 | val AUC 0.64459 | cos+ 0.7567 | cos- 0.6501 | gap 0.1066 | d' 0.487 | 20.6s *BEST*
Epoch 13/50 | train loss 0.22431 | val loss 0.22654 | val AUC 0.64059 | cos+ 0.7553 | cos- 0.6544 | gap 0.1009 | d' 0.469 | 20.8s
Epoch 14/50 | train loss 0.22253 | val loss 0.22560 | val AUC 0.63953 | cos+ 0.7527 | cos- 0.6486 | gap 0.1041 | d' 0.470 | 20.9s
Epoch 15/50 | train loss 0.22251 | val loss 0.22592 | val AUC 0.64229 | cos+ 0.7419 | cos- 0.6349 | gap 0.1070 | d' 0.474 | 106.0s
Epoch 16/50 | train loss 0.22117 | val loss 0.22290 | val AUC 0.64548 | cos+ 0.7720 | cos- 0.6657 | gap 0.1064 | d' 0.491 | 99.0s *BEST*
Epoch 17/50 | train loss 0.22030 | val loss 0.22478 | val AUC 0.64326 | cos+ 0.7553 | cos- 0.6501 | gap 0.1052 | d' 0.476 | 23.3s
Epoch 18/50 | train loss 0.22059 | val loss 0.22235 | val AUC 0.64484 | cos+ 0.7517 | cos- 0.6439 | gap 0.1078 | d' 0.490 | 23.4s
Epoch 19/50 | train loss 0.22182 | val loss 0.22209 | val AUC 0.65089 | cos+ 0.7880 | cos- 0.6804 | gap 0.1076 | d' 0.520 | 23.9s *BEST*
Epoch 20/50 | train loss 0.22171 | val loss 0.22278 | val AUC 0.65184 | cos+ 0.7503 | cos- 0.6389 | gap 0.1113 | d' 0.508 | 105.8s *BEST*
Epoch 21/50 | train loss 0.22027 | val loss 0.22273 | val AUC 0.64607 | cos+ 0.7641 | cos- 0.6549 | gap 0.1092 | d' 0.482 | 94.0s
Epoch 22/50 | train loss 0.22039 | val loss 0.22141 | val AUC 0.64947 | cos+ 0.7605 | cos- 0.6503 | gap 0.1101 | d' 0.505 | 22.1s
Epoch 23/50 | train loss 0.22059 | val loss 0.22400 | val AUC 0.64197 | cos+ 0.7699 | cos- 0.6647 | gap 0.1051 | d' 0.488 | 22.1s
Epoch 24/50 | train loss 0.21969 | val loss 0.22503 | val AUC 0.64054 | cos+ 0.7443 | cos- 0.6391 | gap 0.1051 | d' 0.466 | 22.6s
Epoch 25/50 | train loss 0.21824 | val loss 0.22220 | val AUC 0.64739 | cos+ 0.7514 | cos- 0.6399 | gap 0.1115 | d' 0.495 | 105.6s
Epoch 26/50 | train loss 0.21920 | val loss 0.22184 | val AUC 0.64956 | cos+ 0.7556 | cos- 0.6402 | gap 0.1154 | d' 0.505 | 70.5s
Epoch 27/50 | train loss 0.22151 | val loss 0.22361 | val AUC 0.64568 | cos+ 0.7419 | cos- 0.6339 | gap 0.1080 | d' 0.477 | 22.3s
Epoch 28/50 | train loss 0.21962 | val loss 0.22520 | val AUC 0.63727 | cos+ 0.7660 | cos- 0.6621 | gap 0.1038 | d' 0.451 | 22.1s
Epoch 29/50 | train loss 0.21866 | val loss 0.22198 | val AUC 0.64663 | cos+ 0.7583 | cos- 0.6456 | gap 0.1127 | d' 0.498 | 28.3s
Epoch 30/50 | train loss 0.21625 | val loss 0.22005 | val AUC 0.64849 | cos+ 0.7564 | cos- 0.6388 | gap 0.1176 | d' 0.511 | 105.5s

Early stopping at epoch 30

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 20
Best validation ROC-AUC: 0.651842

################################################################################
STARTING: cosine_v3_biasfree_margin_0p5
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p5
======================================================================
Cosine margin: 0.5
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.22457 | val loss 0.22136 | val AUC 0.58623 | cos+ 0.8615 | cos- 0.7997 | gap 0.0618 | d' 0.308 | 62.8s *BEST*
Epoch 02/50 | train loss 0.21576 | val loss 0.21395 | val AUC 0.61936 | cos+ 0.8107 | cos- 0.7385 | gap 0.0721 | d' 0.405 | 20.5s *BEST*
Epoch 03/50 | train loss 0.21213 | val loss 0.21256 | val AUC 0.62614 | cos+ 0.8185 | cos- 0.7416 | gap 0.0769 | d' 0.438 | 20.7s *BEST*
Epoch 04/50 | train loss 0.21138 | val loss 0.21152 | val AUC 0.62871 | cos+ 0.7781 | cos- 0.6933 | gap 0.0849 | d' 0.445 | 20.7s *BEST*
Epoch 05/50 | train loss 0.20902 | val loss 0.21253 | val AUC 0.61881 | cos+ 0.7854 | cos- 0.7079 | gap 0.0775 | d' 0.396 | 105.4s
Epoch 06/50 | train loss 0.20562 | val loss 0.20615 | val AUC 0.63786 | cos+ 0.7873 | cos- 0.6961 | gap 0.0911 | d' 0.472 | 79.7s *BEST*
Epoch 07/50 | train loss 0.20438 | val loss 0.20927 | val AUC 0.62854 | cos+ 0.7918 | cos- 0.7045 | gap 0.0874 | d' 0.446 | 20.4s
Epoch 08/50 | train loss 0.20724 | val loss 0.20527 | val AUC 0.63764 | cos+ 0.7815 | cos- 0.6881 | gap 0.0934 | d' 0.470 | 20.7s
Epoch 09/50 | train loss 0.20384 | val loss 0.20816 | val AUC 0.63142 | cos+ 0.7807 | cos- 0.6930 | gap 0.0876 | d' 0.426 | 22.8s
Epoch 10/50 | train loss 0.20379 | val loss 0.20498 | val AUC 0.64069 | cos+ 0.7801 | cos- 0.6871 | gap 0.0930 | d' 0.474 | 94.1s *BEST*
Epoch 11/50 | train loss 0.20382 | val loss 0.20639 | val AUC 0.63261 | cos+ 0.7867 | cos- 0.6963 | gap 0.0904 | d' 0.447 | 92.6s
Epoch 12/50 | train loss 0.20418 | val loss 0.20292 | val AUC 0.64471 | cos+ 0.7830 | cos- 0.6866 | gap 0.0964 | d' 0.486 | 22.2s *BEST*
Epoch 13/50 | train loss 0.20262 | val loss 0.20433 | val AUC 0.64260 | cos+ 0.7834 | cos- 0.6904 | gap 0.0929 | d' 0.477 | 22.5s
Epoch 14/50 | train loss 0.20196 | val loss 0.20237 | val AUC 0.64826 | cos+ 0.7802 | cos- 0.6804 | gap 0.0998 | d' 0.506 | 22.1s *BEST*
Epoch 15/50 | train loss 0.20187 | val loss 0.20435 | val AUC 0.64535 | cos+ 0.7683 | cos- 0.6698 | gap 0.0985 | d' 0.484 | 102.1s
Epoch 16/50 | train loss 0.20085 | val loss 0.20296 | val AUC 0.64547 | cos+ 0.7832 | cos- 0.6861 | gap 0.0971 | d' 0.480 | 87.4s
Epoch 17/50 | train loss 0.20012 | val loss 0.20472 | val AUC 0.64051 | cos+ 0.7787 | cos- 0.6834 | gap 0.0953 | d' 0.460 | 22.0s
Epoch 18/50 | train loss 0.20006 | val loss 0.20103 | val AUC 0.64923 | cos+ 0.7798 | cos- 0.6796 | gap 0.1002 | d' 0.504 | 22.2s *BEST*
Epoch 19/50 | train loss 0.20138 | val loss 0.20325 | val AUC 0.64536 | cos+ 0.8107 | cos- 0.7162 | gap 0.0945 | d' 0.503 | 21.8s
Epoch 20/50 | train loss 0.20079 | val loss 0.20148 | val AUC 0.65383 | cos+ 0.7723 | cos- 0.6690 | gap 0.1033 | d' 0.512 | 100.7s *BEST*
Epoch 21/50 | train loss 0.19996 | val loss 0.20145 | val AUC 0.64782 | cos+ 0.7907 | cos- 0.6890 | gap 0.1017 | d' 0.495 | 93.8s
Epoch 22/50 | train loss 0.20015 | val loss 0.19890 | val AUC 0.65455 | cos+ 0.7837 | cos- 0.6785 | gap 0.1052 | d' 0.527 | 22.2s *BEST*
Epoch 23/50 | train loss 0.19998 | val loss 0.20221 | val AUC 0.64616 | cos+ 0.7979 | cos- 0.7001 | gap 0.0978 | d' 0.503 | 21.8s
Epoch 24/50 | train loss 0.19817 | val loss 0.20358 | val AUC 0.64271 | cos+ 0.7731 | cos- 0.6759 | gap 0.0972 | d' 0.465 | 22.5s
Epoch 25/50 | train loss 0.19768 | val loss 0.19995 | val AUC 0.65054 | cos+ 0.7775 | cos- 0.6723 | gap 0.1051 | d' 0.511 | 93.6s
Epoch 26/50 | train loss 0.19829 | val loss 0.20225 | val AUC 0.64529 | cos+ 0.7748 | cos- 0.6705 | gap 0.1042 | d' 0.494 | 72.3s
Epoch 27/50 | train loss 0.20064 | val loss 0.20166 | val AUC 0.64913 | cos+ 0.7668 | cos- 0.6655 | gap 0.1014 | d' 0.497 | 23.1s
Epoch 28/50 | train loss 0.19855 | val loss 0.20246 | val AUC 0.64320 | cos+ 0.7839 | cos- 0.6844 | gap 0.0995 | d' 0.467 | 22.8s
Epoch 29/50 | train loss 0.19767 | val loss 0.20013 | val AUC 0.64911 | cos+ 0.7784 | cos- 0.6720 | gap 0.1065 | d' 0.510 | 61.1s
Epoch 30/50 | train loss 0.19565 | val loss 0.19913 | val AUC 0.65195 | cos+ 0.7805 | cos- 0.6727 | gap 0.1078 | d' 0.516 | 105.4s
Epoch 31/50 | train loss 0.19775 | val loss 0.20033 | val AUC 0.65209 | cos+ 0.7828 | cos- 0.6782 | gap 0.1046 | d' 0.503 | 69.7s
Epoch 32/50 | train loss 0.19587 | val loss 0.19996 | val AUC 0.65197 | cos+ 0.7752 | cos- 0.6706 | gap 0.1046 | d' 0.499 | 20.6s

Early stopping at epoch 32

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 22
Best validation ROC-AUC: 0.654550

In [60]:
# ============================================================
# CELL 50 — FINAL COSINE MARGIN COMPARISON
# ============================================================

margin_summary = []


for margin, result in (
    cosine_v3_margin_results.items()
):

    history = result["history"]

    best_epoch = (
        result["best_epoch"]
    )


    best_row = (
        history[
            history["epoch"]
            ==
            best_epoch
        ]
        .iloc[0]
    )


    margin_summary.append(
        {
            "margin":
                float(margin),

            "best_epoch":
                int(best_epoch),

            "val_auc":
                float(
                    result["best_val_auc"]
                ),

            "val_loss":
                float(
                    best_row["val_loss"]
                ),

            "cos_pos":
                float(
                    best_row["cos_pos"]
                ),

            "cos_neg":
                float(
                    best_row["cos_neg"]
                ),

            "gap":
                float(
                    best_row["gap"]
                ),

            "d_prime":
                float(
                    best_row["d_prime"]
                ),
        }
    )


cosine_margin_final_df = (
    pd.DataFrame(
        margin_summary
    )
    .sort_values(
        "val_auc",
        ascending=False,
    )
    .reset_index(
        drop=True
    )
)


display(
    cosine_margin_final_df
)


best_cosine_margin = float(
    cosine_margin_final_df
    .iloc[0]["margin"]
)


best_cosine_val_auc = float(
    cosine_margin_final_df
    .iloc[0]["val_auc"]
)


print()
print("=" * 70)
print("FINAL BEST COSINE CONFIGURATION")
print("=" * 70)

print(
    "Margin:",
    best_cosine_margin
)

print(
    "Validation ROC-AUC:",
    f"{best_cosine_val_auc:.6f}"
)

,margin,best_epoch,val_auc,val_loss,cos_pos,cos_neg,gap,d_prime
0,0.50000,22,0.654550,0.198905,0.783665,0.678513,0.105152,0.527464
1,0.35000,37,0.654489,0.258232,0.721291,0.581834,0.139456,0.518848
2,0.45000,20,0.651842,0.222783,0.750260,0.638935,0.111324,0.507868
3,0.21875,42,0.641155,0.318893,0.654827,0.508155,0.146672,0.455734
4,0.10000,38,0.640862,0.362787,0.638347,0.462181,0.176166,0.458475
5,0.00000,44,0.629923,0.405838,0.613592,0.424624,0.188968,0.404092

======================================================================
FINAL BEST COSINE CONFIGURATION
======================================================================
Margin: 0.5
Validation ROC-AUC: 0.654550

In [61]:
# ============================================================
# CELL 51 — OVERNIGHT COSINE MARGIN EXTENSION
#
# Only two additional points.
# Do not touch the test set.
# ============================================================

OVERNIGHT_COSINE_MARGINS = [
    0.60,
    0.70,
]


for margin in OVERNIGHT_COSINE_MARGINS:

    margin_tag = (
        str(margin)
        .replace(".", "p")
    )

    experiment_name = (
        f"cosine_v3_biasfree_margin_{margin_tag}"
    )

    print()
    print("#" * 80)
    print(
        "STARTING:",
        experiment_name
    )
    print("#" * 80)
    print()

    result = train_cosine_v3_experiment(
        margin=margin,
        experiment_name=experiment_name,
    )

    cosine_v3_margin_results[
        margin
    ] = result

################################################################################
STARTING: cosine_v3_biasfree_margin_0p6
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p6
======================================================================
Cosine margin: 0.6
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.18004 | val loss 0.18495 | val AUC 0.55903 | cos+ 0.9139 | cos- 0.8878 | gap 0.0260 | d' 0.182 | 20.9s *BEST*
Epoch 02/50 | train loss 0.17278 | val loss 0.17350 | val AUC 0.61061 | cos+ 0.8605 | cos- 0.8088 | gap 0.0516 | d' 0.359 | 23.3s *BEST*
Epoch 03/50 | train loss 0.16990 | val loss 0.17267 | val AUC 0.61749 | cos+ 0.8540 | cos- 0.8003 | gap 0.0537 | d' 0.404 | 105.4s *BEST*
Epoch 04/50 | train loss 0.17111 | val loss 0.17328 | val AUC 0.61853 | cos+ 0.8131 | cos- 0.7471 | gap 0.0660 | d' 0.404 | 89.4s *BEST*
Epoch 05/50 | train loss 0.16921 | val loss 0.17036 | val AUC 0.61612 | cos+ 0.8345 | cos- 0.7747 | gap 0.0598 | d' 0.391 | 22.9s
Epoch 06/50 | train loss 0.16749 | val loss 0.16798 | val AUC 0.63126 | cos+ 0.8418 | cos- 0.7760 | gap 0.0658 | d' 0.447 | 22.8s *BEST*
Epoch 07/50 | train loss 0.16474 | val loss 0.16674 | val AUC 0.63604 | cos+ 0.8398 | cos- 0.7682 | gap 0.0716 | d' 0.476 | 35.3s *BEST*
Epoch 08/50 | train loss 0.16671 | val loss 0.16626 | val AUC 0.63688 | cos+ 0.8285 | cos- 0.7558 | gap 0.0726 | d' 0.471 | 106.2s *BEST*
Epoch 09/50 | train loss 0.16336 | val loss 0.16519 | val AUC 0.63663 | cos+ 0.8296 | cos- 0.7559 | gap 0.0737 | d' 0.462 | 100.1s
Epoch 10/50 | train loss 0.16331 | val loss 0.16655 | val AUC 0.62845 | cos+ 0.8295 | cos- 0.7590 | gap 0.0705 | d' 0.438 | 22.5s
Epoch 11/50 | train loss 0.16406 | val loss 0.16316 | val AUC 0.64192 | cos+ 0.8329 | cos- 0.7569 | gap 0.0760 | d' 0.488 | 22.7s *BEST*
Epoch 12/50 | train loss 0.16300 | val loss 0.16242 | val AUC 0.64634 | cos+ 0.8228 | cos- 0.7433 | gap 0.0794 | d' 0.488 | 22.4s *BEST*
Epoch 13/50 | train loss 0.16292 | val loss 0.16232 | val AUC 0.64765 | cos+ 0.8243 | cos- 0.7455 | gap 0.0788 | d' 0.498 | 105.6s *BEST*
Epoch 14/50 | train loss 0.16172 | val loss 0.16204 | val AUC 0.65008 | cos+ 0.8264 | cos- 0.7460 | gap 0.0803 | d' 0.517 | 105.7s *BEST*
Epoch 15/50 | train loss 0.16181 | val loss 0.16375 | val AUC 0.64511 | cos+ 0.8171 | cos- 0.7392 | gap 0.0779 | d' 0.484 | 22.1s
Epoch 16/50 | train loss 0.16133 | val loss 0.16141 | val AUC 0.65004 | cos+ 0.8385 | cos- 0.7592 | gap 0.0793 | d' 0.515 | 22.1s
Epoch 17/50 | train loss 0.16050 | val loss 0.16234 | val AUC 0.64806 | cos+ 0.8199 | cos- 0.7385 | gap 0.0815 | d' 0.497 | 22.4s
Epoch 18/50 | train loss 0.16066 | val loss 0.16070 | val AUC 0.65364 | cos+ 0.8257 | cos- 0.7448 | gap 0.0809 | d' 0.514 | 89.5s *BEST*
Epoch 19/50 | train loss 0.16169 | val loss 0.16506 | val AUC 0.63811 | cos+ 0.8524 | cos- 0.7821 | gap 0.0703 | d' 0.475 | 80.0s
Epoch 20/50 | train loss 0.16158 | val loss 0.16203 | val AUC 0.65174 | cos+ 0.8190 | cos- 0.7380 | gap 0.0810 | d' 0.503 | 22.5s
Epoch 21/50 | train loss 0.16031 | val loss 0.16156 | val AUC 0.64658 | cos+ 0.8331 | cos- 0.7526 | gap 0.0805 | d' 0.494 | 22.3s
Epoch 22/50 | train loss 0.16102 | val loss 0.15967 | val AUC 0.65265 | cos+ 0.8272 | cos- 0.7435 | gap 0.0837 | d' 0.523 | 22.4s
Epoch 23/50 | train loss 0.16040 | val loss 0.16082 | val AUC 0.64864 | cos+ 0.8362 | cos- 0.7552 | gap 0.0811 | d' 0.517 | 81.6s
Epoch 24/50 | train loss 0.15874 | val loss 0.16162 | val AUC 0.64318 | cos+ 0.8286 | cos- 0.7485 | gap 0.0801 | d' 0.468 | 88.0s
Epoch 25/50 | train loss 0.15897 | val loss 0.16133 | val AUC 0.64892 | cos+ 0.8200 | cos- 0.7379 | gap 0.0821 | d' 0.498 | 22.2s
Epoch 26/50 | train loss 0.15970 | val loss 0.16041 | val AUC 0.65180 | cos+ 0.8295 | cos- 0.7446 | gap 0.0849 | d' 0.515 | 22.3s
Epoch 27/50 | train loss 0.16073 | val loss 0.16134 | val AUC 0.64809 | cos+ 0.8206 | cos- 0.7385 | gap 0.0821 | d' 0.502 | 23.4s
Epoch 28/50 | train loss 0.15936 | val loss 0.16150 | val AUC 0.64226 | cos+ 0.8377 | cos- 0.7575 | gap 0.0803 | d' 0.470 | 98.5s

Early stopping at epoch 28

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 18
Best validation ROC-AUC: 0.653643

################################################################################
STARTING: cosine_v3_biasfree_margin_0p7
################################################################################

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p7
======================================================================
Cosine margin: 0.7
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.13522 | val loss 0.13475 | val AUC 0.58936 | cos+ 0.9469 | cos- 0.9194 | gap 0.0276 | d' 0.317 | 81.1s *BEST*
Epoch 02/50 | train loss 0.12960 | val loss 0.12849 | val AUC 0.61676 | cos+ 0.8951 | cos- 0.8527 | gap 0.0424 | d' 0.397 | 22.4s *BEST*
Epoch 03/50 | train loss 0.12771 | val loss 0.12840 | val AUC 0.62426 | cos+ 0.8922 | cos- 0.8472 | gap 0.0449 | d' 0.433 | 22.2s *BEST*
Epoch 04/50 | train loss 0.12785 | val loss 0.12875 | val AUC 0.62553 | cos+ 0.8614 | cos- 0.8094 | gap 0.0521 | d' 0.433 | 22.7s *BEST*
Epoch 05/50 | train loss 0.12570 | val loss 0.12627 | val AUC 0.63328 | cos+ 0.8791 | cos- 0.8288 | gap 0.0503 | d' 0.463 | 105.6s *BEST*
Epoch 06/50 | train loss 0.12410 | val loss 0.12385 | val AUC 0.63785 | cos+ 0.8754 | cos- 0.8202 | gap 0.0552 | d' 0.475 | 83.2s *BEST*
Epoch 07/50 | train loss 0.12318 | val loss 0.12496 | val AUC 0.63543 | cos+ 0.8744 | cos- 0.8190 | gap 0.0554 | d' 0.475 | 22.3s
Epoch 08/50 | train loss 0.12520 | val loss 0.12389 | val AUC 0.63906 | cos+ 0.8704 | cos- 0.8142 | gap 0.0562 | d' 0.480 | 22.3s *BEST*
Epoch 09/50 | train loss 0.12266 | val loss 0.12388 | val AUC 0.63614 | cos+ 0.8742 | cos- 0.8191 | gap 0.0551 | d' 0.458 | 22.6s
Epoch 10/50 | train loss 0.12197 | val loss 0.12322 | val AUC 0.63711 | cos+ 0.8738 | cos- 0.8186 | gap 0.0552 | d' 0.465 | 105.7s
Epoch 11/50 | train loss 0.12306 | val loss 0.12478 | val AUC 0.63125 | cos+ 0.8744 | cos- 0.8210 | gap 0.0534 | d' 0.448 | 71.7s
Epoch 12/50 | train loss 0.12256 | val loss 0.12169 | val AUC 0.64750 | cos+ 0.8726 | cos- 0.8133 | gap 0.0593 | d' 0.507 | 22.1s *BEST*
Epoch 13/50 | train loss 0.12176 | val loss 0.12325 | val AUC 0.64015 | cos+ 0.8711 | cos- 0.8166 | gap 0.0545 | d' 0.475 | 22.3s
Epoch 14/50 | train loss 0.12174 | val loss 0.12417 | val AUC 0.63832 | cos+ 0.8743 | cos- 0.8202 | gap 0.0541 | d' 0.479 | 26.2s
Epoch 15/50 | train loss 0.12149 | val loss 0.12349 | val AUC 0.64414 | cos+ 0.8594 | cos- 0.7998 | gap 0.0596 | d' 0.483 | 105.5s
Epoch 16/50 | train loss 0.12112 | val loss 0.12241 | val AUC 0.64472 | cos+ 0.8688 | cos- 0.8117 | gap 0.0571 | d' 0.479 | 61.6s
Epoch 17/50 | train loss 0.12055 | val loss 0.12173 | val AUC 0.64618 | cos+ 0.8685 | cos- 0.8079 | gap 0.0606 | d' 0.494 | 22.4s
Epoch 18/50 | train loss 0.12053 | val loss 0.12116 | val AUC 0.65002 | cos+ 0.8701 | cos- 0.8111 | gap 0.0590 | d' 0.506 | 22.3s *BEST*
Epoch 19/50 | train loss 0.12153 | val loss 0.12295 | val AUC 0.63851 | cos+ 0.8869 | cos- 0.8328 | gap 0.0541 | d' 0.469 | 32.2s
Epoch 20/50 | train loss 0.12081 | val loss 0.12117 | val AUC 0.65230 | cos+ 0.8655 | cos- 0.8044 | gap 0.0610 | d' 0.508 | 105.4s *BEST*
Epoch 21/50 | train loss 0.12036 | val loss 0.12108 | val AUC 0.64853 | cos+ 0.8736 | cos- 0.8118 | gap 0.0617 | d' 0.499 | 55.6s
Epoch 22/50 | train loss 0.12059 | val loss 0.12019 | val AUC 0.65110 | cos+ 0.8736 | cos- 0.8115 | gap 0.0621 | d' 0.516 | 21.9s
Epoch 23/50 | train loss 0.12014 | val loss 0.12025 | val AUC 0.65050 | cos+ 0.8782 | cos- 0.8166 | gap 0.0616 | d' 0.519 | 22.5s
Epoch 24/50 | train loss 0.11884 | val loss 0.12142 | val AUC 0.64420 | cos+ 0.8710 | cos- 0.8107 | gap 0.0603 | d' 0.468 | 22.4s
Epoch 25/50 | train loss 0.11898 | val loss 0.12050 | val AUC 0.65248 | cos+ 0.8650 | cos- 0.8011 | gap 0.0639 | d' 0.524 | 105.5s *BEST*
Epoch 26/50 | train loss 0.11968 | val loss 0.12065 | val AUC 0.64941 | cos+ 0.8665 | cos- 0.8029 | gap 0.0636 | d' 0.505 | 51.4s
Epoch 27/50 | train loss 0.12073 | val loss 0.12138 | val AUC 0.64564 | cos+ 0.8627 | cos- 0.8033 | gap 0.0594 | d' 0.494 | 22.3s
Epoch 28/50 | train loss 0.11959 | val loss 0.12307 | val AUC 0.63759 | cos+ 0.8716 | cos- 0.8146 | gap 0.0570 | d' 0.448 | 22.3s
Epoch 29/50 | train loss 0.11904 | val loss 0.12110 | val AUC 0.64789 | cos+ 0.8681 | cos- 0.8058 | gap 0.0622 | d' 0.502 | 22.9s
Epoch 30/50 | train loss 0.11763 | val loss 0.12098 | val AUC 0.64967 | cos+ 0.8653 | cos- 0.8017 | gap 0.0636 | d' 0.497 | 105.6s
Epoch 31/50 | train loss 0.11908 | val loss 0.11958 | val AUC 0.65490 | cos+ 0.8711 | cos- 0.8079 | gap 0.0632 | d' 0.520 | 54.9s *BEST*
Epoch 32/50 | train loss 0.11779 | val loss 0.12090 | val AUC 0.65140 | cos+ 0.8626 | cos- 0.8009 | gap 0.0617 | d' 0.499 | 22.2s
Epoch 33/50 | train loss 0.11905 | val loss 0.11974 | val AUC 0.65133 | cos+ 0.8762 | cos- 0.8136 | gap 0.0625 | d' 0.513 | 23.6s
Epoch 34/50 | train loss 0.11812 | val loss 0.11975 | val AUC 0.65525 | cos+ 0.8701 | cos- 0.8059 | gap 0.0643 | d' 0.529 | 22.8s *BEST*
Epoch 35/50 | train loss 0.11727 | val loss 0.11927 | val AUC 0.65005 | cos+ 0.8752 | cos- 0.8123 | gap 0.0629 | d' 0.523 | 105.5s
Epoch 36/50 | train loss 0.11812 | val loss 0.11961 | val AUC 0.65488 | cos+ 0.8685 | cos- 0.8055 | gap 0.0630 | d' 0.514 | 52.6s
Epoch 37/50 | train loss 0.11829 | val loss 0.11908 | val AUC 0.65619 | cos+ 0.8744 | cos- 0.8086 | gap 0.0658 | d' 0.528 | 22.4s *BEST*
Epoch 38/50 | train loss 0.11765 | val loss 0.11916 | val AUC 0.65144 | cos+ 0.8744 | cos- 0.8104 | gap 0.0639 | d' 0.519 | 22.4s
Epoch 39/50 | train loss 0.11761 | val loss 0.11969 | val AUC 0.65126 | cos+ 0.8707 | cos- 0.8084 | gap 0.0624 | d' 0.505 | 34.5s
Epoch 40/50 | train loss 0.11745 | val loss 0.11942 | val AUC 0.65190 | cos+ 0.8770 | cos- 0.8133 | gap 0.0637 | d' 0.519 | 105.5s
Epoch 41/50 | train loss 0.11858 | val loss 0.11917 | val AUC 0.65500 | cos+ 0.8663 | cos- 0.8019 | gap 0.0644 | d' 0.524 | 49.6s
Epoch 42/50 | train loss 0.11749 | val loss 0.11823 | val AUC 0.65691 | cos+ 0.8767 | cos- 0.8109 | gap 0.0658 | d' 0.532 | 22.3s *BEST*
Epoch 43/50 | train loss 0.11634 | val loss 0.11880 | val AUC 0.65393 | cos+ 0.8710 | cos- 0.8073 | gap 0.0638 | d' 0.514 | 22.4s
Epoch 44/50 | train loss 0.11702 | val loss 0.12165 | val AUC 0.64047 | cos+ 0.8771 | cos- 0.8187 | gap 0.0584 | d' 0.446 | 32.1s
Epoch 45/50 | train loss 0.11626 | val loss 0.11871 | val AUC 0.65504 | cos+ 0.8718 | cos- 0.8067 | gap 0.0651 | d' 0.527 | 105.8s
Epoch 46/50 | train loss 0.11633 | val loss 0.11877 | val AUC 0.65720 | cos+ 0.8670 | cos- 0.8010 | gap 0.0660 | d' 0.527 | 54.0s *BEST*
Epoch 47/50 | train loss 0.11704 | val loss 0.11938 | val AUC 0.65357 | cos+ 0.8692 | cos- 0.8059 | gap 0.0633 | d' 0.515 | 22.6s
Epoch 48/50 | train loss 0.11693 | val loss 0.11862 | val AUC 0.65525 | cos+ 0.8710 | cos- 0.8058 | gap 0.0652 | d' 0.522 | 22.4s
Epoch 49/50 | train loss 0.11602 | val loss 0.11902 | val AUC 0.65233 | cos+ 0.8675 | cos- 0.8018 | gap 0.0657 | d' 0.518 | 22.0s
Epoch 50/50 | train loss 0.11615 | val loss 0.11933 | val AUC 0.65412 | cos+ 0.8651 | cos- 0.8009 | gap 0.0642 | d' 0.511 | 105.6s

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 46
Best validation ROC-AUC: 0.657201

In [63]:
# ============================================================
# CELL 53 — FINAL BOUNDARY CHECK: MARGIN 0.80
# ============================================================

margin = 0.80

result_080 = train_cosine_v3_experiment(
    margin=margin,
    experiment_name="cosine_v3_biasfree_margin_0p80",
)

cosine_v3_margin_results[
    margin
] = result_080

======================================================================
EXPERIMENT: cosine_v3_biasfree_margin_0p80
======================================================================
Cosine margin: 0.8
Learning rate: 0.0005
Fused AdamW: True
AMP: True
Max epochs: 50
Early stopping patience: 10

Epoch 01/50 | train loss 0.09127 | val loss 0.08832 | val AUC 0.60634 | cos+ 0.9578 | cos- 0.9351 | gap 0.0227 | d' 0.359 | 21.6s *BEST*
Epoch 02/50 | train loss 0.08714 | val loss 0.08599 | val AUC 0.61730 | cos+ 0.9299 | cos- 0.9019 | gap 0.0280 | d' 0.403 | 22.5s *BEST*
Epoch 03/50 | train loss 0.08550 | val loss 0.08724 | val AUC 0.61276 | cos+ 0.9374 | cos- 0.9128 | gap 0.0247 | d' 0.386 | 22.5s
Epoch 04/50 | train loss 0.08565 | val loss 0.08604 | val AUC 0.61935 | cos+ 0.9144 | cos- 0.8836 | gap 0.0308 | d' 0.413 | 22.6s *BEST*
Epoch 05/50 | train loss 0.08396 | val loss 0.08448 | val AUC 0.62948 | cos+ 0.9173 | cos- 0.8825 | gap 0.0348 | d' 0.451 | 20.2s *BEST*
Epoch 06/50 | train loss 0.08361 | val loss 0.08320 | val AUC 0.63745 | cos+ 0.9206 | cos- 0.8860 | gap 0.0346 | d' 0.475 | 69.5s *BEST*
Epoch 07/50 | train loss 0.08238 | val loss 0.08347 | val AUC 0.63794 | cos+ 0.9177 | cos- 0.8801 | gap 0.0376 | d' 0.484 | 22.1s *BEST*
Epoch 08/50 | train loss 0.08434 | val loss 0.08489 | val AUC 0.62268 | cos+ 0.9232 | cos- 0.8912 | gap 0.0320 | d' 0.428 | 23.8s
Epoch 09/50 | train loss 0.08236 | val loss 0.08285 | val AUC 0.63765 | cos+ 0.9193 | cos- 0.8833 | gap 0.0361 | d' 0.465 | 22.2s
Epoch 10/50 | train loss 0.08178 | val loss 0.08228 | val AUC 0.64346 | cos+ 0.9171 | cos- 0.8803 | gap 0.0368 | d' 0.490 | 22.1s *BEST*
Epoch 11/50 | train loss 0.08247 | val loss 0.08293 | val AUC 0.63442 | cos+ 0.9195 | cos- 0.8843 | gap 0.0352 | d' 0.462 | 22.7s
Epoch 12/50 | train loss 0.08202 | val loss 0.08199 | val AUC 0.64582 | cos+ 0.9126 | cos- 0.8720 | gap 0.0406 | d' 0.496 | 53.7s *BEST*
Epoch 13/50 | train loss 0.08225 | val loss 0.08424 | val AUC 0.63059 | cos+ 0.9206 | cos- 0.8883 | gap 0.0323 | d' 0.451 | 70.9s
Epoch 14/50 | train loss 0.08132 | val loss 0.08229 | val AUC 0.64044 | cos+ 0.9126 | cos- 0.8742 | gap 0.0384 | d' 0.480 | 21.1s
Epoch 15/50 | train loss 0.08138 | val loss 0.08162 | val AUC 0.64795 | cos+ 0.9105 | cos- 0.8701 | gap 0.0404 | d' 0.507 | 23.7s *BEST*
Epoch 16/50 | train loss 0.08124 | val loss 0.08087 | val AUC 0.65038 | cos+ 0.9166 | cos- 0.8762 | gap 0.0403 | d' 0.518 | 23.1s *BEST*
Epoch 17/50 | train loss 0.08078 | val loss 0.08234 | val AUC 0.63797 | cos+ 0.9153 | cos- 0.8780 | gap 0.0373 | d' 0.464 | 22.7s
Epoch 18/50 | train loss 0.08097 | val loss 0.08193 | val AUC 0.64885 | cos+ 0.9201 | cos- 0.8839 | gap 0.0362 | d' 0.504 | 103.1s
Epoch 19/50 | train loss 0.08123 | val loss 0.08141 | val AUC 0.64587 | cos+ 0.9234 | cos- 0.8861 | gap 0.0373 | d' 0.499 | 38.1s
Epoch 20/50 | train loss 0.08073 | val loss 0.08107 | val AUC 0.65163 | cos+ 0.9120 | cos- 0.8716 | gap 0.0403 | d' 0.510 | 20.3s *BEST*
Epoch 21/50 | train loss 0.08075 | val loss 0.08149 | val AUC 0.64556 | cos+ 0.9152 | cos- 0.8741 | gap 0.0411 | d' 0.492 | 20.5s
Epoch 22/50 | train loss 0.08071 | val loss 0.08080 | val AUC 0.65058 | cos+ 0.9188 | cos- 0.8795 | gap 0.0393 | d' 0.510 | 20.8s
Epoch 23/50 | train loss 0.08067 | val loss 0.08141 | val AUC 0.64510 | cos+ 0.9225 | cos- 0.8843 | gap 0.0382 | d' 0.499 | 62.7s
Epoch 24/50 | train loss 0.08073 | val loss 0.08104 | val AUC 0.64493 | cos+ 0.9141 | cos- 0.8741 | gap 0.0400 | d' 0.481 | 41.8s
Epoch 25/50 | train loss 0.07979 | val loss 0.08170 | val AUC 0.64435 | cos+ 0.9092 | cos- 0.8686 | gap 0.0407 | d' 0.485 | 22.6s
Epoch 26/50 | train loss 0.08033 | val loss 0.08053 | val AUC 0.65236 | cos+ 0.9109 | cos- 0.8671 | gap 0.0438 | d' 0.524 | 22.8s *BEST*
Epoch 27/50 | train loss 0.08071 | val loss 0.08195 | val AUC 0.64184 | cos+ 0.9076 | cos- 0.8685 | gap 0.0391 | d' 0.465 | 68.4s
Epoch 28/50 | train loss 0.07992 | val loss 0.08241 | val AUC 0.63318 | cos+ 0.9148 | cos- 0.8773 | gap 0.0376 | d' 0.439 | 37.8s
Epoch 29/50 | train loss 0.07984 | val loss 0.08096 | val AUC 0.64830 | cos+ 0.9119 | cos- 0.8705 | gap 0.0414 | d' 0.499 | 22.5s
Epoch 30/50 | train loss 0.07902 | val loss 0.08098 | val AUC 0.65083 | cos+ 0.9104 | cos- 0.8673 | gap 0.0431 | d' 0.509 | 23.0s
Epoch 31/50 | train loss 0.07951 | val loss 0.08014 | val AUC 0.65198 | cos+ 0.9149 | cos- 0.8734 | gap 0.0415 | d' 0.510 | 94.0s
Epoch 32/50 | train loss 0.07883 | val loss 0.08009 | val AUC 0.65208 | cos+ 0.9127 | cos- 0.8714 | gap 0.0413 | d' 0.505 | 62.7s
Epoch 33/50 | train loss 0.07975 | val loss 0.07966 | val AUC 0.65400 | cos+ 0.9139 | cos- 0.8713 | gap 0.0426 | d' 0.526 | 20.2s *BEST*
Epoch 34/50 | train loss 0.07893 | val loss 0.07983 | val AUC 0.65564 | cos+ 0.9119 | cos- 0.8684 | gap 0.0435 | d' 0.531 | 20.3s *BEST*
Epoch 35/50 | train loss 0.07861 | val loss 0.07990 | val AUC 0.64827 | cos+ 0.9153 | cos- 0.8731 | gap 0.0421 | d' 0.514 | 20.7s
Epoch 36/50 | train loss 0.07872 | val loss 0.07937 | val AUC 0.65791 | cos+ 0.9140 | cos- 0.8705 | gap 0.0435 | d' 0.532 | 65.0s *BEST*
Epoch 37/50 | train loss 0.07904 | val loss 0.07973 | val AUC 0.65448 | cos+ 0.9161 | cos- 0.8716 | gap 0.0444 | d' 0.521 | 88.4s
Epoch 38/50 | train loss 0.07882 | val loss 0.07919 | val AUC 0.65801 | cos+ 0.9165 | cos- 0.8737 | gap 0.0428 | d' 0.536 | 20.2s *BEST*
Epoch 39/50 | train loss 0.07874 | val loss 0.07952 | val AUC 0.65257 | cos+ 0.9121 | cos- 0.8695 | gap 0.0426 | d' 0.517 | 20.6s
Epoch 40/50 | train loss 0.07878 | val loss 0.07926 | val AUC 0.65200 | cos+ 0.9200 | cos- 0.8775 | gap 0.0425 | d' 0.527 | 20.5s
Epoch 41/50 | train loss 0.07937 | val loss 0.07976 | val AUC 0.65300 | cos+ 0.9136 | cos- 0.8717 | gap 0.0419 | d' 0.517 | 24.5s
Epoch 42/50 | train loss 0.07866 | val loss 0.07919 | val AUC 0.65558 | cos+ 0.9159 | cos- 0.8721 | gap 0.0438 | d' 0.531 | 105.2s
Epoch 43/50 | train loss 0.07755 | val loss 0.07918 | val AUC 0.65605 | cos+ 0.9153 | cos- 0.8720 | gap 0.0432 | d' 0.520 | 39.8s
Epoch 44/50 | train loss 0.07855 | val loss 0.07935 | val AUC 0.65491 | cos+ 0.9144 | cos- 0.8715 | gap 0.0429 | d' 0.518 | 22.1s
Epoch 45/50 | train loss 0.07731 | val loss 0.07941 | val AUC 0.65268 | cos+ 0.9185 | cos- 0.8770 | gap 0.0416 | d' 0.520 | 22.2s
Epoch 46/50 | train loss 0.07823 | val loss 0.07908 | val AUC 0.65991 | cos+ 0.9124 | cos- 0.8681 | gap 0.0443 | d' 0.533 | 22.5s *BEST*
Epoch 47/50 | train loss 0.07815 | val loss 0.07935 | val AUC 0.65643 | cos+ 0.9122 | cos- 0.8687 | gap 0.0435 | d' 0.529 | 104.2s
Epoch 48/50 | train loss 0.07792 | val loss 0.07979 | val AUC 0.65193 | cos+ 0.9147 | cos- 0.8729 | gap 0.0418 | d' 0.504 | 49.2s
Epoch 49/50 | train loss 0.07780 | val loss 0.07922 | val AUC 0.65397 | cos+ 0.9124 | cos- 0.8684 | gap 0.0440 | d' 0.530 | 22.5s
Epoch 50/50 | train loss 0.07775 | val loss 0.07913 | val AUC 0.65816 | cos+ 0.9123 | cos- 0.8683 | gap 0.0440 | d' 0.528 | 22.4s

======================================================================
TRAINING COMPLETE
======================================================================
Best epoch: 46
Best validation ROC-AUC: 0.659911

In [64]:
# ============================================================
# CELL 52 — OVERNIGHT FINAL SUMMARY
# ============================================================

overnight_summary = []


for margin, result in cosine_v3_margin_results.items():

    history = result["history"]

    best_epoch = result["best_epoch"]

    best_row = (
        history[
            history["epoch"] == best_epoch
        ]
        .iloc[0]
    )

    overnight_summary.append(
        {
            "margin":
                float(margin),

            "best_epoch":
                int(best_epoch),

            "val_auc":
                float(
                    result["best_val_auc"]
                ),

            "val_loss":
                float(
                    best_row["val_loss"]
                ),

            "cos_pos":
                float(
                    best_row["cos_pos"]
                ),

            "cos_neg":
                float(
                    best_row["cos_neg"]
                ),

            "gap":
                float(
                    best_row["gap"]
                ),

            "d_prime":
                float(
                    best_row["d_prime"]
                ),
        }
    )


overnight_summary_df = (
    pd.DataFrame(
        overnight_summary
    )
    .sort_values(
        "val_auc",
        ascending=False,
    )
    .reset_index(
        drop=True
    )
)


display(
    overnight_summary_df
)


print()
print("=" * 70)
print("BEST COSINE CONFIGURATION AFTER OVERNIGHT RUNS")
print("=" * 70)

print(
    "Margin:",
    overnight_summary_df.iloc[0]["margin"]
)

print(
    "Validation ROC-AUC:",
    f"{overnight_summary_df.iloc[0]['val_auc']:.6f}"
)

print(
    "d-prime:",
    f"{overnight_summary_df.iloc[0]['d_prime']:.6f}"
)

,margin,best_epoch,val_auc,val_loss,cos_pos,cos_neg,gap,d_prime
0,0.80000,46,0.659911,0.079082,0.912439,0.868127,0.044311,0.533434
1,0.70000,46,0.657201,0.118772,0.867044,0.801033,0.066011,0.526738
2,0.50000,22,0.654550,0.198905,0.783665,0.678513,0.105152,0.527464
3,0.35000,37,0.654489,0.258232,0.721291,0.581834,0.139456,0.518848
4,0.60000,18,0.653643,0.160698,0.825663,0.744777,0.080886,0.513868
5,0.45000,20,0.651842,0.222783,0.750260,0.638935,0.111324,0.507868
6,0.21875,42,0.641155,0.318893,0.654827,0.508155,0.146672,0.455734
7,0.10000,38,0.640862,0.362787,0.638347,0.462181,0.176166,0.458475
8,0.00000,44,0.629923,0.405838,0.613592,0.424624,0.188968,0.404092

======================================================================
BEST COSINE CONFIGURATION AFTER OVERNIGHT RUNS
======================================================================
Margin: 0.8
Validation ROC-AUC: 0.659911
d-prime: 0.533434

In [70]:
# ============================================================
# SAVE BEST COSINE V3 MODEL BEFORE KERNEL RESTART
# ============================================================

from pathlib import Path
import torch
import json

SAVE_DIR = Path("../artifacts/cosine_v3")
SAVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

best_cosine_result = cosine_v3_margin_results[
    0.80
]

best_cosine_model = best_cosine_result[
    "model"
]


# ------------------------------------------------------------
# SAVE MODEL CHECKPOINT
# ------------------------------------------------------------

checkpoint_path = (
    SAVE_DIR
    /
    "cosine_v3_margin_0p80_best.pt"
)

torch.save(
    {
        "model_state_dict":
            best_cosine_model.state_dict(),

        "embedding_dim":
            EMBEDDING_DIM,

        "margin":
            0.80,

        "best_epoch":
            best_cosine_result["best_epoch"],

        "best_val_auc":
            best_cosine_result["best_val_auc"],

        "architecture":
            "SiameseNetworkCosineV3",

        "conv_bias":
            False,
    },
    checkpoint_path,
)


# ------------------------------------------------------------
# SAVE TRAINING HISTORY
# ------------------------------------------------------------

history_path = (
    SAVE_DIR
    /
    "cosine_v3_margin_0p80_history.tsv"
)

best_cosine_result[
    "history"
].to_csv(
    history_path,
    sep="\t",
    index=False,
)


print("=" * 70)
print("COSINE V3 SAVED")
print("=" * 70)

print(
    "Checkpoint:",
    checkpoint_path
)

print(
    "History:",
    history_path
)

print(
    "Best epoch:",
    best_cosine_result["best_epoch"]
)

print(
    "Best Val ROC-AUC:",
    best_cosine_result["best_val_auc"]
)

======================================================================
COSINE V3 SAVED
======================================================================
Checkpoint: ..\artifacts\cosine_v3\cosine_v3_margin_0p80_best.pt
History: ..\artifacts\cosine_v3\cosine_v3_margin_0p80_history.tsv
Best epoch: 46
Best Val ROC-AUC: 0.6599109638794127

In [71]:
# ============================================================
# SAVE COSINE MARGIN ABLATION SUMMARY
# ============================================================

margin_ablation_path = (
    SAVE_DIR
    /
    "cosine_v3_margin_ablation.tsv"
)

cosine_margin_final_df.to_csv(
    margin_ablation_path,
    sep="\t",
    index=False,
)

print(
    "Margin ablation saved:",
    margin_ablation_path
)

Margin ablation saved: ..\artifacts\cosine_v3\cosine_v3_margin_ablation.tsv

In [72]:
checkpoint = torch.load(
    "../artifacts/cosine_v3/cosine_v3_margin_0p80_best.pt",
    map_location=DEVICE,
)

best_cosine_model = SiameseNetworkCosineV3(
    embedding_dim=checkpoint["embedding_dim"]
).to(DEVICE)

best_cosine_model.load_state_dict(
    checkpoint["model_state_dict"]
)

best_cosine_model.eval()

print(
    "Loaded margin:",
    checkpoint["margin"]
)

print(
    "Best epoch:",
    checkpoint["best_epoch"]
)

print(
    "Best Val AUC:",
    checkpoint["best_val_auc"]
)

Loaded margin: 0.8
Best epoch: 46
Best Val AUC: 0.6599109638794127